### ISSUE TITLE
No alarm for go.d/portcheck

### ISSUE THREAD

**Issue by mihailigoshin** [netdata/netdata#10043]
Port 22 is open and status is green (as should be), port 19999 is not present and is red as failed (as should be) from the charts, but it is missing alarm for it. 

```cmd
/etc/netdata/go.d:
total 4
-rw-r--r-- 1 root root 2264 Oct  8 13:46 portcheck.conf
```

```cmd
/etc/netdata/health.d:
total 4
-rw-r--r-- 1 root root 1490 Oct  6 09:53 portcheck.conf
```

```yaml
###
jobs:
 - name: job1
   host: lx9
   ports: [22, 19999]
###
```

```cmd
$ grep "\[health\]" -A 11 /etc/netdata/netdata.conf 
[health]
	# silencers file = /var/lib/netdata/health.silencers.json
	# enabled = yes
	# default repeat warning = never
	# default repeat critical = never
	# in memory max health log entries = 1000
	# script to execute on alarm = /usr/libexec/netdata/plugins.d/alarm-notify.sh
	# stock health configuration directory = /usr/lib/netdata/conf.d/health.d
	# health configuration directory = /etc/netdata/health.d
	# rotate log every lines = 2000
	# run at least every seconds = 10
	# postpone alarms during hibernation for seconds = 60
###
```

In stream.conf for API key 

```cmd
health enabled by default = yes
```

**Comment by ilyam8** [comment]
Hi @mihailigoshin , thx for reporting, fixed in #10048

**Comment by mihailigoshin** [comment]
@ilyam8 , Thank you.

**Comment by mihailigoshin** [comment]
I've changed the to 
`  lookup: average -5m unaligned percentage of no_connection,failed
`
The restarted the netdata service but still do not receive an alarm nor notification.

**Comment by ilyam8** [comment]
Could you find that [`connection_fails`](https://github.com/netdata/netdata/blob/2b640642ee8392ee7f697c23de4d8976c7aaed12/health/health.d/portcheck.conf#L36-L46) alarm (Alarms=>All=>portcheck*) and show the screenshot?
