### ISSUE TITLE
exporting.conf seems not working 

### ISSUE THREAD

**Issue by mihailigoshin** [netdata/netdata#10165]
This is not working:

` /etc/netdata/edit-config exporting.conf
`
```

[graphite:my_graphite]
    enabled = yes
    destination = udp:influxdb.home:2003
    data source = average
    prefix = netdata
    hostname = lxc04
    #update every = 10
```

PS.  I've tried via tcp but for sure influxdb graphite is via udp

This is working:

`/etc/netdata/edit-config netdata.conf`

```
[backend]
        # host tags = 
         enabled = yes
        # data source = average
         type = graphite
         destination = udp:influxdb.home:2003
         prefix = netdata
         hostname = lxc04
```

Here is the exact configuration from influxdb.conf

```
[[graphite]]
  # Determines whether the graphite endpoint is enabled.
    enabled = true
    database = "graphite"
   #retention-policy = ""
    bind-address = ":2003"
    protocol = "udp"
   #consistency-level = "one"
```

Influxdb is on a remote machine 
BTW I've tried with opentsdb and got the same results

**Comment by ilyam8** [comment]
Hi @mihailigoshin, netdata version?

**Comment by mihailigoshin** [comment]
@ilyam8 Hi, 

netdata v1.26.0

**Comment by vlvkobal** [comment]
I've tried with
```
[graphite:instance_graphite_udp]
enabled = yes
destination = udp:localhost:2003
data source = average
update every = 2
prefix = netdata
hostname = lsc04
send charts matching = example.random
```
and
```
    enabled = true
    database = "graphite"
    bind-address = ":2003"
    protocol = "udp"

```
everything is working as expected 🤷‍♂️.

**Comment by vlvkobal** [comment]
Please check the Netdata part using `nc -l -p 2003`.

**Comment by vlvkobal** [comment]
Well, I'm closing this. I can't reproduce the issue and there were quite considerable changes to the exporting engine during the last days. @mihailigoshin if you still face the problem after updating Netdata and you are able to provide more information, feel free to reopen the issue.

**Comment by fayak** [comment]
I have the same issue. On archlinux, install netdata with `pacman` -> (`netdata v1.26.0`).

Go to `/etc/`, `./edit-config exporting.conf`, and set

```
[exporting:global]
    enabled = yes
    # send configured labels = yes
    # send automatic labels = no
    # update every = 10

[prometheus:exporter]
    # send names instead of ids = yes
    # send configured labels = yes
    send automatic labels = yes
    # send charts matching = *
    # send hosts matching = localhost *
    prefix = test

... (default)
```

`systemctl restart netdata` to apply changes, and nothing is applied.

```
$ curl -s '127.1:19999/api/v1/allmetrics?format=prometheus' | grep test | wc -l
0
```


```
$ cat /var/log/netdata/error.log | grep exporting
2020-11-23 10:43:08: netdata INFO  : EXPORTING : CONFIG: cannot load user exporting config '/etc/netdata/exporting.conf'. Will try the stock version.
2020-11-23 10:43:08: netdata INFO  : EXPORTING : EXPORTING: no exporting connectors configured
2020-11-23 10:43:47: netdata INFO  : EXPORTING : EXPORTING: no exporting connectors configured
```
(first is from stock install I guess, second is mine)

**Comment by fayak** [comment]
I'm actually trying to add a prometheus label to my metrics, and interested in the `send configured labels`, but even if I have the label in `http://127.0.0.1:19999/api/v1/info` (configured in `netdata.conf`), it is never exported in `api/v1/allmetrics?format=prometheus`

**Comment by ilyam8** [comment]
@fayak 👋 

@vlvkobal is on vacation this week, we will check the problem right after he is back

**Comment by thiagoftsm** [comment]
Hello @fayak ,

According to this message:

```
2020-11-23 10:43:08: netdata INFO  : EXPORTING : CONFIG: cannot load user exporting config '/etc/netdata/exporting.conf'. Will try the stock version.
```

You do not have the file `/etc/netdata/exporting.conf` and it is possible this is your problem, please, can you check if the file exists?

Best regards!

**Comment by fayak** [comment]
As mentionned, this log is for the first time netdata is ran when installing it with pacman. The file name is correct, and its content is the one I sent on my prev. message ;)

**Comment by fayak** [comment]
Hello !

Should I create a new issue ?

**Comment by vlvkobal** [comment]
I reinstalled Netdata using `pacman` and it reads the configuration file without any issues. Please show the output of `ls -l /etc/netdata/exporting.conf`.

The options aren't working indeed. I'll look at that tomorrow.

**Comment by fayak** [comment]
```
ls -l /etc/netdata/exporting.conf
-rw-r--r-- 1 root root 2562 Nov 23 10:46 /etc/netdata/exporting.conf
```

**Comment by vlvkobal** [comment]
The problem with the options was fixed in #10323.

**Comment by pickfire** [comment]
I still get the same issue `EXPORTING : CONFIG: cannot load user exporting config '/etc/netdata/exporting.conf'. Will try the stock version.` after upgrading to v1.28.0, even with just a simple one, it does not work.
```toml
[exporting:global]
  enabled = true
```
I am using kubernetes for deployment, the configuration is as follow for helm values:
```yaml
child:
  configs:
   exporting:
     enabled: true
     data: |
       [exporting:global]
         enabled = true
```
I was planning to use `prometheus_remote_write` as well but I am surprised even after I removed the block it still does not work.
```yaml
...
      [prometheus_remote_write:my_prometheus_remote_write_instance]
        enabled = yes
        destination = m3dbnode.default:7201
        remote write URL path = /api/v1/prom/remote/write
```

**Comment by thiagoftsm** [comment]
Hello @pickfire ,

The error that you are giving us means that either  Netdata could not find the file `/etc/netdata/exporting.conf` or it does not have permission to read the file, please, can you run the following command for we identify what is the problem:

```bash
$ ls -l /etc/netdata/exporting.conf
```

Best regards!

**Comment by pickfire** [comment]
Ah, I figured it out. I was looking at the wrong container, I looked at the parent instead of the child, I was confused about it for a bit.

**Comment by montyfudd** [comment]
nice!
-monty
