### ISSUE TITLE
/etc/cron.daily/netdata-updater fails

### ISSUE THREAD

**Issue by bmatheny** [netdata/netdata#10417]
Found https://community.netdata.cloud/t/periodically-anacron-job-cron-daily-on-localhost-reports-a-problem-with-netdata-updater-sh/612 but this workaround does not fix my issue.

##### Bug report summary
cron has been failing to run netdata-updater (`/etc/cron.daily/netdata-updater`) for a while now:

```
root@admin00:~# /etc/cron.daily/netdata-updater
Checking if a newer version of the updater script is available.
Downloading newest version of updater script.
/tmp/netdata-updater-6YqW7XDJWd/netdata-updater.sh: line 348: THIS_SHOULD_BE_REPLACED_BY_INSTALLER_SCRIPT: No such file or directory
```

I found the above thread and tried to `--reinstall` but that didn't fix the issue. After running `--reinstall` and it not fixing the issue, I ran the uninstaller, deleted any netdata related files, and did a full reinstall via: `bash <(curl -Ss https://my-netdata.io/kickstart.sh) --stable-channel`

After doing that, I still get the same error when I run `netdata-updater` via cron (or via the CLI using `/etc/cron.daily/netdata-updater`).

It looks to me like the kickstart (or some other) installer does some sed magic on netdata-updater when dropping it in to `/etc/cron.daily/`, but that same magic isn't applied by `netdata-updater` when attempting to self update.

Possible fixes:

1. Set default for netdata-updater in cron to not self-update (`--no-updater-self-update` works)
2. Apply same logic from kickstart installer for `/etc/cron.daily/netdata-updater` on `/tmp/netdata-updater-XXXXXXXXXX/netdata-updater.sh` when `/etc/cron.daily/netdata-updater` attempts to self update.

##### OS / Environment

```
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=20.04
/etc/lsb-release:DISTRIB_CODENAME=focal
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="20.04.1 LTS (Focal Fossa)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 20.04.1 LTS"
/etc/os-release:VERSION_ID="20.04"
```

##### Netdata version

netdata v1.28.0

##### Steps To Reproduce

1. Fresh install of netdata, e.g. `bash <(curl -Ss https://my-netdata.io/kickstart.sh) --stable-channel`
2. Try to run `/etc/cron.daily/netdata-updater` by hand
3. See error e.g. `/tmp/netdata-updater-2YQZ1VCnpz/netdata-updater.sh: line 348: THIS_SHOULD_BE_REPLACED_BY_INSTALLER_SCRIPT: No such file or directory`

##### Expected behavior

netdata-updater should not error out when run via CLI or cron.

**Comment by mapl** [comment]
Have exactly the same issue on Ubuntu 20.04.1 LTS (Focal Fossa), however on "Debian GNU/Linux 10 (buster)", it works.

**Comment by Dlizzz** [comment]
+1

**Comment by douglasparker** [comment]
It seems like the automatic updater is always broken. :/

**Comment by Ma3xl3** [comment]
Same problem.
Netdata v1.26.0 worked well. On v1.27.0 and v1.28.0 the error occurs.

**Comment by Lamera** [comment]
Same issue on alpine linux.
I fixed the issue with this added lines: https://github.com/skibbipl/netdata/commit/18c4f99282695f7318bbb6bf6c5eff2b685d4e39

**Comment by douglasparker** [comment]
> Same issue on alpine linux.
> I fixed the issue with this added lines: [skibbipl@18c4f99](https://github.com/skibbipl/netdata/commit/18c4f99282695f7318bbb6bf6c5eff2b685d4e39)

I can confirm that this fix also works for Ubuntu 20.04.

**Comment by mapl** [comment]
As the command "python" was not found. I used the described way to create a symbolic link of python to python3

https://stackoverflow.com/a/50331137

```
sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 10
```
This gives a priority of 10 for the path of python3.

**Comment by jobenvil** [comment]
Meanwhile I have done: 

1. `bash <(curl -Ss https://my-netdata.io/kickstart.sh) --reinstalll` -> NOK
2. `./netdata-uninstaller.sh --yes  && bash <(curl -Ss https://my-netdata.io/kickstart.sh)` --> NOK
3. `sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 10`  -- > **OK**

@mapl I think that's a good non intrusive WA. Thanks!
```
jobenvil@arkanoid:~$ sudo bash /etc/cron.daily/netdata-updater
Checking if a newer version of the updater script is available.
Downloading newest version of updater script.
/tmp/netdata-updater-bl6Oc4qWWE/netdata-updater.sh: línea 348: THIS_SHOULD_BE_REPLACED_BY_INSTALLER_SCRIPT: No existe el archivo o el directorio
jobenvil@arkanoid:~$ sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 10
update-alternatives: utilizando /usr/bin/python3 para proveer /usr/bin/python (python) en modo automático
jobenvil@arkanoid:~$ sudo bash /etc/cron.daily/netdata-updater
Checking if a newer version of the updater script is available.
jue 31 dic 2020 13:21:28 CET : INFO:  Running on a terminal - (this script also supports running headless from crontab)
jue 31 dic 2020 13:21:28 CET : INFO:  Current Version: 00102800000051
jue 31 dic 2020 13:21:28 CET : INFO:  Latest Version: 00102800000051
jue 31 dic 2020 13:21:28 CET : INFO:  Newest version (current=00102800000051 >= latest=00102800000051) is already installed

```

**Comment by Ferroin** [comment]
Should be fixed in master now.

**Comment by cepn-itadmin** [comment]
Still not fix as each time a new version of the netdata-updater.sh is downloaded this error is fired.

To test it : modify the date of the /usr/libexec/netdata/netdata-updater.sh :
```
touch "20 days ago" /usr/libexec/netdata/netdata-updater.sh
```

Then run again the cron.daily/netdata_updater and voilà:
```
Checking if a newer version of the updater script is available.
Downloading newest version of updater script.
/tmp/netdata-updater-d7wlaTrZIH/netdata-updater.sh: ligne 354: THIS_SHOULD_BE_REPLACED_BY_INSTALLER_SCRIPT: Aucun fichier ou dossier de ce type
```

**Comment by skibbipl** [comment]
Yes, I can confirm that issue on my raspberries. Even when I symlinked python to python3.

**Comment by Ferroin** [comment]
That’s an unrelated bug that will be fixed when #10447 gets merged.
