### ISSUE TITLE
Teams notification netdata button points to app.netdata.cloud for a standalone agent

### ISSUE THREAD

**Issue by Romanow88** [netdata/netdata#10696]
##### Bug report summary
Using a standalone netdata agent
When setting up netdata alarm notifications to MSTeams the notification itself contains a button pointing to "app.netdata.cloud" instead of the actual netdata node which produced the alert.
##### OS / Environment
```
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=20.04
/etc/lsb-release:DISTRIB_CODENAME=focal
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="20.04.2 LTS (Focal Fossa)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 20.04.2 LTS"
/etc/os-release:VERSION_ID="20.04"
/etc/os-release:HOME_URL="https://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="https://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
/etc/os-release:PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
/etc/os-release:VERSION_CODENAME=focal
/etc/os-release:UBUNTU_CODENAME=focal
```

##### Netdata version
netdata v1.29.3

##### Component Name
No clue.

##### Steps To Reproduce

1. Setup a single node Netdata instalation not connected to netdata cloud.
2. set up a MSTeams webhook 
3. trigger an alert

##### Expected behavior
The "Netdata" button in teams should point to the netdata instance if it's not connected to a registry or to netdata cloud.

**Comment by thiagoftsm** [comment]
@manos-saratsis this is an old issue that we have, but we need to bring a fix for this, do we already have a plan to bring it?

**Comment by thiagoftsm** [comment]
I remove the label `need triage`, because this is a well known problem, we need to update `alarm-notify.sh` link and the cloud needs to redirect back.

**Comment by MrZammler** [comment]
Hi. This should be okay by now. Even if the link points to `app.netdata.cloud` there will be a redirect back to local agent's dashboard. Redirecting also to a child dashboard should be fixed when #12609 is merged.

**Comment by Raptus1** [comment]
Redirect still not working as expected.

The simplest way would for this to link to the host directly, no?

We have parent that sends out these notifications and it would make sense to have the link point to that parent and not a internet-based redirecting instance.

![image](https://github.com/netdata/netdata/assets/26519394/f4e0b3d2-ed97-4589-84c2-277ab674fc49)
