### ISSUE TITLE
alert still fired for the resolved last collected

### ISSUE THREAD

**Issue by yasharne** [netdata/netdata#10989]
##### Bug report summary
the child (`1.29.1`) is streaming to the parent (`1.29.1`), I see an alert which is claiming the MySQL last collected is more than 60 days (the number in front of the last collected is not updating):
![image](https://user-images.githubusercontent.com/7656049/115140991-5393fc80-a04f-11eb-933b-367f6b5d3f62.png)
But on the chart, I see it is collecting data without any problem:
![image](https://user-images.githubusercontent.com/7656049/115183744-af16c680-a0f1-11eb-9b02-40be664a68ea.png)

##### OS / Environment

```
Linux netdata-01 4.15.0-142-generic #146-Ubuntu SMP Tue Apr 13 01:11:19 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=18.04
/etc/lsb-release:DISTRIB_CODENAME=bionic
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="18.04.5 LTS (Bionic Beaver)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 18.04.5 LTS"
/etc/os-release:VERSION_ID="18.04"
/etc/os-release:HOME_URL="https://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="https://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
/etc/os-release:PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
/etc/os-release:VERSION_CODENAME=bionic
/etc/os-release:UBUNTU_CODENAME=bionic
```

##### Netdata version

parent and child are running `v1.29.1`

##### Installation method

Prebuild

##### Component Name

Alerting

**Comment by yasharne** [comment]
This problem still exists

**Comment by yasharne** [comment]
`/api/v1/alarms?all=false&active=true` on the parent shows there are no alerts firing, so this seems to be a visual problem
```
{
	"hostname": "netdata-02",
	"latest_alarm_log_unique_id": 1612952529,
	"status": true,
	"now": 1619978037,
	"alarms": {

	}
}
```

**Comment by ilyam8** [comment]
@yasharne did you add `/host/HOSTNAME/`?

> http://PARENT_IP/host/CHILD_HOSTNAME/api/v1/alarms?all&active

**Comment by yasharne** [comment]
Hi @ilyam8 adding `/host/HOSTNAME/` shows the alert:
```
	"alarms": {
		"mysql_local.queries.mysql_last_collected_secs": {
			"id": 1613502978,
			"name": "mysql_last_collected_secs",
			"chart": "mysql_local.queries",
			"family": "queries",
			"active": true,
			"disabled": false,
			"silenced": false,
			"exec": "/opt/netdata/usr/libexec/netdata/plugins.d/alarm-notify.sh",
			"recipient": "dba",
			"source": "4@/opt/netdata/etc/netdata/health.d/mysql.conf",
			"units": "seconds ago",
			"info": "number of seconds since the last successful data collection",
			"status": "CRITICAL",
			"last_status_change": 1613558486,
			"last_updated": 1618736574,
			"next_update": 1618736584,
			"update_every": 10,
			"delay_up_duration": 0,
			"delay_down_duration": 300,
			"delay_max_duration": 3600,
			"delay_multiplier": 1.500000,
			"delay": 0,
			"delay_up_to_timestamp": 1613558486,
			"warn_repeat_every": "0",
			"crit_repeat_every": "0",
			"value_string": "60 days 12:32:38 ago",
			"last_repeat": "0",
			"calc":"$now - $last_collected_t",
			"calc_parsed":"(${now} - ${last_collected_t})",
			"crit":"$this &gt; (($status == $CRITICAL) ? ($update_every) : (60 * $update_every))",
			"crit_parsed":"(${this} &gt; ((${status} == ${CRITICAL}) ? ${update_every} : (60 * ${update_every})))",
			"green":null,
			"red":null,
			"value":5229158
		}
	}
```
And of course, the plugin is collecting data:
![image](https://user-images.githubusercontent.com/7656049/117105199-c82aa300-ad92-11eb-94ff-8d469160020a.png)

**Comment by ilyam8** [comment]
@yasharne it is hard to track the cause. Have you tried `netdatacli reload-health`? I believe it should fix the current issue. Likely it will happen again after some time, but let's see.

**Comment by yasharne** [comment]
@ilyam8 I tried `netdatacli reload-health` on the parent but it didn't fix the issue

**Comment by thiagoftsm** [comment]
Hello @yasharne ,

Is this alarm raised for data from a child or a parent node?  I ma trying to figure out why our database is not giving correct data for our health. :thinking: . 
Another doubt, I assumed you are using dbengine on parent, please, can you confirm this. 

Best Regards,

**Comment by yasharne** [comment]
Hi @thiagoftsm child node (which is running MySQL) is streaming to the parent and the alert is raised from the parent as we do not store any metrics on the child
And yes, we are using dbengine the parent

**Comment by thiagoftsm** [comment]
> Hi @thiagoftsm child node (which is running MySQL) is streaming to the parent and the alert is raised from the parent as we do not store any metrics on the child
> And yes, we are using dbengine the parent

This explains what is happening, I remember I ran tests months ago and during the tests the parent was not raising all expected alarms for children. We are working to improve our stream (ping @stelfrag ) and I hope this will be fixed soon.

**Comment by ilyam8** [comment]
> he child (1.29.1) is streaming to the parent (1.29.1)

@yasharne are you still having this issue with v1.31.0?

**Comment by stelfrag** [comment]
Closing due to no feedback, please report again if applicable

**Comment by yasharne** [comment]
Hi @ilyam8 @stelfrag 
yes, today I encountered this issue again on 1.33.0:
![image](https://user-images.githubusercontent.com/7656049/155163077-4234a7a7-e159-4eeb-957f-4b4aa6fea500.png)
While it is the chart collecting data:
![image](https://user-images.githubusercontent.com/7656049/155163303-d995536b-a8cd-4bc8-95a5-b84b15a1f90b.png)
When I click on this icon:
![image](https://user-images.githubusercontent.com/7656049/155163407-90d6c10b-0d6b-4812-bf8a-855d45edbc2b.png)
It takes me to the time where the chart has no data (take a look at the time range): 
![image](https://user-images.githubusercontent.com/7656049/155163585-c0cf4c96-eeb4-482a-a8c6-b48d8b7ef5c3.png)

**Comment by MrZammler** [comment]
Hi @yasharne , thanks for the follow up. What is the setting on the parent's `stream.conf` for `health enabled by default` ?

**Comment by yasharne** [comment]
Hi @MrZammler this is my configuration:
```
health enabled by default = auto
```

**Comment by MrZammler** [comment]
Hi @yasharne , thanks!

Have you noticed if the child crashes (or in any way disconnects/loses connection from the parent without informing the parent it's closing the connection), especially when the alert is raised ?

There might be something to indicate this in the child's `error.log`...

**Comment by yasharne** [comment]
Hi @MrZammler 
No, as I checked, the netdata agent was fine during the problem

**Comment by MrZammler** [comment]
Hi @yasharne 

There have been some recent changes regarding children and alerts. Any chance you have updated to a latest nightly? If you are on stable releases, then let's revisit this after the next stable release.

Thanks!

**Comment by cpipilas** [comment]
Fixed in the latest releases.
