### ISSUE TITLE
[Bug]: BSD available memory showing strange overly big values

### ISSUE THREAD

**Issue by hugovalente-pm** [netdata/netdata#13172]
### Bug description

With the fix on https://github.com/netdata/netdata/pull/13140 the `mem.available` chart is now available for BSD hosts, but the values presented are strange and not representative of actual memory

![image](https://user-images.githubusercontent.com/73555475/174154666-0022f719-205b-4953-a0c4-c44e9913ead0.png)

Issue reported here https://github.com/netdata/netdata-cloud/issues/352#issuecomment-1158081672

### Expected behavior

Values to be consistent with top, for example:

```
[root@staging ~]# top
last pid: 92652;  load averages:  0.38,  1.31,  1.15                                                                                                             up 2+00:55:10  16:01:52
89 processes:  1 running, 87 sleeping, 1 zombie
CPU:  0.1% user,  0.0% nice,  0.1% system,  0.1% interrupt, 99.7% idle
Mem: 433M Active, 1706M Inact, 12G Wired, 104K Buf, 111G Free
ARC: 7822M Total, 4460M MFU, 1400M MRU, 160K Anon, 83M Header, 1863M Other
     5037M Compressed, 12G Uncompressed, 2.37:1 Ratio
Swap: 4096M Total, 4096M Free
```

### Steps to reproduce

1. Fire-up a host with BSD
2. Check the `mem.available` chart reporting in the TiB measurement

### Installation method

kickstart.sh

### System info

```shell
TBA
```

### Netdata build info

```shell
TBA
```

**Comment by hugovalente-pm** [comment]
@MikeJakubik pinging you also here

**Comment by MrZammler** [comment]
The description is also wrong ....

@MikeJakibik, can you post please your system info ?

**Comment by MikeJakubik** [comment]
Hi,

I im running 13.1 stable, this should all be the same all the way back to 11 (or older).

`FreeBSD staging.swift-api.com 13.1-STABLE FreeBSD 13.1-STABLE #0 stable/13-be3f66738: Tue Jun 14 14:45:31 EDT 2022     root@staging.swift-api.com:/usr/obj/usr/src/amd64.amd64/sys/GENERIC amd64`

The following links will help understand and calculate FreeBSD memory.

https://wiki.freebsd.org/Memory
https://www.cyberciti.biz/faq/freebsd-command-to-get-ram-information/

For example, the following sysctls can be used.

```
    #   determine the individual known information
    #   NOTICE: forget hw.usermem, it is just (hw.physmem - vm.stats.vm.v_wire_count).
    #   NOTICE: forget vm.stats.misc.zero_page_count, it is just the subset of
    #           vm.stats.vm.v_free_count which is already pre-zeroed.
    mem_phys=`sysctl -n hw.physmem`
    set +e
    mem_hw=`mem_rounded $mem_phys`
    set -e
    sysctl_pagesize=`sysctl -n hw.pagesize`
    mem_all=`echo "\`sysctl -n vm.stats.vm.v_page_count\` * $sysctl_pagesize" | bc`
    mem_wire=`echo "\`sysctl -n vm.stats.vm.v_wire_count\` * $sysctl_pagesize" | bc`
    mem_active=`echo "\`sysctl -n vm.stats.vm.v_active_count\` * $sysctl_pagesize" | bc`
    mem_inactive=`echo "\`sysctl -n vm.stats.vm.v_inactive_count\` * $sysctl_pagesize" | bc`
    mem_cache=`echo "\`sysctl -n vm.stats.vm.v_cache_count\` * $sysctl_pagesize" | bc`
    mem_free=`echo "\`sysctl -n vm.stats.vm.v_free_count\` * $sysctl_pagesize" | bc`

    #   determine the individual unknown information
    mem_gap_sys=`echo "$mem_phys - $mem_all" | bc`
    mem_gap_hw=`echo "$mem_hw - $mem_phys" | bc`

    #   determine logical summary information
    mem_total=$mem_hw
    mem_avail=`echo "$mem_inactive + $mem_cache + $mem_free" | bc`
    mem_used=`echo "$mem_total - $mem_avail" | bc
```

Thanks.

**Comment by MrZammler** [comment]
> `` mem_avail=`echo "$mem_inactive + $mem_cache + $mem_free" | bc` ``

Hi @MikeJakubik thanks for this, indeed that is what is (at least tries to) do there for the available ram. Will check and get back to you. Thanks!

**Comment by MrZammler** [comment]
Can you also post please a screenshot of `System overview` -> `ram` ?

**Comment by MikeJakubik** [comment]
![Screenshot 2022-06-17 084605](https://user-images.githubusercontent.com/73555475/174301019-fd5e72c8-1e9c-4277-991c-2a3abca3ecd9.png)

**Comment by MikeJakubik** [comment]
While we're on this topic, I just noticed that wired here shows incorrectly as well. It's in the negatives.

According to top:

Mem: 709M Active, 10G Inact, 19G Wired, 104K Buf, 94G Free

According to Netdata:
Wired = -6.3 GiB

**Comment by MrZammler** [comment]
@MikeJakubik Hi!

Can you also please post what `htop` reports (especially on the wired) ?

**Comment by blastehh** [comment]
Hi,
Just updated the netdata plugin on Truenas and noticed that the wired ram is incorrect as well.
You can see the point at which the plugin was updated:
![image](https://user-images.githubusercontent.com/8324677/174637906-f80f8ce7-4a4c-4a34-94ef-1b9d0fc2f1dc.png)
![image](https://user-images.githubusercontent.com/8324677/174637919-9ca90c0f-5d71-42e0-b914-fd234f052c0b.png)

**Comment by MikeJakubik** [comment]
> @MikeJakubik Hi!
> 
> Can you also please post what `htop` reports (especially on the wired) ?

I don't trust htop or most Linux htop like programs to properly report memory usage on FreeBSD.

**Comment by blastehh** [comment]
Also taking a look at /api/v1/allmetrics?format=prometheus_all_hosts&source=as-collected
seems the metrics are outputting 2 separate values??
![image](https://user-images.githubusercontent.com/8324677/174640094-3558a039-116e-4d3b-8263-82a823a0f14f.png)

**Comment by ilyam8** [comment]
@blastehh @MikeJakubik can you show

```cmd
sysctl vm.stats.vm.v_wire_count
pagesize
sysctl kstat.zfs.misc.arcstats.size
sysctl kstat.zfs.misc.arcstats.c_min
```

**Comment by MikeJakubik** [comment]
> ```batchfile
> sysctl kstat.zfs.misc.arcstats.c_min
> ```

[root@staging ~]# sysctl vm.stats.vm.v_wire_count
vm.stats.vm.v_wire_count: 3255308
[root@staging ~]# pagesize
4096
[root@staging ~]# sysctl kstat.zfs.misc.arcstats.size
kstat.zfs.misc.arcstats.size: 8759291232
[root@staging ~]# sysctl kstat.zfs.misc.arcstats.c_min
kstat.zfs.misc.arcstats.c_min: 4286929920

**Comment by blastehh** [comment]
```
root@storage:~ # sysctl vm.stats.vm.v_wire_count
vm.stats.vm.v_wire_count: 7506491
root@storage:~ # pagesize
4096
root@storage:~ # sysctl kstat.zfs.misc.arcstats.size
kstat.zfs.misc.arcstats.size: 27353964064
root@storage:~ # sysctl kstat.zfs.misc.arcstats.c_min
kstat.zfs.misc.arcstats.c_min: 1069892096

```

**Comment by ilyam8** [comment]
Negative wired fixed in #13183

**Comment by MikeJakubik** [comment]
Still shows negative here.

![Screenshot 2022-06-20 145144](https://user-images.githubusercontent.com/73555475/174662945-30fafb5f-78eb-4a3f-a36a-f5c4893c0111.png)

**Comment by MikeJakubik** [comment]
Also, mem.available is messed up, 18TiB of RAM???

![Screenshot 2022-06-20 145316](https://user-images.githubusercontent.com/73555475/174663304-2933f2a5-f0bc-40c5-92f1-bd9b673a9464.png)

**Comment by ilyam8** [comment]
@MikeJakubik the PR hasn't been merged yet. Both negative wired and wrong mem avail will be fixed when it is merged.

**Comment by MikeJakubik** [comment]
mem.available appears to display correctly now, however, while we're on the subject, the mem.commited metric displays an odd value of "Commited_AS".

![Screenshot 2022-06-22 122247](https://user-images.githubusercontent.com/73555475/175085198-caad6bb0-3842-4047-b3b4-8be29b959b7d.png)

**Comment by ilyam8** [comment]
I guess the idea was to have the same dimensions name as on Linux:

from man procfs

> Committed_AS %lu
> The amount of memory presently allocated on the system. The committed memory is a sum of all of the memory which has been allocated by processes, even if it has  not  been  "used"  by them  as of yet.

This is FreeBSD `mem.committed` chart

https://github.com/netdata/netdata/blob/a878ed36431db17bebb53004200e41bb91e9248f/collectors/freebsd.plugin/freebsd_sysctl.c#L278-L292

We use `vmtotal.t_rm`, which [total real memory in use](http://fxr.watson.org/fxr/source/sys/vmmeter.h?v=FREEBSD-11-STABLE#L213).

```cmd
[cm@zammler-freebsd-vm1 ~]$ sysctl vm.vmtotal | grep ^Real
Real Memory:		(Total: 157660K Active: 156024K)
```

---

I am not sure if it matches Committed_AS on Linux. @vlvkobal?
