### ISSUE TITLE
[Bug]: cant install netdata on centos 7

### ISSUE THREAD

**Issue by iulianhlc** [netdata/netdata#15164]
### Bug description

I had it installed on Centos 7 and stop working!
I try to reinstall it and didn't work!
I try to install it on another server with centos 7 and didn't work either!

### Expected behavior

systemctl status netdata.service
● netdata.service - Real time performance monitoring
   Loaded: loaded (/usr/lib/systemd/system/netdata.service; disabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Thu 2023-06-08 12:35:23 EEST; 28s ago
  Process: 20808 ExecStart=/usr/sbin/netdata -P /run/netdata/netdata.pid -D (code=exited, status=1/FAILURE)
  Process: 20805 ExecStartPre=/bin/chown -R netdata /run/netdata (code=exited, status=0/SUCCESS)
  Process: 20801 ExecStartPre=/bin/mkdir -p /run/netdata (code=exited, status=0/SUCCESS)
  Process: 20798 ExecStartPre=/bin/chown -R netdata /var/cache/netdata (code=exited, status=0/SUCCESS)
  Process: 20794 ExecStartPre=/bin/mkdir -p /var/cache/netdata (code=exited, status=0/SUCCESS)
 Main PID: 20808 (code=exited, status=1/FAILURE)

Jun 08 12:35:23 korriban.web-admin.ro systemd[1]: Unit netdata.service entered failed state.
Jun 08 12:35:23 korriban.web-admin.ro systemd[1]: netdata.service failed.

### Steps to reproduce

cd /usr/local/directadmin/custombuild
./build netdata

wget -O /tmp/netdata-kickstart.sh https://my-netdata.io/kickstart.sh && sh /tmp/netdata-kickstart.sh --stable-channel --claim-token xxxxxxxxxxxxxxxxxxxxxxxxxxx  --claim-url https://app.netdata.cloud

### Installation method

kickstart.sh

### System info

```shell
3.10.0-1160.42.2.el7.x86_64 #1 SMP Tue Sep 7 14:49:57 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
/etc/centos-release:CentOS Linux release 7.9.2009 (Core)
/etc/os-release:NAME="CentOS Linux"
/etc/os-release:VERSION="7 (Core)"
/etc/os-release:ID="centos"
/etc/os-release:ID_LIKE="rhel fedora"
/etc/os-release:VERSION_ID="7"
/etc/os-release:PRETTY_NAME="CentOS Linux 7 (Core)"
/etc/os-release:ANSI_COLOR="0;31"
/etc/os-release:CPE_NAME="cpe:/o:centos:centos:7"
/etc/os-release:
/etc/os-release:CENTOS_MANTISBT_PROJECT="CentOS-7"
/etc/os-release:CENTOS_MANTISBT_PROJECT_VERSION="7"
/etc/os-release:REDHAT_SUPPORT_PRODUCT="centos"
/etc/os-release:REDHAT_SUPPORT_PRODUCT_VERSION="7"
/etc/os-release:
/etc/redhat-release:CentOS Linux release 7.9.2009 (Core)
/etc/system-release:CentOS Linux release 7.9.2009 (Core)
```

### Netdata build info

```shell
netdata -W buildinfo
Version: netdata v1.39.1
Configure options:  '--build=x86_64-redhat-linux-gnu' '--host=x86_64-redhat-linux-gnu' '--program-prefix=' '--disable-dependency-tracking' '--prefix=/usr' '--exec-prefix=/usr' '--bindir=/usr/bin' '--sbindir=/usr/sbin' '--sysconfdir=/etc' '--datadir=/usr/share' '--includedir=/usr/include' '--libdir=/usr/lib64' '--libexecdir=/usr/libexec' '--localstatedir=/var' '--sharedstatedir=/var/lib' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--enable-plugin-freeipmi' '--with-bundled-protobuf' '--with-zlib' '--with-math' '--with-user=netdata' 'build_alias=x86_64-redhat-linux-gnu' 'host_alias=x86_64-redhat-linux-gnu' 'CFLAGS=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1  -m64 -mtune=generic' 'LDFLAGS=-Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld' 'CXXFLAGS=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1  -m64 -mtune=generic' 'PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig'
Install type: custom
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES
    ACLK:                       YES
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         NO
Libraries:
    protobuf:                YES (bundled)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  YES
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    NO
    IPMI:                    YES
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
Debug/Developer Features:
    Trace Allocations:       NO
```

**Comment by duy13** [comment]
https://github.com/netdata/netdata/issues/15158


Same here, the error is still unresolved

**Comment by tkatsoulas** [comment]
Hello @iulianhlc 

I need one clarification, in the steps to reproduce you do the following;

```
cd /usr/local/directadmin/custombuild
./build netdata
```

and then 

```
wget -O /tmp/netdata-kickstart.sh https://my-netdata.io/kickstart.sh && sh /tmp/netdata-kickstart.sh --stable-channel --claim-token xxxxxxxxxxxxxxxxxxxxxxxxxxx --claim-url https://app.netdata.cloud/
```

May I ask why? you only needed the kickstart

**Comment by iulianhlc** [comment]
Hello @tkatsoulas 

I try both ways.

And is not working anymore!

**Comment by nathnial** [comment]
> Makefile:6120: httpd/h2o/deps/cloexec/.deps/libh2o_a-cloexec.Po: No such file or directory

uphere is my centos7 error, after execute netdata-installer.sh with root. And what most important is that I can't find a httpd/h2o/deps/cloexec/.deps dir.

**Comment by Dim-P** [comment]
> > Makefile:6120: httpd/h2o/deps/cloexec/.deps/libh2o_a-cloexec.Po: No such file or directory
> 
> uphere is my centos7 error, after execute netdata-installer.sh with root. And what most important is that I can't find a httpd/h2o/deps/cloexec/.deps dir.

@nathnial This looks like it is a similar case to https://github.com/netdata/netdata/issues/15248 and should be fixed by https://github.com/netdata/netdata/pull/15253 . Is it possible to test again and confirm if it is indeed fixed now?

@iulianhlc and @duy13 , are you facing a similar issue or it is a different error you've come across?

**Comment by duy13** [comment]
currently, at version v1.40 it is still not usable on centos 7, node on netdata cloud is always in unseen mode cannot collect data

**Comment by MrZammler** [comment]
@duy13 

Could you please share your error.log to manolis@netdata.cloud? Thanks.
