### ISSUE TITLE
[Bug]: Parent Dashboard shows Child metrics but prometheus can't scrape them all

### ISSUE THREAD

**Issue by marcelmfs** [netdata/netdata#15272]
### Bug description

I've been struggling for weeks now to have all my streamed metrics in any seemingly working state. I have updated all agents to the same versions, nightlies, stables, without SSL, with SSL, there's always something preventing Prometheus from getting a complete view on all metrics of *some* children. I have tried all variations of memory mode, web SSL, and such.

I have a dozen or so servers running netdata. It was brilliant in the past, zero config, really easy. 

Nowadays, THE STRUGGLE. 

I don't know what happened but from nowhere my grafana plots started to display a lot of GAPS, and prometheus was timing out with `Context Deadline Exceeded` while fetching `/api/v1/allmetrics?format=prometheus_all_hosts`.

Starting from there I saw a report on the community forum of a Windows netdata agent having the same issue, single threaded web server CPU 100% yadda-yadda, ok. The solution? Update to latest. I did that. But it didn't work out. Then I started updating all agents to latest, nope. 

I even went and isolated all production netdata agents with a specific API key and disabled the non-essential ones (there were around 50 agents, around a dozen or so are production instances). Maybe the handling of some of those API NOT ENABLED messages were messing up with the RCVR threads? Who knows? I routed traffic from their source IPs to dev null. 

I'm still not able to see all metrics from `/api/v1/allmetrics?format=prometheus_all_hosts`, I have some of those production servers behind Nginx acting as TCP forwarding proxy transparently streaming traffic to the Parent Netdata's server where another Nginx's acting as a Transparent TCP Streaming Reverse proxy. I have also tried everything in there, enabling/disabling Keepalive, adding cache to the HTTP proxy pass endpoint serving `/api/v1`, by now I have depleted all tricks from my toolbelt, and still nothing worked. 

Then I downgraded all agents to 1.36.1, also no luck. WTH!? It used to work on v1.36.1! 

Something's following also during downgrades? I thought it was some patch management at the OS-level (CentOS7 almost EOL I know I know). But nothing changed.

Some weird access.log entry that is bugging me loads:
```
1736: 7541 '[localhost]:42128' 'DATA' (sent/all = 126/122 bytes -15120282027630780416%, prep/sent/total = 0.07/0.06/0.13 ms) 200 '/host/Children1-prod//api/v1/alarms?active'
```

Am I understanding this correctly? 126 out of 122 bytes sent? And that's 15120282027630780416% of what? 0,000000000000001 fentobits? 

And some entries from error.log from the same Child host:
```
/var/log/netdata/error.log:2023-06-28 13:51:46: netdata INFO  : MAIN : Host 'Children1-prod' (at registry as 'Children1-prod') with guid '7728c592-15b7-11ee-aa08-005056bbfda6' initialized, os 'linux', timezone 'Europe/Paris', tags '', program_name 'netdata', program_version 'v1.40.1', update every 5, memory mode dbengine, history entries 0, streaming disabled (to '' with api key ''), health disabled, cache_dir '/var/cache/netdata', alarms default handler '', alarms default recipient ''
/var/log/netdata/error.log:2023-06-28 13:51:46: netdata INFO  : MAIN : Host 'Children1-prod' (at registry as 'Children1-prod') with guid '8dd68b8c-15ba-11ee-bc6e-005056bbfda6' initialized, os 'linux', timezone 'Europe/Paris', tags '', program_name 'netdata', program_version 'v1.40.1', update every 5, memory mode dbengine, history entries 0, streaming disabled (to '' with api key ''), health disabled, cache_dir '/var/cache/netdata', alarms default handler '', alarms default recipient ''
/var/log/netdata/error.log:2023-06-28 13:52:03: netdata INFO  : RCVR[Children1-pr : STREAM Children1-prod [localhost]:42524: receive thread created (task id 4216)
/var/log/netdata/error.log:2023-06-28 13:52:03: netdata INFO  : RCVR[Children1-pr : Host 'Children1-prod' (at registry as 'Children1-prod') with guid 'd15ebc3a-15ba-11ee-864c-005056bbfda6' initialized, os 'linux', timezone 'Europe/Paris', tags '', program_name 'netdata', program_version 'v1.40.1', update every 5, memory mode dbengine, history entries 0, streaming disabled (to '' with api key ''), health disabled, cache_dir '/var/cache/netdata', alarms default handler '', alarms default recipient ''
/var/log/netdata/error.log:2023-06-28 13:52:03: netdata INFO  : RCVR[Children1-pr : STREAM Children1-prod [receive from [localhost]:42524]: established link with negotiated capabilities: VCAPS HLABELS CLAIM CLABELS FUNCTIONS REPLICATION BINARY INTERPOLATED IEEE754
/var/log/netdata/error.log:2023-06-28 13:52:03: netdata INFO  : RCVR[Children1-pr : STREAM 'Children1-prod' [receive from [localhost]:42524]: ready to receive data. STATUS: CONNECTED
/var/log/netdata/error.log:2023-06-28 13:52:24: netdata INFO  : RCVR[Children1-pr : STREAM 'Children1-prod' [receive from [localhost]:42524]: receive thread ended (task id 4216)
/var/log/netdata/error.log:2023-06-28 13:52:29: netdata INFO  : MAIN : RRD: 'host:Children1-prod' cleaning up disk files...
/var/log/netdata/error.log:2023-06-28 13:52:29: netdata INFO  : MAIN : RRD: 'host:Children1-prod' cleaning up disk files...
/var/log/netdata/error.log:2023-06-28 13:52:29: netdata INFO  : MAIN : RRD: 'host:Children1-prod' cleaning up disk files...
/var/log/netdata/error.log:2023-06-28 13:52:39: netdata INFO  : MAIN : RRD: 'host:Children1-prod' stopping data collection...
/var/log/netdata/error.log:2023-06-28 13:52:39: netdata INFO  : MAIN : RRD: 'host:Children1-prod' stopping data collection...
/var/log/netdata/error.log:2023-06-28 13:52:39: netdata INFO  : MAIN : RRD: 'host:Children1-prod' stopping data collection...
/var/log/netdata/error.log:2023-06-28 13:53:56: netdata INFO  : RCVR[Children1-pr : STREAM Children1-prod [localhost]:46048: receive thread created (task id 4778)
/var/log/netdata/error.log:2023-06-28 13:53:56: netdata INFO  : RCVR[Children1-pr : Host 'Children1-prod' (at registry as 'Children1-prod') with guid 'd15ebc3a-15ba-11ee-864c-005056bbfda6' initialized, os 'linux', timezone 'Europe/Paris', tags '', program_name 'netdata', program_version 'v1.40.1', update every 5, memory mode dbengine, history entries 0, streaming disabled (to '' with api key ''), health disabled, cache_dir '/var/cache/netdata', alarms default handler '', alarms default recipient ''
/var/log/netdata/error.log:2023-06-28 13:53:56: netdata INFO  : RCVR[Children1-pr : STREAM Children1-prod [receive from [localhost]:46048]: established link with negotiated capabilities: VCAPS HLABELS CLAIM CLABELS FUNCTIONS REPLICATION BINARY INTERPOLATED IEEE754
/var/log/netdata/error.log:2023-06-28 13:53:56: netdata INFO  : RCVR[Children1-pr : STREAM 'Children1-prod' [receive from [localhost]:46048]: ready to receive data. STATUS: CONNECTED
/var/log/netdata/error.log:2023-06-28 14:01:07: netdata ERROR : RCVR[Children1-pr : PLUGINSD: 'host:Children1-prod/chart:netdata.workers_busy_time_by_type_libuv/' stale data collection lock found during THREAD CLEANUP; it has been unlocked
/var/log/netdata/error.log:2023-06-28 14:01:07: netdata ERROR : RCVR[Children1-pr : PLUGINSD: 'host:Children1-prod/chart:netdata.workers_busy_time_by_type_libuv/' stale ML lock found during THREAD CLEANUP, it has been unlocked
/var/log/netdata/error.log:2023-06-28 14:01:07: netdata INFO  : RCVR[Children1-pr : STREAM 'Children1-prod' [receive from [localhost]:46048]: receive thread ended (task id 4778)
/var/log/netdata/error.log:2023-06-28 14:01:10: netdata INFO  : MAIN : RRD: 'host:Children1-prod' cleaning up disk files...
/var/log/netdata/error.log:2023-06-28 14:01:10: netdata INFO  : MAIN : RRD: 'host:Children1-prod' stopping data collection...
/var/log/netdata/error.log:2023-06-28 14:01:11: netdata INFO  : MAIN : Host 'Children1-prod' (at registry as 'Children1-prod') with guid 'd15ebc3a-15ba-11ee-864c-005056bbfda6' initialized, os 'linux', timezone 'Europe/Paris', tags '', program_name 'netdata', program_version 'v1.40.1', update every 5, memory mode dbengine, history entries 0, streaming disabled (to '' with api key ''), health disabled, cache_dir '/var/cache/netdata', alarms default handler '', alarms default recipient ''
/var/log/netdata/error.log:2023-06-28 14:01:38: netdata INFO  : RCVR[Children1-pr : STREAM Children1-prod [localhost]:40140: receive thread created (task id 5823)
/var/log/netdata/error.log:2023-06-28 14:01:38: netdata INFO  : RCVR[Children1-pr : Host Children1-prod is not in archived mode anymore
/var/log/netdata/error.log:2023-06-28 14:01:38: netdata INFO  : RCVR[Children1-pr : STREAM Children1-prod [receive from [localhost]:40140]: established link with negotiated capabilities: VCAPS HLABELS CLAIM CLABELS FUNCTIONS REPLICATION BINARY INTERPOLATED IEEE754
/var/log/netdata/error.log:2023-06-28 14:01:38: netdata INFO  : RCVR[Children1-pr : STREAM 'Children1-prod' [receive from [localhost]:40140]: ready to receive data. STATUS: CONNECTED
/var/log/netdata/error.log:2023-06-28 14:09:01: netdata INFO  : MAIN : Host 'Children1-prod' (at registry as 'Children1-prod') with guid 'd15ebc3a-15ba-11ee-864c-005056bbfda6' initialized, os 'linux', timezone 'Europe/Paris', tags '', program_name 'netdata', program_version 'v1.40.1', update every 5, memory mode dbengine, history entries 0, streaming disabled (to '' with api key ''), health disabled, cache_dir '/var/cache/netdata', alarms default handler '', alarms default recipient ''
/var/log/netdata/error.log:2023-06-28 14:09:01: netdata INFO  : RCVR[Children1-pr : STREAM Children1-prod [localhost]:50222: receive thread created (task id 6780)
/var/log/netdata/error.log:2023-06-28 14:09:01: netdata INFO  : RCVR[Children1-pr : STREAM 'Children1-prod' [receive from [localhost]:50222]: host is initializing. STATUS: INITIALIZATION IN PROGRESS RETRY LATER
/var/log/netdata/error.log:2023-06-28 14:09:01: netdata INFO  : RCVR[Children1-pr : STREAM 'Children1-prod' [receive from [localhost]:50222]: receive thread ended (task id 6780)
/var/log/netdata/error.log:2023-06-28 14:11:01: netdata INFO  : RCVR[Children1-pr : STREAM Children1-prod [localhost]:54852: receive thread created (task id 7015)
/var/log/netdata/error.log:2023-06-28 14:11:01: netdata INFO  : RCVR[Children1-pr : Host Children1-prod is not in archived mode anymore
/var/log/netdata/error.log:2023-06-28 14:11:01: netdata INFO  : RCVR[Children1-pr : STREAM Children1-prod [receive from [localhost]:54852]: established link with negotiated capabilities: VCAPS HLABELS CLAIM CLABELS FUNCTIONS REPLICATION BINARY INTERPOLATED IEEE754
/var/log/netdata/error.log:2023-06-28 14:11:01: netdata INFO  : RCVR[Children1-pr : STREAM 'Children1-prod' [receive from [localhost]:54852]: ready to receive data. STATUS: CONNECTED
/var/log/netdata/error.log:2023-06-28 14:15:13: netdata INFO  : RCVR[Children1-pr : STREAM 'Children1-prod' [receive from [localhost]:54852]: receive thread ended (task id 7015)
/var/log/netdata/error.log:2023-06-28 14:15:15: netdata INFO  : MAIN : RRD: 'host:Children1-prod' cleaning up disk files...
/var/log/netdata/error.log:2023-06-28 14:15:15: netdata INFO  : MAIN : RRD: 'host:Children1-prod' stopping data collection...
/var/log/netdata/error.log:2023-06-28 14:15:44: netdata INFO  : RCVR[Children1-pr : STREAM Children1-prod [localhost]:42954: receive thread created (task id 7800)
/var/log/netdata/error.log:2023-06-28 14:15:44: netdata INFO  : RCVR[Children1-pr : Host 'Children1-prod' (at registry as 'Children1-prod') with guid 'd15ebc3a-15ba-11ee-864c-005056bbfda6' initialized, os 'linux', timezone 'Europe/Paris', tags '', program_name 'netdata', program_version 'v1.40.1', update every 5, memory mode dbengine, history entries 0, streaming disabled (to '' with api key ''), health disabled, cache_dir '/var/cache/netdata', alarms default handler '', alarms default recipient ''
/var/log/netdata/error.log:2023-06-28 14:15:44: netdata INFO  : RCVR[Children1-pr : STREAM Children1-prod [receive from [localhost]:42954]: established link with negotiated capabilities: VCAPS HLABELS CLAIM CLABELS FUNCTIONS REPLICATION BINARY INTERPOLATED IEEE754
/var/log/netdata/error.log:2023-06-28 14:15:44: netdata INFO  : RCVR[Children1-pr : STREAM 'Children1-prod' [receive from [localhost]:42954]: ready to receive data. STATUS: CONNECTED
```

Let me know if you need me to send these files to some mailbox.

### Expected behavior

Streaming data to parent be correctly parsed by prometheus. 

### Steps to reproduce

I'm not sure if it's because of these double layers of Nginx/Forwarding/Reversing TCP Streaming Proxy layer, I tried with Netdata listening directly to the Public IP and it didn't improve things, just got more verbose logs.

1. Have Nginx as TCP Streaming forwarding netdata child Agent's data to Nginx as TCP Streaming reverse proxy to Netdata Parent agent
2. Set up netdata-latest.gz.run on all of children. Build from source tag v1.40.1 on Parent.
3. Try to scrape /api/v1/allmetrics?format=prometheus_all_hosts` on the HTTP server should bring all metrics from all children.

### Installation method

kickstart.sh

### System info

```shell
Parent:

/etc/centos-release:CentOS Linux release 7.9.2009 (Core)
/etc/os-release:NAME="CentOS Linux"
/etc/os-release:VERSION="7 (Core)"
/etc/os-release:ID="centos"
/etc/os-release:ID_LIKE="rhel fedora"
/etc/os-release:VERSION_ID="7"
/etc/os-release:PRETTY_NAME="CentOS Linux 7 (Core)"
/etc/os-release:ANSI_COLOR="0;31"
/etc/os-release:CPE_NAME="cpe:/o:centos:centos:7"
/etc/os-release:
/etc/os-release:CENTOS_MANTISBT_PROJECT="CentOS-7"
/etc/os-release:CENTOS_MANTISBT_PROJECT_VERSION="7"
/etc/os-release:REDHAT_SUPPORT_PRODUCT="centos"
/etc/os-release:REDHAT_SUPPORT_PRODUCT_VERSION="7"
/etc/os-release:
/etc/redhat-release:CentOS Linux release 7.9.2009 (Core)
/etc/system-release:CentOS Linux release 7.9.2009 (Core)
```
One of the children:
```
/etc/oracle-release:Oracle Linux Server release 7.9
/etc/os-release:NAME="Oracle Linux Server"
/etc/os-release:VERSION="7.9"
/etc/os-release:ID="ol"
/etc/os-release:ID_LIKE="fedora"
/etc/os-release:VARIANT="Server"
/etc/os-release:VARIANT_ID="server"
/etc/os-release:VERSION_ID="7.9"
/etc/os-release:PRETTY_NAME="Oracle Linux Server 7.9"
/etc/os-release:ANSI_COLOR="0;31"
/etc/os-release:CPE_NAME="cpe:/o:oracle:linux:7:9:server"
/etc/os-release:
/etc/os-release:ORACLE_BUGZILLA_PRODUCT="Oracle Linux 7"
/etc/os-release:ORACLE_BUGZILLA_PRODUCT_VERSION=7.9
/etc/os-release:ORACLE_SUPPORT_PRODUCT="Oracle Linux"
/etc/os-release:ORACLE_SUPPORT_PRODUCT_VERSION=7.9
/etc/redhat-release:Red Hat Enterprise Linux Server release 7.9 (Maipo)
/etc/system-release:Oracle Linux Server release 7.9
```
```


### Netdata build info

```shell
Parent:

# netdata -W buildinfo
Version: netdata v1.40.1
Configure options:  '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--disable-cloud' '--with-bundled-protobuf' 'CFLAGS=-O0 -ggdb -fsanitize=address -fno-omit-frame-pointer' 'LDFLAGS='
Install type: custom
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              NO (by user request)
    ACLK:                       NO
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         NO
    HTTPD (h2o):                YES
Libraries:
    protobuf:                YES (bundled)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    debugfs:                 YES
    EBPF:                    YES
    IPMI:                    NO
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: NO
Debug/Developer Features:
    Trace Allocations:       NO
```
One of the children:
```
# /opt/netdata/bin/srv/netdata -W buildinfo
Version: netdata v1.40.1
Configure options:  '--prefix=/opt/netdata/usr' '--sysconfdir=/opt/netdata/etc' '--localstatedir=/opt/netdata/var' '--libexecdir=/opt/netdata/usr/libexec' '--libdir=/opt/netdata/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--enable-cloud' '--without-bundled-protobuf' '--disable-dependency-tracking' 'CFLAGS=-static -O2 -I/openssl-static/include -I/libnetfilter-acct-static/include/libnetfilter_acct -I/usr/include/libmnl -pipe' 'LDFLAGS=-static -L/openssl-static/lib -L/libnetfilter-acct-static/lib -lnetfilter_acct -L/usr/lib -lmnl' 'PKG_CONFIG=pkg-config --static' 'PKG_CONFIG_PATH=/openssl-static/lib/pkgconfig:/libnetfilter-acct-static/lib/pkgconfig:/usr/lib/pkgconfig'
Install type: manual-static
    Binary architecture: x86_64
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES
    ACLK:                       YES
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
    HTTPD (h2o):                YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    debugfs:                 YES
    EBPF:                    YES
    IPMI:                    NO
    NFACCT:                  YES
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
Debug/Developer Features:
    Trace Allocations:       NO
```
```


### Additional info

Let me know to which mailbox I should send them logs.

**Comment by ilyam8** [comment]
Hey, @marcelmfs. Should be much faster after #15276. But you will need to switch your parent to the nightly channel.

**Comment by marcelmfs** [comment]
Hi @ilyam8 

After installing nightly on the parent, it's segfaulting:
```
[Thu Jun 29 07:05:34 2023] WEB[9][18383]: segfault at 10 ip 0000000000cc570b sp 00007f0666bb8d08 error 6
[Thu Jun 29 07:15:06 2023] WEB[14][18998]: segfault at 10 ip 0000000000cc570b sp 00007f2197febd08 error 6
```

**Comment by marcelmfs** [comment]
And with a build of the master branch netdata won't start.

**Comment by MrZammler** [comment]
Hi @marcelmfs Can you also please paste part of the error.log during the crash ?

**Comment by MrZammler** [comment]
Could also check with `coredumpctl` if there's more info on the crash?

**Comment by marcelmfs** [comment]
Hi @MrZammler

In the meantime I cherry picked @ilyam8's change into the v.1.40.1 tag to filter out other changes that could have been causing the crash and so far it's stable but the status I have is the same, _some_ hosts' metrics are still not being retrieved from the request to `/api/v1/allmetrics?format=prometheus_all_hosts` although I can see them being updated in the Parent's Dashboard.

**Comment by marcelmfs** [comment]
I think it was due to the clock not being synchronised, I manually forced an update of the server's clock and now it's showing  all metrics in prometheus.

**Comment by ilyam8** [comment]
> I think it was due to the clock not being synchronised

Perhaps, as far as I remember, Netdata keeps a timestamp of the last scrape and only exports metrics that have been updated since then.

> other changes that could have been causing the crash

It is #15087, parents with a lot of children can crash. Fixed in #15280.

**Comment by marcelmfs** [comment]
Well, the child agent who had it's clock resynchronised is again showing only a few keys on Prometheus, and now the clock is in sync so that didn't fix it.
