### ISSUE TITLE
[Bug]: Parents are dying unexpectedly without any signs of problems happening before

### ISSUE THREAD

**Issue by hugovalente-pm** [netdata/netdata#16876]
### Bug description

Since the last big update with the new protocol user parents are dying unexpectedly without any signs of problems before.
The agent is running but it doesn’t do anything. User has to `kill -9 netdata` and restart the agent.

### Expected behavior

Update shouldn't have caused parents to suddenly dying

### Steps to reproduce

1.
2.
3.
...

### Installation method

kickstart.sh

### System info

```shell
Linux netdata-parent-XXXXXXXX- #101-Ubuntu SMP Tue Nov 14 13:30:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=22.04
/etc/lsb-release:DISTRIB_CODENAME=jammy
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 22.04.3 LTS"
/etc/os-release:PRETTY_NAME="Ubuntu 22.04.3 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION_ID="22.04"
/etc/os-release:VERSION="22.04.3 LTS (Jammy Jellyfish)"
/etc/os-release:VERSION_CODENAME=jammy
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:UBUNTU_CODENAME=jammy
```

### Netdata build info

```shell
Packaging:
    Netdata Version ____________________________________________ : v1.44.1
    Installation Type __________________________________________ : binpkg-deb
    Package Architecture _______________________________________ : x86_64
    Package Distro _____________________________________________ :
    Configure Options __________________________________________ :  '--build=x86_64-linux-gnu' '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--disable-option-checking' '--disable-silent-rules' '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' '--disable-maintainer-mode' '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libdir=/usr/lib' '--libexecdir=/usr/libexec' '--with-user=netdata' '--with-math' '--with-zlib' '--with-webdir=/var/lib/netdata/www' '--disable-dependency-tracking' 'build_alias=x86_64-linux-gnu' 'CFLAGS=-g -O2 -ffile-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CXXFLAGS=-g -O2 -ffile-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security'
Default Directories:
    User Configurations ________________________________________ : /etc/netdata
    Stock Configurations _______________________________________ : /usr/lib/netdata/conf.d
    Ephemeral Databases (metrics data, metadata) _______________ : /var/cache/netdata
    Permanent Databases ________________________________________ : /var/lib/netdata
    Plugins ____________________________________________________ : /usr/libexec/netdata/plugins.d
    Static Web Files ___________________________________________ : /var/lib/netdata/www
    Log Files __________________________________________________ : /var/log/netdata
    Lock Files _________________________________________________ : /var/lib/netdata/lock
    Home _______________________________________________________ : /var/lib/netdata
Operating System:
    Kernel _____________________________________________________ : Linux
    Kernel Version _____________________________________________ : 5.15.0-91-generic
    Operating System ___________________________________________ : Ubuntu
    Operating System ID ________________________________________ : ubuntu
    Operating System ID Like ___________________________________ : debian
    Operating System Version ___________________________________ : 22.04.3 LTS (Jammy Jellyfish)
    Operating System Version ID ________________________________ : none
    Detection __________________________________________________ : /etc/os-release
Hardware:
    CPU Cores __________________________________________________ : 64
    CPU Frequency ______________________________________________ : 1996000000
    RAM Bytes __________________________________________________ : 135052869632
    Disk Capacity ______________________________________________ : 536870912000
    CPU Architecture ___________________________________________ : x86_64
    Virtualization Technology __________________________________ : kvm
    Virtualization Detection ___________________________________ : systemd-detect-virt
Container:
    Container __________________________________________________ : none
    Container Detection ________________________________________ : systemd-detect-virt
    Container Orchestrator _____________________________________ : none
    Container Operating System _________________________________ : none
    Container Operating System ID ______________________________ : none
    Container Operating System ID Like _________________________ : none
    Container Operating System Version _________________________ : none
    Container Operating System Version ID ______________________ : none
    Container Operating System Detection _______________________ : none
Features:
    Built For __________________________________________________ : Linux
    Netdata Cloud ______________________________________________ : YES
    Health (trigger alerts and send notifications) _____________ : YES
    Streaming (stream metrics to parent Netdata servers) _______ : YES
    Back-filling (of higher database tiers) ____________________ : YES
    Replication (fill the gaps of parent Netdata servers) ______ : YES
    Streaming and Replication Compression ______________________ : YES (zstd lz4 gzip)
    Contexts (index all active and archived metrics) ___________ : YES
    Tiering (multiple dbs with different metrics resolution) ___ : YES (5)
    Machine Learning ___________________________________________ : YES
Database Engines:
    dbengine ___________________________________________________ : YES
    alloc ______________________________________________________ : YES
    ram ________________________________________________________ : YES
    map ________________________________________________________ : YES
    save _______________________________________________________ : YES
    none _______________________________________________________ : YES
Connectivity Capabilities:
    ACLK (Agent-Cloud Link: MQTT over WebSockets over TLS) _____ : YES
    static (Netdata internal web server) _______________________ : YES
    h2o (web server) ___________________________________________ : YES
    WebRTC (experimental) ______________________________________ : NO
    Native HTTPS (TLS Support) _________________________________ : YES
    TLS Host Verification ______________________________________ : YES
Libraries:
    LZ4 (extremely fast lossless compression algorithm) ________ : YES
    ZSTD (fast, lossless compression algorithm) ________________ : YES
    zlib (lossless data-compression library) ___________________ : YES
    Judy (high-performance dynamic arrays and hashtables) ______ : YES (bundled)
    dlib (robust machine learning toolkit) _____________________ : YES (bundled)
    protobuf (platform-neutral data serialization protocol) ____ : YES (system)
    OpenSSL (cryptography) _____________________________________ : YES
    libdatachannel (stand-alone WebRTC data channels) __________ : NO
    JSON-C (lightweight JSON manipulation) _____________________ : YES
    libcap (Linux capabilities system operations) ______________ : NO
    libcrypto (cryptographic functions) ________________________ : YES
    libm (mathematical functions) ______________________________ : YES
    jemalloc ___________________________________________________ : NO
    TCMalloc ___________________________________________________ : NO
Plugins:
    apps (monitor processes) ___________________________________ : YES
    cgroups (monitor containers and VMs) _______________________ : YES
    cgroup-network (associate interfaces to CGROUPS) ___________ : YES
    proc (monitor Linux systems) _______________________________ : YES
    tc (monitor Linux network QoS) _____________________________ : YES
    diskspace (monitor Linux mount points) _____________________ : YES
    freebsd (monitor FreeBSD systems) __________________________ : NO
    macos (monitor MacOS systems) ______________________________ : NO
    statsd (collect custom application metrics) ________________ : YES
    timex (check system clock synchronization) _________________ : YES
    idlejitter (check system latency and jitter) _______________ : YES
    bash (support shell data collection jobs - charts.d) _______ : YES
    debugfs (kernel debugging metrics) _________________________ : YES
    cups (monitor printers and print jobs) _____________________ : YES
    ebpf (monitor system calls) ________________________________ : YES
    freeipmi (monitor enterprise server H/W) ___________________ : YES
    nfacct (gather netfilter accounting) _______________________ : YES
    perf (collect kernel performance events) ___________________ : YES
    slabinfo (monitor kernel object caching) ___________________ : YES
    Xen ________________________________________________________ : NO
    Xen VBD Error Tracking _____________________________________ : NO
    Logs Management ____________________________________________ : YES
Exporters:
    AWS Kinesis ________________________________________________ : NO
    GCP PubSub _________________________________________________ : NO
    MongoDB ____________________________________________________ : YES
    Prometheus (OpenMetrics) Exporter __________________________ : YES
    Prometheus Remote Write ____________________________________ : YES
    Graphite ___________________________________________________ : YES
    Graphite HTTP / HTTPS ______________________________________ : YES
    JSON _______________________________________________________ : YES
    JSON HTTP / HTTPS __________________________________________ : YES
    OpenTSDB ___________________________________________________ : YES
    OpenTSDB HTTP / HTTPS ______________________________________ : YES
    All Metrics API ____________________________________________ : YES
    Shell (use metrics in shell scripts) _______________________ : YES
Debug/Developer Features:
    Trace All Netdata Allocations (with charts) ________________ : NO
    Developer Mode (more runtime checks, slower) _______________ : NO
```

### Additional info

Install method details - Kickstart.sh with forced repo packages.

Logs:
> It’s a little bit strange. The last lines in the logs before the issue occurs shows a shutdown command. This seems to get stuck which lead to the problem that netdata is running but not working.

Other input from user:
> Today i’ve found another issue. /var/run/netdata/ doesn’t exist. So the pid file couldn’t get created. But i think that’s not a real issue until you try to setup Monit :)

**Comment by ilyam8** [comment]
> parents are dying

Hey, @hugovalente-pm. Can you please:

- define "dying"? "agent is running but it doesn’t do anything" is not helpful, I am not sure what that means.
- give a detailed description of the setup.
- provide more information about the problem - How often it happens? Are there any Netdata threads using 100% during "dying"? 
- provide full logs from Netdata start till "dying".

**Comment by ilyam8** [comment]
> dying = crashing

This contradicts "User has to kill -9 netdata and restart the agent.". 


> checking if user can jump on the issue

Yes. I think we can't do much without it.

**Comment by hugovalente-pm** [comment]
user doesn't have time to provide more details due workload but was able to share the following

> Yesterday evening Monit restarted Netdata because of connection issues. Some minutes before syslog logged a segfault. I don’t know if it’s related to this issue.

**PARENT-100**
```
[2024-01-30T10:01:12+0000] info     : 'netdata' process is running with pid 420619
[2024-01-30T18:47:21+0000] error    : 'netdata' process is not running
[2024-01-30T18:47:21+0000] info     : 'netdata' trying to restart
[2024-01-30T18:47:21+0000] info     : 'netdata' start: '/usr/bin/killall -9 netdata && /usr/bin/systemctl start netdata'
[2024-01-30T18:51:25+0000] info     : 'netdata' process is running with pid 475569
```

```
Jan 30 18:29:07 netdata-parent-100 netdata[420619]: FUNCTIONS: function 'processes' of host 'nc-linseis-transfer3' changed collector from 461423 to 475401
Jan 30 18:29:07 netdata-parent-100 netdata[420619]: FUNCTIONS: function 'processes' of host 'nc-linseis-transfer3' changed execute callback data
Jan 30 18:29:07 netdata-parent-100 netdata[420619]: FUNCTIONS: function 'block-devices' of host 'nc-linseis-transfer3' changed collector from 461423 to 475401
Jan 30 18:29:07 netdata-parent-100 netdata[420619]: FUNCTIONS: function 'block-devices' of host 'nc-linseis-transfer3' changed execute callback data
Jan 30 18:29:07 netdata-parent-100 netdata[420619]: STREAM 'steindesign2' [receive from [185.147.217.162]:42862]: thread 461202 takes too long to stop, giving up...
Jan 30 18:29:08 netdata-parent-100 netdata[420619]: DBENGINE: journal file 18775 needs to be indexed, but it has writers working on it - skipping it for now
Jan 30 18:29:09 netdata-parent-100 kernel: [619671.564059] show_signal_msg: 6 callbacks suppressed
Jan 30 18:29:09 netdata-parent-100 kernel: [619671.564062] UV_WORKER[118][420890]: segfault at 80000001 ip 00007fba8b1f87fd sp 00007fba3cfc2848 error 4 in libc.so.6[7fba8b083000+195000]
Jan 30 18:29:09 netdata-parent-100 kernel: [619671.564096] Code: f8 77 c3 66 2e 0f 1f 84 00 00 00 00 00 f3 0f 1e fa 89 f8 48 89 fa c5 f9 ef c0 25 ff 0f 00 00 3d e0 0f 00 00 0f 87 33 01 00 00 <c5> fd 74 0f c5 fd d7 c1 85 c0 74 57 f3 0f bc c0 c5 f8 77 c3 66 66
Jan 30 18:29:09 netdata-parent-100 netdata[420619]: DBENGINE: journal file 18775 needs to be indexed, but it has writers working on it - skipping it for now
Jan 30 18:35:01 netdata-parent-100 CRON[475465]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Jan 30 18:44:01 netdata-parent-100 CRON[475529]: (daemon) CMD (test -x /usr/bin/debsecan && /usr/bin/debsecan --cron)
Jan 30 18:45:01 netdata-parent-100 CRON[475537]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Jan 30 18:46:23 netdata-parent-100 apps.plugin[421211]: Received error on stdin.
Jan 30 18:46:23 netdata-parent-100 debugfs.plugin[421237]: error writing to stdout: EPIPE. Exiting...
Jan 30 18:46:23 netdata-parent-100 netdata[420621]: EOF found in spawn pipe.
Jan 30 18:46:23 netdata-parent-100 netdata[420621]: Shutting down spawn server event loop.
Jan 30 18:46:23 netdata-parent-100 netdata[420621]: Shutting down spawn server loop complete.
Jan 30 18:46:23 netdata-parent-100 ebpf.plugin[421234]: Received error on stdin.
Jan 30 18:46:23 netdata-parent-100 systemd-journal.plugin[421232]: Received error on stdin.
Jan 30 18:46:23 netdata-parent-100 systemd[1]: netdata.service: Main process exited, code=killed, status=11/SEGV
Jan 30 18:48:54 netdata-parent-100 systemd[1]: netdata.service: State 'stop-sigterm' timed out. Killing.
Jan 30 18:48:54 netdata-parent-100 systemd[1]: netdata.service: Killing process 421234 (ebpf.plugin) with signal SIGKILL.
Jan 30 18:48:54 netdata-parent-100 systemd[1]: netdata.service: Killing process 421358 (EBPF PROCESS) with signal SIGKILL.
Jan 30 18:48:54 netdata-parent-100 systemd[1]: netdata.service: Killing process 421359 (EBPF CACHESTAT) with signal SIGKILL.
Jan 30 18:48:54 netdata-parent-100 systemd[1]: netdata.service: Killing process 421360 (EBPF SWAP) with signal SIGKILL.
Jan 30 18:48:54 netdata-parent-100 systemd[1]: netdata.service: Killing process 421361 (EBPF MOUNT) with signal SIGKILL.
Jan 30 18:48:54 netdata-parent-100 systemd[1]: netdata.service: Killing process 421362 (EBPF FD) with signal SIGKILL.
Jan 30 18:48:54 netdata-parent-100 systemd[1]: netdata.service: Killing process 421363 (EBPF SOFTIRQ) with signal SIGKILL.
Jan 30 18:48:54 netdata-parent-100 systemd[1]: netdata.service: Killing process 421368 (EBPF SHM) with signal SIGKILL.
Jan 30 18:48:54 netdata-parent-100 systemd[1]: netdata.service: Killing process 421372 (EBPF_READER) with signal SIGKILL.
Jan 30 18:48:54 netdata-parent-100 systemd[1]: netdata.service: Killing process 421373 (EBPF_WORK[1]) with signal SIGKILL.
Jan 30 18:48:54 netdata-parent-100 systemd[1]: netdata.service: Failed with result 'signal'.
Jan 30 18:48:54 netdata-parent-100 systemd[1]: netdata.service: Consumed 5d 12h 4min 53.099s CPU time.
Jan 30 18:49:24 netdata-parent-100 systemd[1]: netdata.service: Scheduled restart job, restart counter is at 3.
Jan 30 18:49:24 netdata-parent-100 systemd[1]: Stopped Real time performance monitoring.
Jan 30 18:49:24 netdata-parent-100 systemd[1]: netdata.service: Consumed 5d 12h 4min 53.099s CPU time.
Jan 30 18:49:24 netdata-parent-100 systemd[1]: Started Real time performance monitoring.
Jan 30 18:49:24 netdata-parent-100 netdata[475569]: Netdata agent version "v1.44.1" is starting
Jan 30 18:49:24 netdata-parent-100 netdata[475569]: IEEE754: system is using IEEE754 DOUBLE PRECISION values
Jan 30 18:49:24 netdata-parent-100 netdata[475569]: TIMEZONE: using the contents of /etc/timezone
Jan 30 18:49:24 netdata-parent-100 netdata[475569]: TIMEZONE: fixed as 'Etc/UTC'
Jan 30 18:49:24 netdata-parent-100 netdata[475569]: NETDATA STARTUP: next: initialize ML
Jan 30 18:49:25 netdata-parent-100 netdata[475569]: ml database version is 2 (no migration needed)
Jan 30 18:49:25 netdata-parent-100 netdata[475569]: NETDATA STARTUP: in      76 ms, initialize ML - next: initialize signals
Jan 30 18:49:25 netdata-parent-100 netdata[475569]: NETDATA STARTUP: in       0 ms, initialize signals - next: initialize static threads
Jan 30 18:49:25 netdata-parent-100 netdata[475569]: NETDATA STARTUP: in       0 ms, initialize static threads - next: initialize web server
Jan 30 18:49:25 netdata-parent-100 netdata[475569]: NETDATA STARTUP: in       0 ms, initialize web server - next: initialize h2o server
Jan 30 18:49:25 netdata-parent-100 netdata[475569]: NETDATA STARTUP: in       0 ms, initialize h2o server - next: set resource limits
Jan 30 18:49:25 netdata-parent-100 netdata[475569]: resources control: allowed file descriptors: soft = 1024, max = 524288
Jan 30 18:49:25 netdata-parent-100 netdata[475569]: NETDATA STARTUP: in       0 ms, set resource limits - next: become daemon
Jan 30 18:49:25 netdata-parent-100 netdata[475569]: Out-Of-Memory (OOM) score is already set to the wanted value 0
Jan 30 18:49:25 netdata-parent-100 netdata[475569]: Running with process scheduling policy 'batch', nice level 0
Jan 30 18:49:25 netdata-parent-100 netdata[475569]: netdata started on pid 475569.
Jan 30 18:49:25 netdata-parent-100 netdata[475569]: NETDATA STARTUP: in       4 ms, become daemon - next: initialize threads after fork
Jan 30 18:49:25 netdata-parent-100 netdata[475569]: NETDATA STARTUP: in       0 ms, initialize threads after fork - next: initialize registry
Jan 30 18:49:25 netdata-parent-100 netdata[475569]: NETDATA STARTUP: in       0 ms, initialize registry - next: fork the spawn server
Jan 30 18:49:25 netdata-parent-100 netdata[475569]: Initializing spawn client.
Jan 30 18:49:25 netdata-parent-100 netdata[475569]: NETDATA STARTUP: in       1 ms, fork the spawn server - next: collecting system info
Jan 30 18:49:25 netdata-parent-100 netdata[475571]: Spawn server is up.
Jan 30 18:49:26 netdata-parent-100 netdata[475569]: NETDATA STARTUP: in    1453 ms, collecting system info - next: initialize RRD structures
Jan 30 18:49:26 netdata-parent-100 netdata[475569]: SQLite database /var/cache/netdata/netdata-meta.db initialization
Jan 30 18:49:26 netdata-parent-100 netdata[475569]: metadata database version is 15 (no migration needed)
Jan 30 18:49:26 netdata-parent-100 netdata[475569]: SQLite database initialization completed
Jan 30 18:49:26 netdata-parent-100 netdata[475569]: SQLite database /var/cache/netdata/context-meta.db initialization
Jan 30 18:49:26 netdata-parent-100 netdata[475569]: context database version is 1 (no migration needed)
Jan 30 18:49:30 netdata-parent-100 netdata[475569]: Cannot open the file /var/lib/netdata/health.silencers.json, so Netdata will work with the default health configuration.
Jan 30 18:49:30 netdata-parent-100 netdata[475569]: DBENGINE: found 229 files in path /var/cache/netdata/dbengine
Jan 30 18:49:30 netdata-parent-100 netdata[475569]: DBENGINE: loading 77 data/journal of tier 0...
Jan 30 18:49:30 netdata-parent-100 netdata[475569]: DBENGINE: found 314 files in path /var/cache/netdata/dbengine-tier2
Jan 30 18:49:30 netdata-parent-100 netdata[475569]: DBENGINE: found 575 files in path /var/cache/netdata/dbengine-tier1
Jan 30 18:49:30 netdata-parent-100 netdata[475569]: DBENGINE: loading 105 data/journal of tier 2...
Jan 30 18:49:30 netdata-parent-100 netdata[475569]: DBENGINE: loading 192 data/journal of tier 1...
Jan 30 18:49:32 netdata-parent-100 netdata[475569]: DBENGINE: populating retention to MRG from 192 journal files of tier 1, using 21 threads...
Jan 30 18:49:34 netdata-parent-100 netdata[475569]: DBENGINE: populating retention to MRG from 105 journal files of tier 2, using 21 threads...
Jan 30 18:49:45 netdata-parent-100 netdata[475569]: DBENGINE: indexing file '/var/cache/netdata/dbengine/journalfile-1-0000018775.njfv2': extents 14258, metrics 870023, pages 912512
Jan 30 18:49:46 netdata-parent-100 netdata[475569]: DBENGINE: migrated journal file '/var/cache/netdata/dbengine/journalfile-1-0000018775.njfv2', file size 79003688
Jan 30 18:49:54 netdata-parent-100 netdata[475569]: DBENGINE: populating retention to MRG from 77 journal files of tier 0, using 21 threads...
Jan 30 18:50:15 netdata-parent-100 netdata[475569]: DBENGINE: tier 0 is ready for data collection and queries
Jan 30 18:50:15 netdata-parent-100 netdata[475569]: DBENGINE: tier 1 is ready for data collection and queries
Jan 30 18:50:15 netdata-parent-100 netdata[475569]: DBENGINE: tier 2 is ready for data collection and queries
```

**PARENT-1**

```
[2024-01-30T20:25:29+0000] error    : 'netdata' failed protocol test [DEFAULT] at [localhost]:19999 [TCP/IP] -- Connection refused
[2024-01-30T20:25:29+0000] info     : 'netdata' exec: '/usr/bin/killall -9 netdata'
[2024-01-30T20:31:29+0000] info     : 'netdata' connection succeeded to [localhost]:19999 [TCP/IP]
```

Some hours before:
```
Jan 30 17:22:07 netdata-parent-1kernel: [615514.855011] INFO: task UV_WORKER[6]:193338 blocked for more than 120 seconds.
Jan 30 17:22:07 netdata-parent-1kernel: [615514.855146]       Not tainted 5.15.0-91-generic #101-Ubuntu
Jan 30 17:22:07 netdata-parent-1kernel: [615514.855291] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
Jan 30 17:22:07 netdata-parent-1kernel: [615514.855427] task:UV_WORKER[6]    state:D stack:    0 pid:193338 ppid:     1 flags:0x00000002
Jan 30 17:22:07 netdata-parent-1kernel: [615514.855428] Call Trace:
Jan 30 17:22:07 netdata-parent-1kernel: [615514.855429]  <TASK>
Jan 30 17:22:07 netdata-parent-1kernel: [615514.855430]  __schedule+0x24e/0x590
Jan 30 17:22:07 netdata-parent-1kernel: [615514.855432]  ? _raw_spin_unlock_irqrestore+0xe/0x30
Jan 30 17:22:07 netdata-parent-1kernel: [615514.855434]  schedule+0x69/0x110
Jan 30 17:22:07 netdata-parent-1kernel: [615514.855436]  rwsem_down_write_slowpath+0x230/0x3e0
Jan 30 17:22:07 netdata-parent-1kernel: [615514.855437]  ? default_wake_function+0x1a/0x40
Jan 30 17:22:07 netdata-parent-1kernel: [615514.855440]  ? _raw_spin_unlock_irqrestore+0xe/0x30
Jan 30 17:22:07 netdata-parent-1kernel: [615514.855442]  down_write+0x47/0x60
Jan 30 17:22:07 netdata-parent-1kernel: [615514.855443]  ext4_dio_write_iter+0xe1/0x430
Jan 30 17:22:07 netdata-parent-1kernel: [615514.855445]  ext4_file_write_iter+0x38/0x60
Jan 30 17:22:07 netdata-parent-1kernel: [615514.855447]  new_sync_write+0x114/0x1a0
Jan 30 17:22:07 netdata-parent-1kernel: [615514.855449]  vfs_write+0x1d5/0x270
Jan 30 17:22:07 netdata-parent-1kernel: [615514.855451]  __x64_sys_pwrite64+0x96/0xc0
Jan 30 17:22:07 netdata-parent-1kernel: [615514.855452]  do_syscall_64+0x5c/0xc0
Jan 30 17:22:07 netdata-parent-1kernel: [615514.855454]  ? exit_to_user_mode_prepare+0x37/0xb0
Jan 30 17:22:07 netdata-parent-1kernel: [615514.855456]  ? syscall_exit_to_user_mode+0x35/0x50
Jan 30 17:22:07 netdata-parent-1kernel: [615514.855457]  ? __x64_sys_write+0x19/0x20
Jan 30 17:22:07 netdata-parent-1kernel: [615514.855459]  ? do_syscall_64+0x69/0xc0
Jan 30 17:22:07 netdata-parent-1kernel: [615514.855460]  ? exit_to_user_mode_prepare+0x37/0xb0
Jan 30 17:22:07 netdata-parent-1kernel: [615514.855462]  ? syscall_exit_to_user_mode+0x35/0x50
Jan 30 17:22:07 netdata-parent-1kernel: [615514.855464]  ? __x64_sys_write+0x19/0x20
Jan 30 17:22:07 netdata-parent-1kernel: [615514.855465]  ? do_syscall_64+0x69/0xc0
Jan 30 17:22:07 netdata-parent-1kernel: [615514.855466]  ? sysvec_apic_timer_interrupt+0x4e/0x90
Jan 30 17:22:07 netdata-parent-1kernel: [615514.855468]  entry_SYSCALL_64_after_hwframe+0x62/0xcc
Jan 30 17:22:07 netdata-parent-1kernel: [615514.855470] RIP: 0033:0x7fc18c2fc83f
Jan 30 17:22:07 netdata-parent-1kernel: [615514.855471] RSP: 002b:00007fc17e26cb90 EFLAGS: 00000293 ORIG_RAX: 0000000000000012
Jan 30 17:22:07 netdata-parent-1kernel: [615514.855472] RAX: ffffffffffffffda RBX: 00007fc17e26d458 RCX: 00007fc18c2fc83f
Jan 30 17:22:07 netdata-parent-1kernel: [615514.855473] RDX: 0000000000001000 RSI: 000055bf64aab000 RDI: 00000000000001e1
Jan 30 17:22:07 netdata-parent-1kernel: [615514.855474] RBP: 0000000000000000 R08: 0000000000000000 R09: 0000000000000000
Jan 30 17:22:07 netdata-parent-1kernel: [615514.855474] R10: 000000000041d000 R11: 0000000000000293 R12: 00007fc18cd00678
Jan 30 17:22:07 netdata-parent-1kernel: [615514.855475] R13: 000055bb9124a620 R14: 0000000000000001 R15: 000055bb9124a5f8
Jan 30 17:22:07 netdata-parent-1kernel: [615514.855476]  </TASK>
```

**Comment by CreeperFace00** [comment]
I've also been having issues with my parent hanging in this way for a few months now. The logs show that Netdata is "cleaning up..." and "exiting"
Every time it happens I have to `killall -9 netdata` and restart the agent to get it running again.


It happened this morning:
```
Feb 01 10:25:11 netdata netdata[2002200]: cleaning up...
Feb 01 10:25:11 netdata netdata[2002200]: cleaning up...
Feb 01 10:25:11 netdata netdata[2002200]: STATSD: stopping data collection thread 1...
Feb 01 10:25:11 netdata netdata[2002200]: STATSD: closing sockets...
Feb 01 10:25:11 netdata netdata[2002200]: cleaning up...
Feb 01 10:25:11 netdata netdata[2002200]: cleaning up...
Feb 01 10:25:11 netdata netdata[2002200]: cleaning up...
Feb 01 10:25:11 netdata netdata[2002200]: cleaning up...
Feb 01 10:25:11 netdata netdata[2002200]: TC: killing with SIGTERM tc-qos-helper process 2008168
Feb 01 10:25:11 netdata netdata[2002200]: STATSD: cleanup completed.
Feb 01 10:25:11 netdata netdata[2002200]: cleaning up...
Feb 01 10:25:11 netdata netdata[2002200]: cleaning up...
Feb 01 10:25:11 netdata netdata[2002200]: TC: waiting for tc plugin child process pid 2008168 to exit...
Feb 01 10:25:11 netdata logs-management.plugin[2002558]: uv_run(main_loop, ...); no handles or requests - cleaning up...
Feb 01 10:25:11 netdata netdata[2002623]: level=info msg="received terminated signal (15). Terminating..." plugin=go.d component=agent
Feb 01 10:25:11 netdata netdata[2002623]: level=info msg=stopped plugin=go.d collector=logind job=logind
Feb 01 10:25:11 netdata netdata[2002623]: level=info msg=stopped plugin=go.d collector=systemdunits job=service-units
Feb 01 10:25:11 netdata netdata[2002623]: level=info msg="instance is stopped" plugin=go.d component="job manager"
Feb 01 10:25:11 netdata netdata[2002623]: level=info msg="instance is stopped" plugin=go.d component="discovery manager"
Feb 01 10:25:11 netdata netdata[2002623]: level=info msg="instance is stopped" plugin=go.d component="discovery file"
Feb 01 10:25:11 netdata netdata[2002623]: level=info msg="instance is stopped" plugin=go.d component="filestatus manager"
Feb 01 10:25:11 netdata netdata[2002623]: level=info msg="instance is stopped" plugin=go.d component="functions manager"
Feb 01 10:25:11 netdata netdata[2002623]: level=info msg="instance is stopped" plugin=go.d component=agent
Feb 01 10:25:12 netdata logs-management.plugin[2002558]: [stats charts]: thread exiting...
Feb 01 10:25:12 netdata netdata[2002200]: cleaning up...
Feb 01 10:25:12 netdata netdata[2002200]: waiting for discovery thread to finish...
Feb 01 10:25:12 netdata netdata[2002200]: discovery thread stopped
Feb 01 10:25:12 netdata logs-management.plugin[2002558]: [logs_manag_kmsg_logs]: p_file_info_destroy() cleanup...
Feb 01 10:25:12 netdata logs-management.plugin[2002558]: [logs_manag_systemd_logs]: p_file_info_destroy() cleanup...
Feb 01 10:25:12 netdata logs-management.plugin[2002558]: [logs_manag_systemd_logs]: p_file_info_destroy() cleanup done
Feb 01 10:25:12 netdata logs-management.plugin[2002558]: [logs_manag_kmsg_logs]: p_file_info_destroy() cleanup done
Feb 01 10:25:12 netdata logs-management.plugin[2002558]: logs management clean up done - exiting
```
[error.log](https://github.com/netdata/netdata/files/14129165/error.log)

I've been hesitant to open an issue about this due to the response on the last small issue I opened.

**Comment by grandich** [comment]
We are also seeing this issue; every team netdata-parent crashes because of this leak: https://github.com/netdata/netdata/issues/10423, it keeps crashing for ~1 hour trying to restart, reporting:

netdata-parent-867cb89b6d-7hkbj netdata 2024-02-08 15:31:04: netdata INFO  : MAIN : Created 375 archived hosts
netdata-parent-867cb89b6d-7hkbj netdata 2024-02-08 15:31:04: netdata INFO  : MAIN : ACLK sync initialization completed
netdata-parent-867cb89b6d-7hkbj netdata EOF found in spawn pipe.
netdata-parent-867cb89b6d-7hkbj netdata Shutting down spawn server event loop.
netdata-parent-867cb89b6d-7hkbj netdata Shutting down spawn server loop complete.

![image](https://github.com/netdata/netdata/assets/1310215/c1645956-3cb9-475f-a4e8-85e60dd0a3ed)


netdata-parent-867cb89b6d-7hkbj      0/1     CrashLoopBackOff   6 (114s ago)

**Comment by ilyam8** [comment]
@grandich @CreeperFace00 @AlwinAntreich hey, guys. Is it still happening in v1.44.2?

**Comment by grandich** [comment]
@ilyam8

For the initialization crash problem, we changed the EKS node where parent runs, from arm64 to x86_64 (changed family c6g to c6a) and it was resolved, never crashed again during startup. Don't know if it is related to the arch properly, or to some performance bottleneck during startup.  #(collecting metrics from 150 nodes). We'll test v1.44.2 with arm64 next week and inform.

For the progressive and slow memory leak related to high churn rate (ephemeral containers/kube cronjobs) which is the cause of restarts (oom kill), last time we tested with v1.44.0/1, we still saw the problem (pattern in image).

![image](https://github.com/netdata/netdata/assets/1310215/a82583ad-981d-4fbf-b9d6-43fd6a246c6b)

**Comment by ilyam8** [comment]
> For the progressive and slow memory leak related to high churn rate (ephemeral containers/kube cronjobs)

I think this is known and not fixed. There is an open issue.

**Comment by CreeperFace00** [comment]
It just happened again, my parent it running v1.44.0-349-nightly, not sure if that makes a difference.

```
max@netdata  ~  netdata -W buildinfo
Packaging:
    Netdata Version ____________________________________________ : v1.44.0-349-nightly
    Installation Type __________________________________________ : custom
    Package Architecture _______________________________________ : unknown
    Package Distro _____________________________________________ : unknown
    Configure Options __________________________________________ : dummy-configure-command
Default Directories:
    User Configurations ________________________________________ : /etc/netdata
    Stock Configurations _______________________________________ : /usr/lib/netdata/conf.d
    Ephemeral Databases (metrics data, metadata) _______________ : /var/cache/netdata
    Permanent Databases ________________________________________ : /var/lib/netdata
    Plugins ____________________________________________________ : /usr/libexec/netdata/plugins.d
    Static Web Files ___________________________________________ : /usr/share/netdata/web
    Log Files __________________________________________________ : /var/log/netdata
    Lock Files _________________________________________________ : /var/lib/netdata/lock
    Home _______________________________________________________ : /var/lib/netdata
Operating System:
    Kernel _____________________________________________________ : Linux
    Kernel Version _____________________________________________ : 5.15.0-91-generic
    Operating System ___________________________________________ : Ubuntu
    Operating System ID ________________________________________ : ubuntu
    Operating System ID Like ___________________________________ : debian
    Operating System Version ___________________________________ : 22.04.3 LTS (Jammy Jellyfish)
    Operating System Version ID ________________________________ : none
    Detection __________________________________________________ : /etc/os-release
Hardware:
    CPU Cores __________________________________________________ : 11
    CPU Frequency ______________________________________________ : 2200000000
    RAM Bytes __________________________________________________ : 16723726336
    Disk Capacity ______________________________________________ : 161061273600
    CPU Architecture ___________________________________________ : x86_64
    Virtualization Technology __________________________________ : kvm
    Virtualization Detection ___________________________________ : systemd-detect-virt
Container:
    Container __________________________________________________ : none
    Container Detection ________________________________________ : systemd-detect-virt
    Container Orchestrator _____________________________________ : none
    Container Operating System _________________________________ : none
    Container Operating System ID ______________________________ : none
    Container Operating System ID Like _________________________ : none
    Container Operating System Version _________________________ : none
    Container Operating System Version ID ______________________ : none
    Container Operating System Detection _______________________ : none
Features:
    Built For __________________________________________________ : Linux
    Netdata Cloud ______________________________________________ : YES
    Health (trigger alerts and send notifications) _____________ : YES
    Streaming (stream metrics to parent Netdata servers) _______ : YES
    Back-filling (of higher database tiers) ____________________ : YES
    Replication (fill the gaps of parent Netdata servers) ______ : YES
    Streaming and Replication Compression ______________________ : YES (zstd lz4 gzip)
    Contexts (index all active and archived metrics) ___________ : YES
    Tiering (multiple dbs with different metrics resolution) ___ : YES (5)
    Machine Learning ___________________________________________ : YES
Database Engines:
    dbengine ___________________________________________________ : YES
    alloc ______________________________________________________ : YES
    ram ________________________________________________________ : YES
    none _______________________________________________________ : YES
Connectivity Capabilities:
    ACLK (Agent-Cloud Link: MQTT over WebSockets over TLS) _____ : YES
    static (Netdata internal web server) _______________________ : YES
    h2o (web server) ___________________________________________ : YES
    WebRTC (experimental) ______________________________________ : NO
    Native HTTPS (TLS Support) _________________________________ : YES
    TLS Host Verification ______________________________________ : YES
Libraries:
    LZ4 (extremely fast lossless compression algorithm) ________ : YES
    ZSTD (fast, lossless compression algorithm) ________________ : YES
    zlib (lossless data-compression library) ___________________ : YES
    Brotli (generic-purpose lossless compression algorithm) ____ : NO
    protobuf (platform-neutral data serialization protocol) ____ : YES (bundled)
    OpenSSL (cryptography) _____________________________________ : YES
    libdatachannel (stand-alone WebRTC data channels) __________ : NO
    JSON-C (lightweight JSON manipulation) _____________________ : YES
    libcap (Linux capabilities system operations) ______________ : YES
    libcrypto (cryptographic functions) ________________________ : YES
    libyaml (library for parsing and emitting YAML) ____________ : YES
Plugins:
    apps (monitor processes) ___________________________________ : YES
    cgroups (monitor containers and VMs) _______________________ : YES
    cgroup-network (associate interfaces to CGROUPS) ___________ : YES
    proc (monitor Linux systems) _______________________________ : YES
    tc (monitor Linux network QoS) _____________________________ : YES
    diskspace (monitor Linux mount points) _____________________ : YES
    freebsd (monitor FreeBSD systems) __________________________ : NO
    macos (monitor MacOS systems) ______________________________ : NO
    statsd (collect custom application metrics) ________________ : YES
    timex (check system clock synchronization) _________________ : YES
    idlejitter (check system latency and jitter) _______________ : YES
    bash (support shell data collection jobs - charts.d) _______ : YES
    debugfs (kernel debugging metrics) _________________________ : YES
    cups (monitor printers and print jobs) _____________________ : NO
    ebpf (monitor system calls) ________________________________ : YES
    freeipmi (monitor enterprise server H/W) ___________________ : NO
    nfacct (gather netfilter accounting) _______________________ : NO
    perf (collect kernel performance events) ___________________ : YES
    slabinfo (monitor kernel object caching) ___________________ : YES
    Xen ________________________________________________________ : NO
    Xen VBD Error Tracking _____________________________________ : NO
    Logs Management ____________________________________________ : YES
Exporters:
    AWS Kinesis ________________________________________________ : NO
    GCP PubSub _________________________________________________ : NO
    MongoDB ____________________________________________________ : NO
    Prometheus (OpenMetrics) Exporter __________________________ : YES
    Prometheus Remote Write ____________________________________ : NO
    Graphite ___________________________________________________ : YES
    Graphite HTTP / HTTPS ______________________________________ : YES
    JSON _______________________________________________________ : YES
    JSON HTTP / HTTPS __________________________________________ : YES
    OpenTSDB ___________________________________________________ : YES
    OpenTSDB HTTP / HTTPS ______________________________________ : YES
    All Metrics API ____________________________________________ : YES
    Shell (use metrics in shell scripts) _______________________ : YES
Debug/Developer Features:
    Trace All Netdata Allocations (with charts) ________________ : NO
    Developer Mode (more runtime checks, slower) _______________ : NO
```

**Comment by AlwinAntreich** [comment]
So far it showed up once again with v1.44.2. Would it help if I ran the `netdata/netdata-debug` container image?
```
time=2024-02-10T12:51:53.967+00:00 comm=netdata source=daemon level=info tid=301 thread=REPLAY[1] msg="REPLICATION SUMMARY: finished, executed 7 replication requests, 0 charts pending replication"
time=2024-02-10T12:54:22.525+00:00 comm=netdata source=daemon level=info tid=301 thread=REPLAY[1] msg="REPLICATION SUMMARY: finished, executed 2114 replication requests, 0 charts pending replication"
time=2024-02-10T12:55:24.852+00:00 comm=netdata source=daemon level=info tid=301 thread=REPLAY[1] msg="REPLICATION SUMMARY: finished, executed 575 replication requests, 0 charts pending replication"
time=2024-02-10T12:58:47.106+00:00 comm=netdata source=daemon level=info tid=301 thread=REPLAY[1] msg="REPLICATION SUMMARY: finished, executed 13 replication requests, 0 charts pending replication"
time=2024-02-10T13:03:02.380+00:00 comm=netdata source=daemon level=info tid=193 thread=UV_WORKER[9] msg="DBENGINE: created data file \"/var/cache/netdata/dbengine-tier1/datafile-1-0000000119.ndf\"."
time=2024-02-10T13:03:02.381+00:00 comm=netdata source=daemon level=info tid=193 thread=UV_WORKER[9] msg="DBENGINE: created journal file \"/var/cache/netdata/dbengine-tier1/journalfile-1-0000000119.njf\"."
time=2024-02-10T13:03:02.500+00:00 comm=netdata source=daemon level=info tid=234 thread=UV_WORKER[49] msg="DBENGINE: recalculating tier 1 retention for 189685 metrics starting with datafile 44"
time=2024-02-10T13:03:03.168+00:00 comm=netdata source=daemon level=info tid=234 thread=UV_WORKER[49] msg="DBENGINE: updating tier 1 metrics registry retention for 189685 metrics"
time=2024-02-10T13:03:03.191+00:00 comm=netdata source=daemon level=info tid=234 thread=UV_WORKER[49] msg="DBENGINE: deleting data file '/var/cache/netdata/dbengine-tier1/datafile-1-0000000043.ndf'."
time=2024-02-10T13:03:03.191+00:00 comm=netdata source=daemon level=info tid=234 thread=UV_WORKER[49] msg="DBENGINE: deleting data and journal files to maintain disk quota"
time=2024-02-10T13:03:03.192+00:00 comm=netdata source=daemon level=info tid=234 thread=UV_WORKER[49] msg="DBENGINE: deleted journal file \"/var/cache/netdata/dbengine-tier1/journalfile-1-0000000043.njf\"."
time=2024-02-10T13:03:03.192+00:00 comm=netdata source=daemon level=info tid=234 thread=UV_WORKER[49] msg="DBENGINE: deleted journal file \"/var/cache/netdata/dbengine-tier1/journalfile-1-0000000043.njfv2\"."
time=2024-02-10T13:03:03.907+00:00 comm=netdata source=daemon level=info tid=234 thread=UV_WORKER[49] msg="DBENGINE: deleted data file \"/var/cache/netdata/dbengine-tier1/datafile-1-0000000043.ndf\"."
time=2024-02-10T13:03:03.907+00:00 comm=netdata source=daemon level=info tid=234 thread=UV_WORKER[49] msg="DBENGINE: reclaimed 754260528 bytes of disk space."
time=2024-02-10T13:03:04.033+00:00 comm=netdata source=daemon level=info tid=190 thread=UV_WORKER[8] msg="DBENGINE: indexing file '/var/cache/netdata/dbengine-tier1/journalfile-1-0000000118.njfv2': extents 28582, metrics 190058, pages 1829248"
time=2024-02-10T13:03:04.885+00:00 comm=netdata source=daemon level=info tid=190 thread=UV_WORKER[8] msg="DBENGINE: migrated journal file '/var/cache/netdata/dbengine-tier1/journalfile-1-0000000118.njfv2', file size 102424404"
time=2024-02-10T13:03:08.365+00:00 comm=netdata source=daemon level=info tid=301 thread=REPLAY[1] msg="REPLICATION SUMMARY: finished, executed 2 replication requests, 0 charts pending replication"
time=2024-02-10T13:05:52.625+00:00 comm=netdata source=daemon level=info tid=301 thread=REPLAY[1] msg="REPLICATION SUMMARY: finished, executed 1 replication requests, 0 charts pending replication"
time=2024-02-10T13:06:01.855+00:00 comm=netdata source=daemon level=info errno="4, Interrupted system call" tid=1 thread=netdata msg="SIGNAL: Received SIGTERM. Cleaning up to exit..."
time=2024-02-10T13:06:01.855+00:00 comm=netdata source=daemon level=info tid=1 thread=netdata msg="Shutting down command server."
time=2024-02-10T13:06:01.855+00:00 comm=netdata source=daemon level=info errno="2, No such file or directory" tid=327 thread=DAEMON_COMMAND msg="Shutting down command event loop."
time=2024-02-10T13:06:01.855+00:00 comm=netdata source=daemon level=info tid=327 thread=DAEMON_COMMAND msg="Shutting down command loop complete."
time=2024-02-10T13:06:01.855+00:00 comm=netdata source=daemon level=info tid=1 thread=netdata msg="Command server has stopped."
time=2024-02-10T13:06:01.855+00:00 comm=netdata source=daemon level=info tid=1 thread=netdata msg="NETDATA SHUTDOWN: initializing shutdown with code 0..."
time=2024-02-10T13:06:01.855+00:00 comm=netdata source=daemon level=info tid=1 thread=netdata msg="NETDATA SHUTDOWN: next: create shutdown file"
time=2024-02-10T13:06:01.855+00:00 comm=netdata source=daemon level=info tid=1 thread=netdata msg="NETDATA SHUTDOWN: in       0 ms, create shutdown file - next: dbengine exit mode"
time=2024-02-10T13:06:01.855+00:00 comm=netdata source=daemon level=info tid=1 thread=netdata msg="NETDATA SHUTDOWN: in       0 ms, dbengine exit mode - next: close webrtc connections"
time=2024-02-10T13:06:01.855+00:00 comm=netdata source=daemon level=info tid=1 thread=netdata msg="NETDATA SHUTDOWN: in       0 ms, close webrtc connections - next: disable maintenance, new queries, new web requests, new streaming connections and aclk"
time=2024-02-10T13:06:01.856+00:00 comm=netdata source=daemon level=info tid=1 thread=netdata msg="NETDATA SHUTDOWN: in       0 ms, disable maintenance, new queries, new web requests, new streaming connections and aclk - next: stop replication, exporters, health and web servers threads"
time=2024-02-10T13:06:01.856+00:00 comm=netdata source=daemon level=info tid=1 thread=netdata msg="SERVICE CONTROL: waiting for the following 65 services [ WEB_SERVER HEALTH ] to exit: "
time=2024-02-10T13:06:02.859+00:00 comm=netdata source=daemon level=info tid=1 thread=netdata msg="SERVICE CONTROL: waiting for the following 65 services [ WEB_SERVER HEALTH ] to exit: "
time=2024-02-10T13:06:02.932+00:00 comm=netdata source=daemon level=warning tid=299 thread=ACLK_MAIN msg="ACLK link is down"
time=2024-02-10T13:06:03.862+00:00 comm=netdata source=daemon level=info tid=1 thread=netdata msg="SERVICE CONTROL: waiting for the following 65 services [ WEB_SERVER HEALTH ] to exit: "
time=2024-02-10T13:06:04.865+00:00 comm=netdata source=daemon level=info tid=1 thread=netdata msg="SERVICE CONTROL: the following 65 service(s) [ WEB_SERVER HEALTH ] take too long to exit: 'HEALTH' (293), 'WEB[1]' (298), 'WEB[2]' (359), 'WEB[3]' (360), 'WEB[4]' (361), 'WEB[5]' (362), 'WEB[6]' (363), 'WEB[7]' (364), 'WEB[8]' (365), 'WEB[9]' (366), 'WEB[10]' (367), 'WEB[11]' (369), 'WEB[12]' (371), 'WEB[13]' (373), 'WEB[14]' (376), 'WEB[15]' (378), 'WEB[16]' (380), 'WEB[17]' (383), 'WEB[18]' (384), 'WEB[19]' (385), 'WEB[20]' (387), 'WEB[21]' (388), 'WEB[22]' (389), 'WEB[23]' (391), 'WEB[24]' (394), 'WEB[25]' (396), 'WEB[26]' (398), 'WEB[27]' (400), 'WEB[28]' (401), 'WEB[29]' (402), 'WEB[30]' (403), 'WEB[31]' (404), 'WEB[32]' (406), 'WEB[33]' (407), 'WEB[34]' (
408), 'WEB[35]' (410), 'WEB[36]' (411), 'WEB[37]' (412), 'WEB[38]' (413), 'WEB[39]' (414), 'WEB[40]' (415), 'WEB[41]' (416), 'WEB[42]' (417), 'WEB[43]' (418), 'WEB[44]' (419), 'WEB[45]' (421), 'WEB[46]' (422), 'WEB[47]' (423), 'WEB[48]' (424), 'WEB[49]' (425), 'WEB[50]' (426), 'WEB[51]' (427), 'WEB[52]' (428), 'WEB[53]' (430), 'WEB[54]' (431), 'WEB[55]' (433), 'WEB[56]' (434), 'WEB
[57]' (435), 'WEB[58]' (436), 'WEB[59]' (437), 'WEB[60]' (438), 'WEB[61]' (439), 'WEB[62]' (441), 'WEB[63]' (442), 'WEB[64]' (443); giving up on them..."
time=2024-02-10T13:06:04.865+00:00 comm=netdata source=daemon level=info tid=1 thread=netdata msg="NETDATA SHUTDOWN: in    3009 ms, (TIMEOUT) stop replication, exporters, health and web servers threads - next: stop collectors and streaming threads"
time=2024-02-10T13:06:04.865+00:00 comm=netdata source=daemon level=info tid=291 thread=P[timex] msg="cleaning up..."
time=2024-02-10T13:06:04.865+00:00 comm=netdata source=collector level=info tid=304 thread=P[tc] msg="cleaning up..."
time=2024-02-10T13:06:04.865+00:00 comm=netdata source=collector level=info tid=304 thread=P[tc] msg="TC: killing with SIGTERM tc-qos-helper process 38788"
time=2024-02-10T13:06:04.865+00:00 comm=netdata source=daemon level=info tid=331 thread=PD[systemd-jour msg="PLUGINSD: 'host:netdata01', killing data collection child process with pid 354"
time=2024-02-10T13:06:04.865+00:00 comm=netdata source=daemon level=info tid=316 thread=PD[debugfs] msg="PLUGINSD: 'host:netdata01', killing data collection child process with pid 36576"
time=2024-02-10T13:06:04.865+00:00 comm=netdata source=collector level=info tid=308 thread=P[diskspace] msg="cleaning up..."
time=2024-02-10T13:06:04.865+00:00 comm=netdata source=daemon level=info tid=294 thread=PLUGINSD msg="PLUGINSD: cleaning up..."
time=2024-02-10T13:06:04.865+00:00 comm=netdata source=daemon level=info tid=316 thread=PD[debugfs] msg="PLUGINSD: 'host:netdata01', waiting for data collection child process pid 36576 to exit..."
time=2024-02-10T13:06:04.865+00:00 comm=netdata source=collector level=info tid=349 thread=STATSD_IN[1] msg="cleaning up..."
time=2024-02-10T13:06:04.865+00:00 comm=netdata source=daemon level=info tid=294 thread=PLUGINSD msg="PLUGINSD: 'host:netdata01', stopping plugin thread: plugin:go.d"
time=2024-02-10T13:06:04.865+00:00 comm=netdata source=collector level=info tid=309 thread=P[proc] msg="cleaning up..."
time=2024-02-10T13:06:04.865+00:00 comm=netdata source=collector level=info tid=320 thread="P[diskspace slo" msg="cleaning up..."
time=2024-02-10T13:06:04.865+00:00 comm=netdata source=collector level=info tid=304 thread=P[tc] msg="TC: waiting for tc plugin child process pid 38788 to exit..."
time=2024-02-10T13:06:04.865+00:00 comm=netdata source=daemon level=info tid=34299 thread=SNDR[dcv131-04] node=dcv131-04 src_capabilities="VCAPS HLABELS CLAIM CLABELS FUNCTIONS REPLICATION BINARY INTERPOLATED IEEE754 ML SLOTS ZSTD " dst_transport=https dst_ip=172.31.100.98 dst_port=19999 msg="STREAM dcv131-04 [send]: sending thread exits DISCONNECTED RECEIVER LEFT"
time=2024-02-10T13:06:04.865+00:00 comm=netdata source=collector level=info tid=292 thread=P[idlejitter] msg="cleaning up..."
time=2024-02-10T13:06:04.865+00:00 comm=netdata source=collector level=info tid=317 thread="P[proc netdev]" msg="cleaning up..."
time=2024-02-10T13:06:04.865+00:00 comm=netdata source=collector level=info tid=296 thread=STATSD_FLUSH msg="cleaning up..."
time=2024-02-10T13:06:04.869+00:00 comm=netdata source=collector level=info tid=296 thread=STATSD_FLUSH msg="STATSD: data collection thread 1 found stopped."
time=2024-02-10T13:06:04.869+00:00 comm=netdata source=collector level=info tid=296 thread=STATSD_FLUSH msg="STATSD: closing sockets..."
time=2024-02-10T13:06:04.869+00:00 comm=netdata source=collector level=info tid=296 thread=STATSD_FLUSH msg="STATSD: cleanup completed."
time=2024-02-10T13:06:04.865+00:00 comm=netdata source=daemon level=info tid=302 thread=PD[apps] msg="PLUGINSD: 'host:netdata01', killing data collection child process with pid 305"
```

**Comment by CreeperFace00** [comment]
Yeah this continues to be an issue, I'm going to see if I can generate a coredump from the agent when it's in this weird state so we can try and figure out what's wrong.
@ilyam8 can we get this issue reopened?

**Comment by ilyam8** [comment]
We can't, because we don't know what the OP issue was. Update to v1.44.3 (or better latest nightly) and try to get the coredump if possible.

**Comment by CreeperFace00** [comment]
Okay I ran gdb against the hung process. https://gist.github.com/CreeperFace00/3c6b31df834fa2810c8b2b6803339d2c
Hopefully this can at least provide a place to start looking.



I can't seem to get Netdata to compile with debug symbols automatically when it updates. Any idea how I could do that? I tried setting `CFLAGS=` in the .environment file, but it seems to get overwritten after every update.

**Comment by CreeperFace00** [comment]
I've kind of given up on this being fixed. And this problem is quite severe and occurs several times a day.
If anyone else is having this issue I recommend setting up a systemd timer/service to check if Netdata has entered zombie mode and requires being beaten with a stick to work again.

Here's what I'm using:
`/opt/fix-netdata.sh`
```
#!/bin/bash

# Netdata webui
URL="http://localhost:19999"

# The Stick
COMMAND="killall -9 netdata; systemctl restart netdata"

# Timeout duration in seconds
TIMEOUT_DURATION=10

# Check interval (in seconds)
CHECK_INTERVAL=30

# Number of seconds to wait, since Netdata might be updating.
ERROR_THRESHOLD=120

# Error counter
error_duration=0

while true; do
# Check if Netdata is responsive
if ! curl -s --max-time $TIMEOUT_DURATION $URL > /dev/null; then
echo "Netdata may be in zombie mode. Starting timer."
((error_duration+=CHECK_INTERVAL))

if [ $error_duration -ge $ERROR_THRESHOLD ]; then
echo "Netdata hasn't spoken to me in 2 minutes. Grabbing the stick..."
$($COMMAND)
error_duration=0
fi
else
error_duration=0
fi

sleep $CHECK_INTERVAL
done
```

`/etc/systemd/system/fix-netdata.service`
```
[Unit]
Description=Unbreak Netdata when it's sad

[Service]
Type=simple
ExecStart=/opt/fix-netdata.sh
User=root
```

`/etc/systemd/system/fix-netdata.timer`
```
[Unit]
Description=Periodically check if Netdata is sad

[Timer]
OnBootSec=5min
OnUnitActiveSec=30s
Unit=fix-netdata.service

[Install]
WantedBy=timers.target
```

Then enable
```
sudo systemctl daemon-reload
sudo systemctl enable --now fix-netdata.timer
```

I'm a bit miffed this is necessary, but I'm not a paying customer, and likely never will be :disappointed:

**Comment by AlwinAntreich** [comment]
I can only add that the issue didn't come up since my last post. Though I removed the stored metrics on one of my parents.

**Comment by stelfrag** [comment]
I am reopening this since we are still investigating

**Comment by AlwinAntreich** [comment]
One of our netdata parents is still crashing with the below snippet reoccurring. (netdata v1.44.3)
```
time=2024-04-04T11:51:19.066+00:00 comm=netdata source=daemon level=alert tid=941 thread=RCVR[vm201] node=vm201 instance=prometheus_ceph_ceph-mgr_prometheus_plugin_croit.ceph_objecter_0x7f42c00791c0_op_rmw-instance_id_4409481650 context=prometheus.ceph_ceph-mgr_prometheus_plugin_croit.ceph_objecter_0x7f42c00791c0_op_rmw src_transport=https src_ip=172.31.100.98 src_port=47268 src_capabilities="VCAPS HLABELS CLAIM CLABELS FUNCTIONS REPLICATION BINARY INTERPOLATED IEEE754 ML SLOTS ZSTD " request="'CHART' 'SLOT:#BdQ' 'prometheus_ceph_ceph-mgr_prometheus_plugin_croit' 'ceph_pg_deep-pool_id_40_18' 'PG deep per pool' 'deep' 'ceph_pg' 'prometheus.ceph_ceph-mgr_prometheus_plugin_croit.ceph_pg_deep' 'line' '70000' '15' '   ' 'go.d' 'prometheus'" msg="METRIC: refcount is 0 (zero or negative) during release"
/usr/sbin/netdata(+0x9bf20)[0x556f2f3cff20]
/usr/sbin/netdata(+0x29447c)[0x556f2f5c847c]
/usr/sbin/netdata(+0x166de6)[0x556f2f49ade6]
/usr/sbin/netdata(+0x167c98)[0x556f2f49bc98]
/usr/sbin/netdata(+0x8958a)[0x556f2f3bd58a]
/usr/sbin/netdata(+0x89b1f)[0x556f2f3bdb1f]
/usr/sbin/netdata(+0x93c0b)[0x556f2f3c7c0b]
/usr/sbin/netdata(+0x179d8a)[0x556f2f4add8a]
/usr/sbin/netdata(+0x8958a)[0x556f2f3bd58a]
/usr/sbin/netdata(+0x897d2)[0x556f2f3bd7d2]
/usr/sbin/netdata(+0x8a2a1)[0x556f2f3be2a1]
/usr/sbin/netdata(+0x8b949)[0x556f2f3bf949]
/usr/sbin/netdata(+0x17b92e)[0x556f2f4af92e]
/usr/sbin/netdata(+0x13aa66)[0x556f2f46ea66]
/usr/sbin/netdata(+0x2b5e1c)[0x556f2f5e9e1c]
/usr/sbin/netdata(+0x2b7219)[0x556f2f5eb219]
/usr/sbin/netdata(+0xb1c03)[0x556f2f3e5c03]
/lib/x86_64-linux-gnu/libc.so.6(+0x89134)[0x7fd8c0e1b134]
/lib/x86_64-linux-gnu/libc.so.6(+0x1097dc)[0x7fd8c0e9b7dc]
```
The restarts are very sporadic.
```
-rw-r--r--  1 root root 4.3M Feb 10 14:32 netdata-1707571924.log
-rw-r--r--  1 root root 4.3M Feb 10 14:33 netdata-1707571981.log
-rw-r--r--  1 root root  13M Feb 12 18:27 netdata-1707758821.log
-rw-r--r--  1 root root 484K Apr  2 11:48 netdata-1712051281.log
-rw-r--r--  1 root root 112K Apr  4 13:54 netdata-1712231641.log
```
In February I removed the `netdatacache` & `netdatalib` volumes from this particular parent. The other parent, which doesn't crash, still has the original volumes.

**Comment by hugovalente-pm** [comment]
@AlwinAntreich would you be able to test this out using the latest stable version `1.45.2`? There have been several bugs fixed that were released recently.

**Comment by AlwinAntreich** [comment]
> @AlwinAntreich would you be able to test this out using the latest stable version `1.45.2`? There have been several bugs fixed that were released recently.
Running since this morning. I'll update the issue when (if it should) it happens again.

Would it help to run the debug version of the container?

**Comment by hugovalente-pm** [comment]
thanks for asking @AlwinAntreich but it shouldn't be needed
