### ISSUE TITLE
Installing and updating netdata to stable releases only (v2)

### ISSUE THREAD

**Issue by DavidS3141** [netdata/netdata#4763]
This feature request is basically a duplicate of #2479 (same title), but I could not reopen that issue and was not sure if anyone would see it. Feel free to close this and reopen #2479 as I documented this post there as well.
##### Feature idea summary
Currently the `kickstart.sh` installs the current repo state with all the latest bugs. You have released versions. Would it be possible to add a version flag to this installer script for those who need the hopefully more reliable released versions? I know that I could to it by hand, but this seems like a very common feature for other projects which netdata is missing. Ideally the cron updater script would have also this flag and only update if there is a new release, otherwise one would have to update manually.

##### Expected behavior
Default:
```bash
bash <(curl -Ss https://my-netdata.io/kickstart.sh)
```
or
```bash
bash <(curl -Ss https://my-netdata.io/kickstart.sh) --version latest
```
Install the released version 1.11.1 without auto-updates:
```bash
bash <(curl -Ss https://my-netdata.io/kickstart.sh) --no-updates --version 1.11.1
```
Install the latest released version (keyword) w/o auto-updates:
```bash
bash <(curl -Ss https://my-netdata.io/kickstart.sh) --no-updates --version release
```
Install the latest release with auto-updates turned on, but because the version flag is given, the behavior of the auto-updates should be adapted such that only released versions are updated (otherwise it would immediately overwrite):
```bash
bash <(curl -Ss https://my-netdata.io/kickstart.sh) --version release
```

**Comment by ktsaou** [comment]
Hi, thanks!

We are currently trying to release our own binary packages for all major distros. Once we have released them, let's discuss this again. I think this won't be needed.

**Comment by DavidS3141** [comment]
Ok thanks. Do you happen to have a time frame within all the binary packages are going to be released? I am asking because #2479 was answered similarly and is already more than a year old.

Like I wrote in #2479, I would considering doing a PR for this if the binary packages are more than 2-3 months into the future.

**Comment by paulfantom** [comment]
We currently plan to move from using git to use tarballs for releases. After that implementing this feature will be much simpler, but I still don't know if we want to go down this road. Preferably I would like not to implement new features in installation and/or upgrader scripts to allow faster and easier transition.

**Comment by DavidS3141** [comment]
Understood, thanks for the replies.
