### ISSUE TITLE
Changing Node URLs

### ISSUE THREAD

**Issue by MuffinMedic** [netdata/netdata#6380]
Using Debian 9, installed through the kickstart script, on the latest version as of an hour ago.

I'm trying to setup the Netdata Console and was able to log in successfully. However, I run my nodes behind Nginx in a subdirectory. How do I tell Netdata that the Node URL contains that subdirectory? I couldn't find anything in the netdata.cloud documentation.

Thanks.

**Comment by gpapamathND** [comment]
Hi @MuffinMedic for the current version of the cloud solution, the following steps are required:

1) Visit your netdata console for every Node URL (via web browser) and Sign-in for each node individually by using the same method & account (i.e. Google, Github, email) 
2) Once you have been signed-in successfully, each node URL will be stored in the cloud registry and be linked to your account.
3) Visit again the "Nodes" screen and all your "registered" nodes will be there.

We understand that this approach is not very convenient, hence we are planning to change it (#4771)

In case you are facing troubles with the registration of your Nodes, please post here.

**Comment by MuffinMedic** [comment]
Hi @gpapamathND 

Thank you. The node is showing up in my console but it is showing up incorrectly. My site url IS "mysite.com/netdata" but it is being listed in the console as "mysite.com". I followed the instructions [here](https://docs.netdata.cloud/docs/running-behind-nginx/) for running it being NGINX.

**Comment by cakrit** [comment]
We did have a problem with these a while back, but it was fixed. I'll repeat the test and get back shortly...

**Comment by cakrit** [comment]
Nope, I see it working very well, with an even more complex set up (see below for the config). The 4th URL was just added now, via the test I did.

![Screenshot from 2019-07-03 14-04-06](https://user-images.githubusercontent.com/43294513/60590184-a679c280-9d9b-11e9-82d6-9623155272a3.png)

```
http {
upstream backend-server1 {
    server localhost:19999;
    keepalive 64;
}
upstream backend-server2 {
    server chris-msi:19999;
    keepalive 64;
}

server {

    # the virtual host name of this subfolder should be exposed
    server_name netdata.mydomain.com;

    error_log /var/log/nginx/netdata.mydomain.com.error.log;
    auth_basic "Restricted";
    auth_basic_user_file /etc/nginx/.htpasswd;

    location ~ /netdata/(?<behost>.*)/(?<ndpath>.*) {
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_http_version 1.1;
        proxy_pass_request_headers on;
        proxy_set_header Connection "keep-alive";
        proxy_store off;
        proxy_pass http://backend-$behost/$ndpath$is_args$args;

        gzip on;
        gzip_proxied any;
        gzip_types *;
    }

    # make sure there is a trailing slash at the browser
    # or the URLs will be wrong
    location ~ /netdata/(?<behost>.*) {
        return 301 /netdata/$behost/;
    }

}
```

**Comment by MuffinMedic** [comment]
Thanks. I still can't seem to get it to work. The node continues to be registered at mysite.com instead of mysite.com/netdata/

Do I need to make any changes in the netdata config?

**Comment by ilyam8** [comment]
Could you post you nginx config?

**Comment by MuffinMedic** [comment]
```
server {
        listen 443 ssl;

        root /var/www/site.net/system;

        server_name system.site.net;

        ssl_certificate /etc/nginx/cert/site.net/fullchain.pem;
        ssl_certificate_key /etc/nginx/cert/site.net/privkey.pem;
        ssl_trusted_certificate /etc/nginx/cert/site.net/fullchain.pem;

        include /etc/nginx/includes/ssl.conf;

        location ~ /netdata/(?<ndpath>.*) {
                proxy_redirect off;
                proxy_set_header Host $host;

                proxy_set_header X-Forwarded-Host $host;
                proxy_set_header X-Forwarded-Server $host;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_http_version 1.1;
                proxy_pass_request_headers on;
                proxy_set_header Connection "keep-alive";
                proxy_store off;
                proxy_pass http://127.0.0.1:19999/$ndpath$is_args$args;

                gzip on;
                gzip_proxied any;
                gzip_types *;
        }
```

**Comment by cakrit** [comment]
Can you put here a screenshot like the following? I want to see the URLs https://system.site.net/netdata on the top and what is shown on the expanded nodes menu for this host. We should see https://system.site.net/netdata appearing there as well.

![Screenshot from 2019-07-03 17-54-59](https://user-images.githubusercontent.com/43294513/60606792-434c5800-9dbc-11e9-9cda-62c89c8c97a1.png)

**Comment by MuffinMedic** [comment]
Doesn't seem to be working. Just says `Loading, please wait...` endlessly.

**Comment by cakrit** [comment]
Not good, but at least we found something to continue the debugging. 
- You are signed in and on the top right you see your name, correct?
- You haven't set up a private registry, correct?

Open your browser's console and let's see what errors you get in the console, plus any timeouts from the network view. 

You could try with the cosole open to clear cache and delete all local storage, in case there's any garbage there, but I'd rather figure out the root cause first.

**Comment by MuffinMedic** [comment]
> * You are signed in and on the top right you see your name, correct?

I am signed in and see my e-mail address.

> * You haven't set up a private registry, correct?

Correct. No changes to netdata's default config.

> Open your browser's console and let's see what errors you get in the console, plus any timeouts from the network view.

```
[Error] Unhandled Promise Rejection: TypeError: null is not an object (evaluating 'registryAgents.concat')
	syncAgents (main.js:4999)
	(anonymous function) (main.js:5081)
	promiseReactionJob
```

No timeouts that I can see.

**Comment by cakrit** [comment]
@Vlegakis, it looks like in this user's case, synchronization with the cloud failed AND currentAgent is null. The parameters should be looking something like the following, but in this case, they definitely don't:
![Screenshot from 2019-07-06 13-06-12](https://user-images.githubusercontent.com/43294513/60755380-33688a00-9fef-11e9-888a-798f95d5ba9d.png)

**Comment by VLegakis** [comment]
Hello @MuffinMedic,
The issue sounds like a sign-in issue. Before moving could we please make sure you sign-in successfully? 
So you login by which method (Github, Google etc..) and in which browser? After signin your name shows up correctly on the top right? (attached screenshot)
![Screenshot 2019-07-08 at 12 49 25](https://user-images.githubusercontent.com/861415/60801003-d996ca00-a17e-11e9-8e7f-9f2d3de97890.png)

Then if we answer these could you also please send us your local storage details? That is in you browser:
1) Open developer tools,
2) Go to your local storage (e.g for Chrome this is under Application tab -> Local Storage
3) Filter the relevant values by cloud. I attach here a screenshot.
<img width="774" alt="Screenshot 2019-07-08 at 12 42 30" src="https://user-images.githubusercontent.com/861415/60801039-ea474000-a17e-11e9-9a65-031f1f3a75e1.png">

**Comment by gpapamathND** [comment]
Hi @MuffinMedic kindly, any updates on this ?

**Comment by MuffinMedic** [comment]
> Hi @MuffinMedic kindly, any updates on this ?

Will post an update as soon as I have access to a computer again.

**Comment by cakrit** [comment]
Closing due to lack of response, please try with the latest version and comment here if the issue persists.
