### ISSUE TITLE
Registry not working

### ISSUE THREAD

**Issue by ondrousn** [netdata/netdata#6855]
Hello, I have set up local registry following your guide.
I tried using one registry and one server to advertise to the registry.

After restarting the service on both servers, there is following error in "My nodes" section in the netdata dashboard: "Failed to contact the registry".

After opening developer console, there is a following error: "ERROR 410: Netdata registry ACCESS failed: http://10.223.70.19:19999". 

What can I please do to get it working?

**Comment by cakrit** [comment]
What's your netdata version? We had an issue with the registry that was fixed in v1.17.0 with PR #6714.

**Comment by ondrousn** [comment]
@cakrit I have uninstalled the old version and installed the most recent one from binary on all servers, however the error still occurs.

**Comment by cakrit** [comment]
Please post here (or email to chris@netdata.cloud if it contains sensitive info) the sections `[web]` and `[registry]` from http://10.223.70.19:19999/netdata.conf and the same from the other server.

**Comment by cakrit** [comment]
I saw the settings, there's nothing wrong with them. 
I'll set it up locally to see if I can replicate. In the meantime, I'd appreciate a more detailed request/response list from your "network" view in your browser's debug console. 
By the way, there's no proxy involved, right? I mean this IP:Port is directly accessible from your browser?

**Comment by cakrit** [comment]
Set it up. v1.17.1 doesn't have any issues. Please check your netdata version from the UI and let me know what you see. When you say "from binary", do you mean our own DEB/RPM distros in package cloud, the `kickstart-static64.sh` or a binary distro that's not maintained by us? Because 3rd party distributions take a while to get updated to the latest version.

**Comment by ondrousn** [comment]
The version is 1.17.1. Netdata was installed using "netdata-installer.sh" from your github repo.

Here is the developer console log:

`dashboard.js:1567 localStorage: LOADED UNDEFINED "options.destroy_on_hide" as value undefined of type undefined
dashboard.js:10009 ACCESS smbhte01.mbs.skoda.vwg5t https://cdh-adm.mbs.skoda.vwg5t:7183/netdata/
VM18:1 Mixed Content: The page at 'https://cdh-adm.mbs.skoda.vwg5t:7183/netdata/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://10.223.70.19:19999/api/v1/registry?action=access&machine=c024d524-d87b-11e9-901f-b49691079e04&name=smbhte01.mbs.skoda.vwg5t&url=https%3A%2F%2Fcdh-adm.mbs.skoda.vwg5t%3A7183%2Fnetdata%2F&_=1568705668937'. This request has been blocked; the content must be served over HTTPS.
(anonymous) @ VM18:1
dashboard.js:602 ERROR 410: Netdata registry ACCESS failed: http://10.223.70.19:19999
main.js:720 Rendering my-netdata menu from registry
main.js:720 Rendering my-netdata menu from registry
`

**Comment by cakrit** [comment]
Well, that makes sense then, you're running netdata behind a proxy and also need the registry to be in https. You'll need to configure `registry to announce` to also have a URL that the proxy will be able to handle. 

I believe you need `registry to announce = https://cdh-adm.mbs.skoda.vwg5t:7183/netdata`, (assuming that's the host with IP 10.223.70.19). I haven't tried a private registry with a subpath via a proxy before, so I'm not 100% sure if it needs a `/` at the end or not, but you'll be able to tell from the request URI and the response.

**Comment by ondrousn** [comment]
Thanks, that is a step forward my goal. I changed config on registry server and two non-registry servers and restarted the netdata service.

Expected result is to see three servers in netdata dashboard dropdown menu, but now it looks like this: [https://imgur.com/a/Qg217mS](Netdata dashboard)

**Comment by cakrit** [comment]
Did you visit the other servers as well? As soon as you bring up their UI, you should see their entries added. Worst case, a reload should show them. If they don't get added, let's see the console messages for the ones that you don't see.

**Comment by ondrousn** [comment]
Everything works like a char, I had no idea there was need to visit the UI of other servers to get it working.

Thanks you so much for assistance, you are very kind.
