### ISSUE TITLE
Notifications use goto-host-from-alarm even if private registry is in use

### ISSUE THREAD

**Issue by tctovsli** [netdata/netdata#6975]
##### Bug report summary
When clicking the alarm in RocketChat, the URL is in this format: `http://netdata:19999/goto-host-from-alarm.html?host=host.example.com`. 
This result in a message "Sorry... your account is not linked to a netdata server named: proxy01.example.com", unless I have already viewed the slave in netdata (so that it is listed under "My nodes"). 
The slave is listed under "Databases streamed to this agent", but only slaves that have been viewed in the GUI is listed under "My nodes".

##### OS / Environment
RHEL 7.7
I have configured my netdata installation to have one master where all agents stream to. This master is also set to be the private registry for all nodes.

This is from netdata.conf on the master (hostname `netdata`):
```
[registry]
        enabled = yes
        # registry db directory = /var/lib/netdata/registry
        # netdata unique id file = /var/lib/netdata/registry/netdata.public.unique.id
        # registry db file = /var/lib/netdata/registry/registry.db
        # registry log file = /var/lib/netdata/registry/registry-log.db
        # registry save db every new entries = 1000000
        # registry expire idle persons days = 365
        # registry domain =
        registry to announce = http://netdata:19999
```
The same settings are applied to all the slaves.

##### Netdata version (ouput of `netdata -V`)
master is version v1.17.1-138-nightly
agent is version v1.17.1
##### Component Name
notification

##### Steps To Reproduce
1. Install netdata master to receive stream from slaves.
2. Point the registry on the master to itself
3. Set a slave to stream to the master and to use the master as registry
4. Configure alarm notifications
5. Click an alarm-link. It will take you to goto-host-from-alarm, which seems to check the registry if the host is known. If the host has not been viewed in netdata, it seems to be unknown and the error occurs.
##### Expected behavior
It is expected that the URL redirects to the host in netdata directly.

**Comment by cakrit** [comment]
This is the way the netdata registry was always designed to work, but this is a great suggestion and I do agree that it's a bug, but for a very specific use case:
If an alarm for a slave is produced by the master, then the `host` that we send to `goto-host-from-alarm` is wrong. In the example below, the master `chris-msi` has dispatched an alarm notification for the slave `chris-ubuntu-tralala`.:
```
http://chris-msi:19999/goto-host-from-alarm.html?host=chris-ubuntu-tralala&chart=example.random&family=random&alarm=example1&alarm_unique_id=1569843380&alarm_id=1569843250&alarm_event_id=3&alarm_when=1569843320
```
The problem with this is that instead of asking the redirect to go to `chris-msi:19999/host/chris-ubuntu-tralala`, we are asking it to send us to `http://chris-ubuntu-tralala:19999` We don't even know if that is a valid URL, so we're not doing the right thing here.

We know that we can access their UI at `masterhost:port/host/slavehost`. So we need to the following (again, only if the master is dispatching the notification for the slave):
- Send the master's URL, instead of the slave's. 
- Add a parameter to tell alarm-notify.sh that we are actually notifying on behalf of a slave, e.g. `slave-host=chris-ubuntu-tralala`
- Ensure that both `goto-host-from-alarm` and the cloud `redirect` pages construct the URL `master-host:master-port/host/slave-host` appropriately
- Ensure that the solution still works behind a reverse proxy that has a subpath after the host. e.g. `master-host:master-port/netdata/host/slave-host`

This is a very nice mini-project.

**Comment by thiagoftsm** [comment]
Thank you @tctovsli for your suggestion!
This week I am working with streams and I will study the way we can bring a PR to fix this bug.

**Comment by cakrit** [comment]
@thiagoftsm I don't believe we fixed this one, right?

**Comment by thiagoftsm** [comment]
You are right @cakrit , I moved this issue to `Ready for dev` for we plan the its development.

**Comment by xPaw** [comment]
This is still an issue. By default clicking a row in alert logs goes to Netdata's cloud promotion page asking me to sign up.

Changing registry url gets me to "Sorry... your account is not linked to a netdata server named:" page.

**Comment by cakrit** [comment]
I don't see it, let's see what you're not doing correctly.
You need at least one netdata instance configured with :
```
[registry]
  enabled = yes
```
That's your private registry server, let's say its URL is http://server1:19999
Then, every netdata instance you have, including server1, should have:

```
[registry]
  registry to announce = http://server1:19999
```
Restart after the config.
Then, you visit all your netdata instances one by one, so that your private registry learns them for the first time. 
You can verify it knows them, by checking the "Visited" nodes list on the left side (it shows up when you click the hamburger icon at the top).

After that's done, you will be able to click on an alarm log entry on any of them and it will send you to the right place, by communicating with your registry on server1.

**Comment by xPaw** [comment]
Adding `enabled = yes` was the fix yeah. But why is netdata not aware that the log comes from the same instance and can't just navigate directly on the already open page?

I don't have multiple instances, and I don't want the cloud/registry stuff.

**Comment by cakrit** [comment]
Perfectly valid question actually, I don't see any reason why we need to jump through hoops to just scroll down to the correct chart.  @thiagoftsm was there a technical reason we chose to do it this way? We're not talking about the links in the alarm notifications of course, just the ones on the alarm logs entries.

**Comment by thiagoftsm** [comment]
Hello everyone,

@cakrit  there is not any special reason to redirect to cloud instead to go direct to the chart on the same page, but I request @jacekkolasa or @VLegakis to fix this, because they have a better JS knowledge to close the box and go to the chart direct, I am not sure about the necessary methods to call.

**Comment by cakrit** [comment]
High priority, let's get this working soon.
