### ISSUE TITLE
Netdata Cloud node unreachable in War Room

### ISSUE THREAD

**Issue by ThoSap** [netdata/netdata#8966]
##### Bug report summary
Netdata Cloud cannot connect to a CentOS 8 (8.1.1911) node behind NGINX reverse proxy and Cloudflare.
Netdata was fresh installed using:
```
bash <(curl -Ss https://my-netdata.io/kickstart-static64.sh) --stable-channel --disable-telemetry
```

![image](https://user-images.githubusercontent.com/6555967/81579640-adeefc80-93ac-11ea-96fb-e69158da4162.png)
```
Connection Problem
This agent cannot connect to Netdata Cloud. Please talk to system's administrator for more information.
```
![image](https://user-images.githubusercontent.com/6555967/81585634-ba775300-93b4-11ea-89cc-84a6b0506351.png)

##### OS / Environment

```
Linux myhost.example.com 4.18.0-147.8.1.el8_1.x86_64 #1 SMP Thu Apr 9 13:49:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
/etc/centos-release:CentOS Linux release 8.1.1911 (Core)
/etc/os-release:NAME="CentOS Linux"
/etc/os-release:VERSION="8 (Core)"
/etc/os-release:ID="centos"
/etc/os-release:ID_LIKE="rhel fedora"
/etc/os-release:VERSION_ID="8"
/etc/os-release:PLATFORM_ID="platform:el8"
/etc/os-release:PRETTY_NAME="CentOS Linux 8 (Core)"
/etc/os-release:ANSI_COLOR="0;31"
/etc/os-release:CPE_NAME="cpe:/o:centos:centos:8"
/etc/os-release:HOME_URL="https://www.centos.org/"
/etc/os-release:BUG_REPORT_URL="https://bugs.centos.org/"
/etc/os-release:
/etc/os-release:CENTOS_MANTISBT_PROJECT="CentOS-8"
/etc/os-release:CENTOS_MANTISBT_PROJECT_VERSION="8"
/etc/os-release:REDHAT_SUPPORT_PRODUCT="centos"
/etc/os-release:REDHAT_SUPPORT_PRODUCT_VERSION="8"
/etc/os-release:
/etc/redhat-release:CentOS Linux release 8.1.1911 (Core)
/etc/system-release:CentOS Linux release 8.1.1911 (Core)
```

##### Netdata version

 netdata v1.22.0

##### Component Name

Netdata Cloud
ACLK_Main

##### Steps To Reproduce

1. Install CentOS 8 (8.1.1911)
2. Install Docker 19.03.8
https://docs.docker.com/engine/install/centos/
https://www.liquidweb.com/kb/how-to-install-docker-on-centos-8/
2.1. Temporarily disable firewalld as Docker is not officially supported yet for CentOS 8 and Fedora 32 (does not support nftables and cgroup v2 yet)
```sudo systemctl disable firewalld```
2.2. Stop firewalld 
```sudo systemctl stop firewalld```
2.3. Reload systemd daemon
```sudo systemctl daemon-reload```
2.3 Restart docker daemon
```sudo systemctl restart docker```
3. Install Netdata using:
```bash <(curl -Ss https://my-netdata.io/kickstart-static64.sh) --stable-channel --disable-telemetry```
4. Run NGINX reverse proxy using Docker and docker-compose
Using the following image:
https://hub.docker.com/layers/nginx/library/nginx/1.17.10/images/sha256-d930948e1f4cc8844d1ebd47fae24fa10d2ffca7fe68bced431354c1b03399c7?context=explore
5. Setup Netdata behind NGINX (As a subfolder to an existing virtual host)
https://learn.netdata.cloud/docs/agent/running-behind-nginx/#as-a-subfolder-to-an-existing-virtual-host
5.1. Test configuration
```docker exec -it nginx nginx -t```
Was successfull.
5.2. Reload new NGINX virtual host config
```docker exec -it nginx nginx -s reload```
6. Added Netdata node to Netdata Cloud Space and War Room
```
cd /opt/netdata/bin/
sudo ./netdata-claim.sh -token=MY_SECRET_TOKEN -rooms=MY_ROOM -url=https://app.netdata.cloud
```
Node appeared in War Room but is Unreachable

7. Access Netdata over Cloudflare CNAME with Cloudlfare proxy enabled (disabled bot detection and JS and normal Challenge for this CNAME, so this can't be it)
_Netdata works as expected but this error from above appears_
8. Access Netdata over LAN
_Netdata works as expected but this error from above appears_
9. Checked troubleshooting guide
https://learn.netdata.cloud/docs/agent/claim/#troubleshooting
```
{
"cloud-enabled": true,
"cloud-available": true,
"agent-claimed": true,
"aclk-available": false
}
```
10. Checked output from /opt/netdata/var/log/netdata/error.log
**Log snippet as gist: https://gist.github.com/ThoSap/f5647ba35097c12dcb5f3b92ef457ac4**

##### Expected behavior

The Node should be reachable in the War Room

**Comment by ThoSap** [comment]
The communication between NGINX and Netdata is not encrypted.
The connection from NGINX to LAN or Cloudflare is HTTPS only using a Let’s Encrypt certificate.

I also tried to install libwebsockets as it is not installed by default on CentOS 8:
```
$ sudo dnf install libwebsockets
$ sudo yum info libwebsockets
Installed Packages
Name         : libwebsockets
Version      : 4.0.1
Release      : 2.el8
Architecture : x86_64
Size         : 809 k
Source       : libwebsockets-4.0.1-2.el8.src.rpm
Repository   : @System
From repo    : epel
Summary      : A lightweight C library for Websockets
URL          : http://libwebsockets.org
License      : LGPLv2 and Public Domain and BSD and MIT and zlib
Description  : This is the libwebsockets C library for lightweight websocket clients and
             : servers.
$ sudo systemctl restart netdata
```

Unfortunately, this did not solve the issue either.

**Comment by amoss** [comment]
Hello, thanks for the bug report. Very detailed, we should be able replicate this quickly. It looks like a problem with the openssl library linked into libwebsockets but we will have to replicate the problem to check. 

@underhood Can you set up a CentOS 8 VM and use the kickstart-static64 steps as above. Skip the nginx proxy at first as that should not affect the ACLK connection and see what you get.

**Comment by ThoSap** [comment]
You're welcome 😉
If you need more details just hit me up.

**Comment by Snuggle** [comment]
Having this issue too on RHEL 8, could it be related to firewalld?

**Comment by Ferroin** [comment]
It might be. Netdata needs to be able to make outbound connections to port 443 on app.netdata.cloud for the agentto actually connect to the cloud.

**Comment by Snuggle** [comment]
Even after stopping firewalld or adding a rule allowing port 443 unrestricted access, this still seems to be an issue.

![image](https://user-images.githubusercontent.com/26250962/81597505-bf8cd000-93bd-11ea-8717-8bc8b6900ec5.png)

**Comment by Veltys** [comment]
Hi everyone,

I would like to comment with my problem, maybe it could help. I can give additional details if needed.

I personally have the same problem with all my nodes; with the change to the new cloud panel, everyone has gone "unreachable".

I have to say my configuration is somewhat heterogeneous: some systems are Raspberry Pi with Raspbian, others are VPS from different providers with Ubuntu or Debian... but they all have in common that Netdata is not directly open to the Internet, but through some reverse proxy (generally Apache, although in a particular case it is IIS) with their corresponding Let's Encrypt certificate. Both the Netdata web panel and other proxied services work normally in 443 port.

Thanks and I hope it can be fixed soon!

**Comment by Ferroin** [comment]
For anybody using Netdata on a 64-bit x86 system, if you're seeing the above issues, you may be able to get things working by using our [pre-built static install](https://learn.netdata.cloud/docs/agent/packaging/installer/methods/kickstart-64).

**Comment by ThoSap** [comment]
@Ferroin I used kickstart-static64.sh as the distribution support matrix suggests for AMD64 CentOS 8.X and RHEL 8.X.
https://learn.netdata.cloud/docs/agent/packaging/distributions/

Unfortunately, this did not solve the issue with the ACLK local issuer certificate check error seen in the gist of my initial post.

**Comment by underhood** [comment]
The issue with cloud connection should not be the inbound connections. Are you able to access `app.netdata.cloud 443` from the machine where the agent is running? Does machine where the agent is running have unrestricted access to the internet or is it behind a proxy/corporate firewall?

I am setting up CentOS8 VM as I write this to check if this is issue of some incompatibility with the CentOS8 or environment where it is running.

**Comment by ThoSap** [comment]
Yes, I am able to access `app.netdata.cloud 443` from the machine. The machine has unrestricted access to the internet and no proxy/corporate firewall is in place. The only thing is "special" in my setup is that I use Pi-hole as DNS Server. But the subdomain `app.netdata.cloud` is not blocked there and resolves just fine.

```
$ telnet app.netdata.cloud 443
Trying 35.196.244.138...
Connected to app.netdata.cloud.
Escape character is '^]'.

^CConnection closed by foreign host.
$
$ nslookup app.netdata.cloud
Server:         192.168.1.5
Address:        192.168.1.5#53

Non-authoritative answer:
Name:   app.netdata.cloud
Address: 35.196.244.138
$ curl -v https://app.netdata.cloud
* Rebuilt URL to: https://app.netdata.cloud/
*   Trying 35.196.244.138...
* TCP_NODELAY set
* Connected to app.netdata.cloud (35.196.244.138) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, [no content] (0):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, [no content] (0):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, [no content] (0):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, [no content] (0):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, [no content] (0):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=app.netdata.cloud
*  start date: May 11 06:33:01 2020 GMT
*  expire date: Aug  9 06:33:01 2020 GMT
*  subjectAltName: host "app.netdata.cloud" matched cert's "app.netdata.cloud"
*  issuer: C=US; O=Let's Encrypt; CN=Let's Encrypt Authority X3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* TLSv1.3 (OUT), TLS app data, [no content] (0):
* TLSv1.3 (OUT), TLS app data, [no content] (0):
* TLSv1.3 (OUT), TLS app data, [no content] (0):
* Using Stream ID: 1 (easy handle 0x563e52fe9700)
* TLSv1.3 (OUT), TLS app data, [no content] (0):
> GET / HTTP/2
> Host: app.netdata.cloud
> User-Agent: curl/7.61.1
> Accept: */*
>
* TLSv1.3 (IN), TLS handshake, [no content] (0):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, [no content] (0):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS app data, [no content] (0):
* Connection state changed (MAX_CONCURRENT_STREAMS == 100)!
* TLSv1.3 (OUT), TLS app data, [no content] (0):
* TLSv1.3 (IN), TLS app data, [no content] (0):
< HTTP/2 200
< accept-ranges: bytes
< content-length: 5238
< content-type: text/html
< date: Tue, 12 May 2020 06:19:46 GMT
< etag: "5eb866d4-1476"
< last-modified: Sun, 10 May 2020 20:40:52 GMT
< server: nginx/1.17.5
<
<!DOCTYPE html>
<html>

<head>
  <script>
    window.envSettings = {
      origin: "",
      dataStaticBaseUrl: "/static",
      dataApiUrl: "",
      dataStubsUrl: ""
    }
  </script>
  <!-- Google Tag Manager -->
  <script>
      ; (function (w, d, s, l, i) {
        w[l] = w[l] || []
        w[l].push({
          "gtm.start": new Date().getTime(),
          event: "gtm.js",
        })
        var f = d.getElementsByTagName(s)[0],
          j = d.createElement(s),
          dl = l != "dataLayer" ? "&l=" + l : ""
        j.async = true
        j.src = "https://www.googletagmanager.com/gtm.js?id=" + i + dl
        f.parentNode.insertBefore(j, f)
      })(window, document, "script", "dataLayer", "GTM-N6CBMJD")
    window.dataLayer = window.dataLayer || []
  </script>
  <!-- End Google Tag Manager -->
  <title>Netdata Cloud</title>
  <meta name="application-name" content="netdata" />
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0, minimum-scale=1.0" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />
  <link
    href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,400italic|Roboto+Mono:400,500|Material+Icons"
    rel="stylesheet" />
  <link href="https://fonts.googleapis.com/css?family=IBM+Plex+Sans:400,500,700" rel="stylesheet" />
<link href="/static/console/react_3~main.1d561beb78f109e7ba01.css" rel="stylesheet"><link href="/static/console/main.a0d248958ef471772ecb.css" rel="stylesheet"><link href="/static/console/netdata_dashboard.76b51a595d4016290556.css" rel="stylesheet"></head>

<body class="mdc-theme--background mdc-typography">
  <!-- Google Tag Manager (noscript) -->
  <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-N6CBMJD" height="0" width="0"
      style="display:none;visibility:hidden"></iframe></noscript>
  <!-- End Google Tag Manager (noscript) -->
  <main id="app" class="console-app" data-host="agent" data-account-name="Nameless Netdata Dev">
  </main>

<script type="text/javascript" src="/static/console/vendors~main~netdata_dashboard~netdata_uikit~react_ui_vendor~vendors_react_1~vendors_react_2~vendors_react_3.93cd99fcc00fac053a66.js"></script><script type="text/javascript" src="/static/console/vendors~main~netdata_dashboard~netdata_uikit~react_ui_vendor.2ee11f78b7bea52b3758.js"></script><script type="text/javascript" src="/static/console/vendors~main~netdata_dashboard~netdata_uikit~vendors_react_1.ebb3fca1d063a2a7f55e.js"></script><script type="text/javascript" src="/static/console/react_2~main.de2133e5668b900eaee6.js"></script><script type="text/javascript" src="/static/console/react_3~main~netdata_dashboard~netdata_uikit.564ff959b4d51ba29ac9.js"></script><script type="text/javascript" src="/static/console/react_3~main~netdata_dashboard.fc4de242af77f845616c.js"></script><script type="text/javascript" src="/static/console/react_3~main.ef1658cf118c05ca94d9.js"></script><script type="text/javascript" src="/static/console/common~main~netdata_dashboard.b43adf00d32da2f746d9.js"></script><script type="text/javascript" src="/static/console/main-81dfea61f0cf0680dbf6.js"></script><script type="text/javascript" src="/static/console/vendors_react_1-81dfea61f0cf0680dbf6.js"></script><script type="text/javascript" src="/static/console/vendors~vendors_react_2.3eeed8fd35f6178be0a8.js"></script><script type="text/javascript" src="/static/console/vendors_react_2-81dfea61f0cf0680dbf6.js"></script><script type="text/javascript" src="/static/console/vendors~vendors_react_3.2f3b70151f1f9de18cbe.js"></script><script type="text/javascript" src="/static/console/vendors_react_3-81dfea61f0cf0680dbf6.js"></script><script type="text/javascript" src="/static/console/vendors~react_env_vendor.4e003f7fd704df08ff90.js"></script><script type="text/javascript" src="/static/console/react_env_vendor-81dfea61f0cf0680dbf6.js"></script><script type="text/javascript" src="/static/console/vendors~dg~react_ui_vendor.6e3bec22d9f2df7e445a.js"></script><script type="text/javascript" src="/static/console/react_ui_vendor-81dfea61f0cf0680dbf6.js"></script><script type="text/javascript" src="/static/console/vendors~vendors_common.c4d3bb6628bf366079eb.js"></script><script type="text/javascript" src="/static/console/vendors_common-81dfea61f0cf0680dbf6.js"></script><script type="text/javascript" src="/static/console/netdata_uikit-81dfea61f0cf0680dbf6.js"></script><script type="text/javascript" src="/static/console/netdata_dashboard-81dfea61f0cf0680dbf6.js"></script><script type="text/javascript" src="/static/console/vendors~jq.b31defa2f47d875991cc.js"></script><script type="text/javascript" src="/static/console/jq-81dfea61f0cf0680dbf6.js"></script><script type="text/javascript" src="/static/console/vendors~dg.a1899813bd33446962ae.js"></script><script type="text/javascript" src="/static/console/dg-81dfea61f0cf0680dbf6.js"></script></body>

* Connection #0 to host app.netdata.cloud left intact
</html>
```

**Comment by underhood** [comment]
Seems to have some SSL issues on CentOS8:
```
2020-05-12 03:44:19: netdata INFO  : ACLK_Main : Setting ACLK target host=app.netdata.cloud port=443 from https://app.netdata.cloud
2020-05-12 03:44:19: netdata INFO  : ACLK_Main : Attempting to establish the agent cloud link
2020-05-12 03:44:19: netdata INFO  : ACLK_Main : Retrieving challenge from cloud: app.netdata.cloud 443 /api/v1/auth/node/d99fac1e-9422-11ea-9d24-08002771e530/challenge
2020-05-12 03:44:19: netdata INFO  : ACLK_Main : aclk_send_https_request GET
2020-05-12 03:44:19: netdata ERROR : ACLK_Main : Libwebsockets: SSL error: unable to get local issuer certificate (preverify_ok=0;err=20;depth=1)
2020-05-12 03:44:19: netdata ERROR : ACLK_Main : Challenge failed: 
2020-05-12 03:44:19: netdata INFO  : ACLK_Main : Retrying to establish the ACLK connection in 0.000 seconds
2020-05-12 03:44:19: netdata INFO  : ACLK_Main : Attempting to establish the agent cloud link
2020-05-12 03:44:19: netdata INFO  : ACLK_Main : Retrieving challenge from cloud: app.netdata.cloud 443 /api/v1/auth/node/d99fac1e-9422-11ea-9d24-08002771e530/challenge
2020-05-12 03:44:19: netdata INFO  : ACLK_Main : aclk_send_https_request GET
2020-05-12 03:44:20: netdata ERROR : ACLK_Main : Libwebsockets: SSL error: unable to get local issuer certificate (preverify_ok=0;err=20;depth=1)
2020-05-12 03:44:20: netdata ERROR : ACLK_Main : Challenge failed: 
2020-05-12 03:44:20: netdata INFO  : ACLK_Main : Retrying to establish the ACLK connection in 1.339 seconds
2020-05-12 03:44:21: netdata INFO  : ACLK_Main : Attempting to establish the agent cloud link
2020-05-12 03:44:21: netdata INFO  : ACLK_Main : Retrieving challenge from cloud: app.netdata.cloud 443 /api/v1/auth/node/d99fac1e-9422-11ea-9d24-08002771e530/challenge
2020-05-12 03:44:21: netdata INFO  : ACLK_Main : aclk_send_https_request GET
2020-05-12 03:44:22: netdata ERROR : ACLK_Main : Libwebsockets: SSL error: unable to get local issuer certificate (preverify_ok=0;err=20;depth=1)
2020-05-12 03:44:22: netdata ERROR : ACLK_Main : Challenge failed: 
2020-05-12 03:44:22: netdata INFO  : ACLK_Main : Retrying to establish the ACLK connection in 2.194 seconds
2020-05-12 03:44:24: netdata INFO  : ACLK_Main : Attempting to establish the agent cloud link
2020-05-12 03:44:24: netdata INFO  : ACLK_Main : Retrieving challenge from cloud: app.netdata.cloud 443 /api/v1/auth/node/d99fac1e-9422-11ea-9d24-08002771e530/challenge
2020-05-12 03:44:24: netdata INFO  : ACLK_Main : aclk_send_https_request GET
2020-05-12 03:44:24: netdata ERROR : ACLK_Main : Libwebsockets: SSL error: unable to get local issuer certificate (preverify_ok=0;err=20;depth=1)
2020-05-12 03:44:24: netdata ERROR : ACLK_Main : Challenge failed: 
2020-05-12 03:44:24: netdata INFO  : ACLK_Main : Retrying to establish the ACLK connection in 4.127 seconds
```

**Comment by underhood** [comment]
@ThoSap can you take a look at Netdata log `grep -i ACLK /opt/netdata/var/log/netdata/error.log` (assuming you installed into `opt` dir) to see if the errors you are getting is the same?

**Comment by ThoSap** [comment]
@underhood this is the exact error I get.
The gist of my initial post: https://gist.github.com/ThoSap/f5647ba35097c12dcb5f3b92ef457ac4

Could it be that libwebsockets cannot verify the full chain because app.netdata.cloud does not send the root CA `DST Root CA X3` of `Let's Encrypt Authority X3` in the full certificate chain?
https://www.ssllabs.com/ssltest/analyze.html?d=app.netdata.cloud

Sending the certificate of `DST Root CA X3` may not be strictly necessary as `Let's Encrypt Authority X3` should be valid as CA for most OS and Browsers.

**Comment by ThoSap** [comment]
I did some testing with my own domain using a Let's Encrypt certificate.
As I also had the root CA `DST Root CA X3` in the certificates full chain I never had an issue on CentOS 8.

Removing the root CA `DST Root CA X3` from the full chain results in the same error that app.netdata.cloud gets:

```
$ dnf info ca-certificates
Last metadata expiration check: 0:00:05 ago on Tue 12 May 2020 11:55:07 AM CEST.
Installed Packages
Name         : ca-certificates
Version      : 2019.2.32
Release      : 80.0.el8_1
Architecture : noarch
Size         : 970 k
Source       : ca-certificates-2019.2.32-80.0.el8_1.src.rpm
Repository   : @System
From repo    : BaseOS
Summary      : The Mozilla CA root certificate bundle
URL          : https://fedoraproject.org/wiki/CA-Certificates
License      : Public Domain
Description  : This package contains the set of CA certificates chosen by the
             : Mozilla Foundation for use with the Internet PKI.

$ openssl version
OpenSSL 1.1.1c FIPS  28 May 2019

$ openssl version -d
OPENSSLDIR: "/etc/pki/tls"

$ openssl s_client -connect app.netdata.cloud:443 -servername app.netdata.cloud -CApath /etc/pki/tls/ -showcerts
CONNECTED(00000003)
depth=1 C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 CN = app.netdata.cloud
verify return:1
---
Certificate chain
 0 s:CN = app.netdata.cloud
   i:C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
-----BEGIN CERTIFICATE-----
MIIFWjCCBEKgAwIBAgISBFNJM7EDxZkGIVlaK3sRR/UxMA0GCSqGSIb3DQEBCwUA
MEoxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MSMwIQYDVQQD
ExpMZXQncyBFbmNyeXB0IEF1dGhvcml0eSBYMzAeFw0yMDA1MTEwNjMzMDFaFw0y
MDA4MDkwNjMzMDFaMBwxGjAYBgNVBAMTEWFwcC5uZXRkYXRhLmNsb3VkMIIBIjAN
BgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArhfI1e3yOwnJCRwKIgC5dq3jwXsR
cPnB9JU27zlsCJRmtaBcZDXmcVtKQ/JrEFYZe2QQtKH0rtxyUAyl9OnySEoMW8SC
uZ7/kZ8EDpyk6QhZPg1ncVXLd2TQzv5i4VVK2yaTh2ZKJ0DFf6R1O/bcZZ5S9noq
eo6RiTw3AN1aQKdrriPU/37mfYT7dksM0pke+4iLIqJz5dDE9+R4ZaoH2p5Ooi+s
Z/+vXEufTLRnTBS1LYjcKCXwe3lJUV3s8N4LuG2AaK7eBXm5NEctwgNDI0tC+SUR
taLW1goMFDeoFo+XCTUv466X861XP3XwZA9HUOcV93zqpRSO7j0OUCM0ZwIDAQAB
o4ICZjCCAmIwDgYDVR0PAQH/BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggr
BgEFBQcDAjAMBgNVHRMBAf8EAjAAMB0GA1UdDgQWBBQmkGQTIuDWnf62OfHwm0dX
4DJpkzAfBgNVHSMEGDAWgBSoSmpjBH3duubRObemRWXv86jsoTBvBggrBgEFBQcB
AQRjMGEwLgYIKwYBBQUHMAGGImh0dHA6Ly9vY3NwLmludC14My5sZXRzZW5jcnlw
dC5vcmcwLwYIKwYBBQUHMAKGI2h0dHA6Ly9jZXJ0LmludC14My5sZXRzZW5jcnlw
dC5vcmcvMBwGA1UdEQQVMBOCEWFwcC5uZXRkYXRhLmNsb3VkMEwGA1UdIARFMEMw
CAYGZ4EMAQIBMDcGCysGAQQBgt8TAQEBMCgwJgYIKwYBBQUHAgEWGmh0dHA6Ly9j
cHMubGV0c2VuY3J5cHQub3JnMIIBBAYKKwYBBAHWeQIEAgSB9QSB8gDwAHYA8JWk
WfIA0YJAEC0vk4iOrUv+HUfjmeHQNKawqKqOsnMAAAFyAqa/BwAABAMARzBFAiB5
ClhBeEswiKFctSV+iFJCAuq4vx8mUp+DY7Uf78Zh7AIhAJpeL53muWjjG6O6eoq5
Rq17TNykYwFIaS2qhUZU1AOeAHYAB7dcG+V9aP/xsMYdIxXHuuZXfFeUt2ruvGE6
GmnTohwAAAFyAqa/OwAABAMARzBFAiAfWKgdNVWQXWKQd5ebBMIb7V/IJzGLHy6v
NXCijSCp0wIhAIRBqErLHEPwEAv77/mPswf+Ea+7N7CeNoE++DcHiXgCMA0GCSqG
SIb3DQEBCwUAA4IBAQAGFeOV+OB67W+QQfrrRJwH3gdet3y9PfHGeKKuYDUgaD2d
zqS8kdJBb+Y7D0yfW/wcwd7fJMNQtYXM8pDKQK/Pcakc4U+ETfSYnNyEfHygXY/G
nSVhoar61JNyOT3kLAXMusBM9fRKEIj9/ooNo4l0aH+aDjHRxGCtf9a4ucUvUPiv
JIiDkYGiiDfGpmKPVI1ajHwBBL9uzRe7F3DrlszVvKqaN/N4aM5tVgLEDhsyDQol
YmLkAbPelgu3/oegSmPbxssFWHAaHhU580fpHEbp7xh2rept+pnJMb53/0nl0lqF
0K53n/2PuJEBJdrYIRcQIWahwFH7mzk5TuWqG3qP
-----END CERTIFICATE-----
 1 s:C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
   i:O = Digital Signature Trust Co., CN = DST Root CA X3
-----BEGIN CERTIFICATE-----
MIIEkjCCA3qgAwIBAgIQCgFBQgAAAVOFc2oLheynCDANBgkqhkiG9w0BAQsFADA/
MSQwIgYDVQQKExtEaWdpdGFsIFNpZ25hdHVyZSBUcnVzdCBDby4xFzAVBgNVBAMT
DkRTVCBSb290IENBIFgzMB4XDTE2MDMxNzE2NDA0NloXDTIxMDMxNzE2NDA0Nlow
SjELMAkGA1UEBhMCVVMxFjAUBgNVBAoTDUxldCdzIEVuY3J5cHQxIzAhBgNVBAMT
GkxldCdzIEVuY3J5cHQgQXV0aG9yaXR5IFgzMIIBIjANBgkqhkiG9w0BAQEFAAOC
AQ8AMIIBCgKCAQEAnNMM8FrlLke3cl03g7NoYzDq1zUmGSXhvb418XCSL7e4S0EF
q6meNQhY7LEqxGiHC6PjdeTm86dicbp5gWAf15Gan/PQeGdxyGkOlZHP/uaZ6WA8
SMx+yk13EiSdRxta67nsHjcAHJyse6cF6s5K671B5TaYucv9bTyWaN8jKkKQDIZ0
Z8h/pZq4UmEUEz9l6YKHy9v6Dlb2honzhT+Xhq+w3Brvaw2VFn3EK6BlspkENnWA
a6xK8xuQSXgvopZPKiAlKQTGdMDQMc2PMTiVFrqoM7hD8bEfwzB/onkxEz0tNvjj
/PIzark5McWvxI0NHWQWM6r6hCm21AvA2H3DkwIDAQABo4IBfTCCAXkwEgYDVR0T
AQH/BAgwBgEB/wIBADAOBgNVHQ8BAf8EBAMCAYYwfwYIKwYBBQUHAQEEczBxMDIG
CCsGAQUFBzABhiZodHRwOi8vaXNyZy50cnVzdGlkLm9jc3AuaWRlbnRydXN0LmNv
bTA7BggrBgEFBQcwAoYvaHR0cDovL2FwcHMuaWRlbnRydXN0LmNvbS9yb290cy9k
c3Ryb290Y2F4My5wN2MwHwYDVR0jBBgwFoAUxKexpHsscfrb4UuQdf/EFWCFiRAw
VAYDVR0gBE0wSzAIBgZngQwBAgEwPwYLKwYBBAGC3xMBAQEwMDAuBggrBgEFBQcC
ARYiaHR0cDovL2Nwcy5yb290LXgxLmxldHNlbmNyeXB0Lm9yZzA8BgNVHR8ENTAz
MDGgL6AthitodHRwOi8vY3JsLmlkZW50cnVzdC5jb20vRFNUUk9PVENBWDNDUkwu
Y3JsMB0GA1UdDgQWBBSoSmpjBH3duubRObemRWXv86jsoTANBgkqhkiG9w0BAQsF
AAOCAQEA3TPXEfNjWDjdGBX7CVW+dla5cEilaUcne8IkCJLxWh9KEik3JHRRHGJo
uM2VcGfl96S8TihRzZvoroed6ti6WqEBmtzw3Wodatg+VyOeph4EYpr/1wXKtx8/
wApIvJSwtmVi4MFU5aMqrSDE6ea73Mj2tcMyo5jMd6jmeWUHK8so/joWUoHOUgwu
X4Po1QYz+3dszkDqMp4fklxBwXRsW10KXzPMTZ+sOPAveyxindmjkW8lGy+QsRlG
PfZ+G6Z6h7mjem0Y+iWlkYcV4PIWL1iwBi8saCbGS5jN2p8M+X+Q7UNKEkROb3N6
KOqkqm57TH2H3eDJAkSnh6/DNFu0Qg==
-----END CERTIFICATE-----
---
Server certificate
subject=CN = app.netdata.cloud

issuer=C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3

---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: RSA-PSS
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 3113 bytes and written 405 bytes
Verification error: unable to get local issuer certificate
---
New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
Server public key is 2048 bit
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 20 (unable to get local issuer certificate)
---
---
Post-Handshake New Session Ticket arrived:
SSL-Session:
    Protocol  : TLSv1.3
    Cipher    : TLS_AES_256_GCM_SHA384
    Session-ID: CFF34EBF817EE2F1E9754E7648D5B34B15C41F686D8C8DBCD03120D8F337DAA6
    Session-ID-ctx:
    Resumption PSK: 02050907902662CEBAFE9309D6DCFF1554C9601BA2C28F224436ACDD4D8E31CFF6B96BB4C88DC09256BBC9953DA018F3
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 7200 (seconds)
    TLS session ticket:
    0000 - 16 1d ac f4 94 0b 34 32-9b 92 b5 89 a2 92 8b d1   ......42........
    0010 - 93 f9 aa 3b 29 31 06 50-9d 12 0b 5c 6f fd ae e9   ...;)1.P...\o...

    Start Time: 1589276880
    Timeout   : 7200 (sec)
    Verify return code: 20 (unable to get local issuer certificate)
    Extended master secret: no
    Max Early Data: 0
---
read R BLOCK
---
Post-Handshake New Session Ticket arrived:
SSL-Session:
    Protocol  : TLSv1.3
    Cipher    : TLS_AES_256_GCM_SHA384
    Session-ID: 26D45090DAA22F86A24CCB28203304442A8FDCD918CF33D0BA7434AF8D92B681
    Session-ID-ctx:
    Resumption PSK: 68638130D7162F2C1ECF009680ED903B40DF324E136131C2E4181A784A09421DFFF8C96F746A0A2C34ABDC507E195AD1
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 7200 (seconds)
    TLS session ticket:
    0000 - fe ce f5 a5 85 fc b0 49-79 e4 af 92 8b c3 79 d1   .......Iy.....y.
    0010 - e1 ce 1b 8b 26 a1 94 c1-54 2e 47 ac 7d b8 2d 1e   ....&...T.G.}.-.

    Start Time: 1589276880
    Timeout   : 7200 (sec)
    Verify return code: 20 (unable to get local issuer certificate)
    Extended master secret: no
    Max Early Data: 0
---
read R BLOCK
HTTP/1.1 408 Request Time-out
content-length: 110
cache-control: no-cache
content-type: text/html
connection: close

<html><body><h1>408 Request Time-out</h1>
Your browser didn't send a complete request in time.
</body></html>
closed
```

@underhood @Ferroin **Just add the `DST Root CA X3` to the full chain of your NGINX webserver certificate** and it should work for CentOS 8.X, RHEL 8.X etc. 😉
```
-----BEGIN CERTIFICATE-----
MIIDSjCCAjKgAwIBAgIQRK+wgNajJ7qJMDmGLvhAazANBgkqhkiG9w0BAQUFADA/
MSQwIgYDVQQKExtEaWdpdGFsIFNpZ25hdHVyZSBUcnVzdCBDby4xFzAVBgNVBAMT
DkRTVCBSb290IENBIFgzMB4XDTAwMDkzMDIxMTIxOVoXDTIxMDkzMDE0MDExNVow
PzEkMCIGA1UEChMbRGlnaXRhbCBTaWduYXR1cmUgVHJ1c3QgQ28uMRcwFQYDVQQD
Ew5EU1QgUm9vdCBDQSBYMzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEB
AN+v6ZdQCINXtMxiZfaQguzH0yxrMMpb7NnDfcdAwRgUi+DoM3ZJKuM/IUmTrE4O
rz5Iy2Xu/NMhD2XSKtkyj4zl93ewEnu1lcCJo6m67XMuegwGMoOifooUMM0RoOEq
OLl5CjH9UL2AZd+3UWODyOKIYepLYYHsUmu5ouJLGiifSKOeDNoJjj4XLh7dIN9b
xiqKqy69cK3FCxolkHRyxXtqqzTWMIn/5WgTe1QLyNau7Fqckh49ZLOMxt+/yUFw
7BZy1SbsOFU5Q9D8/RhcQPGX69Wam40dutolucbY38EVAjqr2m7xPi71XAicPNaD
aeQQmxkqtilX4+U9m5/wAl0CAwEAAaNCMEAwDwYDVR0TAQH/BAUwAwEB/zAOBgNV
HQ8BAf8EBAMCAQYwHQYDVR0OBBYEFMSnsaR7LHH62+FLkHX/xBVghYkQMA0GCSqG
SIb3DQEBBQUAA4IBAQCjGiybFwBcqR7uKGY3Or+Dxz9LwwmglSBd49lZRNI+DT69
ikugdB/OEIKcdBodfpga3csTS7MgROSR6cz8faXbauX+5v3gTt23ADq1cEmv8uXr
AvHRAosZy5Q6XkjEGB5YGV8eAlrwDPGxrancWYaLbumR9YbK+rlmM6pZW87ipxZz
R8srzJmwN0jP41ZL9c8PDHIyh8bwRLtTcm1D9SZImlJnt1ir/md2cXjbDaJWFBM5
JDGFoqgCWjBH4d1QB7wCCZAA62RjYJsWvIjJEubSfZGL+T0yjWW06XyxV3bqxbYo
Ob8VZRzI9neWagqNdwvYkQsEjgfbKbYK7p2CNTUQ
-----END CERTIFICATE-----

```

**Comment by ThoSap** [comment]
P.S. Don't forget to restart NGINX after adding the `DST Root CA X3` to the full chain, otherwise the certificate change will not be loaded by NGINX.

**Comment by amoss** [comment]
@cloud-sre Please take a look at the comments above about the certificate chain.

**Comment by amoss** [comment]
Before release we saw a similar problem, but only on very old versions of openssl. I think you may have identified the root cause of why.

**Comment by Snuggle** [comment]
@ThoSap How would you add this certificate? I'm using the LetsEncrypt to manage my certificates behind a NGINX reverse proxy, which is proxying Netdata, I'm not sure why the reverse proxy's certificates matter here?

**Comment by ThoSap** [comment]
@Snuggle nothing needs to change in your environment.

It seems like the NGINX reverse proxy of `app.netdata.cloud` is only supplying the intermediate chain, not the full chain of the Let's Encrypt certificate.

Somehow OpenSSL which is used by libwebsockets requires the full certificate chain in some environments. To mitigate this issue `app.netdata.cloud` should provide the full certificate chain.

https://www.itsfullofstars.de/2016/02/verify-certificate-chain-with-openssl/

**Comment by ncmans** [comment]
@ThoSap thanks for digging into this. We use cert-manager with ACME to get certificates for our domain and up until recently, cert-manager didn't seem to populate the issuer's cert correctly. [A recent version](https://github.com/jetstack/cert-manager/issues/2111) may have fixed the issue you're experiencing.

**Comment by chrisfw** [comment]
Hi, 
How does one who is not using NGINX or any reverse proxy but still gets this error on CentOS 7 resolve the issue?  The fix sounded more like something that should be done on the netdata cloud side by providing the full certificate chain?
Thanks in advance for any clarity you can provide.  I am happy to provide logs if necessary, but it sounds like the same exact issue related here.

Regards,
Chris Whelan

**Comment by vladsol** [comment]
OS: CentOS Linux release 7.8.2003 (Core) x86_64

When installing from prebuilt binaries (stable and nightly build), claimed nodes appears in dashboard as "unreachable"

2020-05-16 22:50:35: netdata INFO  : ACLK_Main : Attempting to establish the agent cloud link
2020-05-16 22:50:35: netdata INFO  : ACLK_Main : Retrieving challenge from cloud: app.netdata.cloud 443 /api/v1/auth/node/node..id/challenge
2020-05-16 22:50:35: netdata INFO  : ACLK_Main : aclk_send_https_request GET
2020-05-16 22:50:35: netdata ERROR : ACLK_Main : **Libwebsockets: SSL error: unable to get local issuer certificate (preverify_ok=0;err=20;depth=1)**
2020-05-16 22:50:35: netdata ERROR : ACLK_Main : Challenge failed:


Installing netdata by compiling from sources (**stable** branch) = no problems :)

With nightly build, the error is different: 2020-05-16 11:42:06: netdata ERROR : ACLK_Main : Decryption of the challenge failed: error:040A1079:lib(4):func(161):reason(121)

**Comment by tmalaher** [comment]
Same problem on  Centos 7, Debian and Amazon Linux 2.
Installing from kickstart-static64.sh displays the problem
building from source with kickstart.sh works fine.

**Comment by ncmans** [comment]
Update: we'll be testing cert-manager v1.15.0 (which should fix this issue) and will deploy it soon if all goes well.

**Comment by Vudubond** [comment]
Same issue on Cloudlinux 6.xx

ACLK_Main : Libwebsockets: SSL error: unable to get local issuer certificate (preverify_ok=0;err=20;depth=1)

**Comment by fqx** [comment]
Same issue on Amazon Linux AMI

**Comment by zeleznikm** [comment]
Same issue on Red Hat Enterprise Linux Server release 7.7 (Maipo)

**Comment by ncmans** [comment]
Looked further into this and here're my findings:
- [ACME does not provide CA cert](https://github.com/jetstack/cert-manager/issues/1571#issuecomment-486204017) and hence cert-manager does not either. This is correct behavior. See next point.
- Our cloud TLS termination is doing the right thing. It does not provide CA cert and does not need to ([as mentioned](https://github.com/netdata/netdata/issues/8966#issuecomment-628066274) by @ThoSap previously) since the CA cert is meant to be already available on the client machine (if it's not, trusting the CA cert provided by the server defeats the whole purpose of having cert signing). We do correctly provide all the intermediate certs at the moment.
- openssl that ships with CentOS 8 has its `OPENSSLDIR` config set to `/etc/pki/tls`.
- It seems that we are running the openssl with `/etc/ssl` config directory. To test, point `/etc/ssl` to `/etc/pki/tls` (ie `cd /etc; ln -s /etc/pki/tls ssl`) and restart the agent (ie `systemctl restart netdata`). It should then work (I tested this on a fresh installation of both the OS and the agent).

cc @amoss

**Comment by underhood** [comment]
I will retest this after commit 1ac12904b0697f1a3131af2f9ed3addc6b396ad9 CentOS6 can connect to cloud. I will take a look at situation on CentOS8.

**Comment by underhood** [comment]
I just used the `./netdata-installer.sh` method and was able to connect to the cloud with the latest master.
![Screenshot from 2020-06-01 12-58-38](https://user-images.githubusercontent.com/6674623/83402777-ab118580-a407-11ea-9d19-1003f0c54c48.png)

I will investigate further if it is the `1ac1290` or different install method that makes it work

**Comment by underhood** [comment]
@Ferroin I might need some of your insight here as it seems to be related to `kickstart-static64.sh` only. I am double checking this claim right now. But both installing with `netdata-installer.sh` and normal `kickstart` my agent can connect to the cloud with CentOS8

**Comment by Ferroin** [comment]
This is technically an upstream issue in RHEL/CentOS (and as a result their derivatives like OEL and Amazon Linux) resulting from their incomplete handling of using `/etc/pki/tls` instead of `/etc/ssl`. I've opened an upstream bug report against CentOS about this as it will impact any other program that's built under the same circumstances  as Netdata's static installer which uses OpenSSL. The upstream report can be found at https://bugs.centos.org/view.php?id=17424.

We will continue to look into a more concrete workaround on our end as well.

**Comment by underhood** [comment]
OK so issue here is only with static install with kickstart-static64. Other install methods (source, normal nonstatic kickstart) work on the same OS (CentOS8 tested for example).

The reason seems to be that in static install we bundle the static build of OpenSSL in the executable. That executable together with OpenSSL library is built on Alpine Linux. Alpine Linux and some RHEL like distros (e.g. CentOS) have incompatible paths for certificates. openssl config file etc.

Therefore we cannot take openssl built on Alpine Linux and use it on CentOS.

Now how to solve this... ideas? @amoss @Ferroin

**Comment by underhood** [comment]
@ThoSap we did some troubleshooting and after recent changes from @Ferroin this issue should be resolved in latest nightlies.

**Comment by ThoSap** [comment]
@underhood perfect, good to hear😊
In the meantime I used the workaround using the symlink.

Thanks for your time and god bless this great project🤟🏻

**Comment by rdifrancesco** [comment]
I'm still experiencing the issues described in the original post.  I'm running RHEL 6.10 and the latest version of netdata, having tried both the stable and nightly builds:

`bash <(curl -Ss https://my-netdata.io/kickstart-static64.sh) --dont-wait --stable-channel`

I receive the "Connection problem" error and also
`Libwebsockets: SSL error: unable to get local issuer certificate (preverify_ok=0;err=20;depth=1)`

If I build it manually, then I can successfully connect to Cloud.  As best I can tell, I have all requisites already installed for RHEL 6.  Any other ideas what could be the issue with the static build?

**Comment by OdysLam** [comment]
Hi, sorry for taking this long to respond.

We are constantly rolling out fixes and improvements. @rdifrancesco  can you verify that you are still experiencing an issue so that we can start looking into it?

**Comment by rdifrancesco** [comment]
@OdysLam after putting my testing on hold for several weeks, I was now able to confirm that my nodes can successfully connect to the war room.  I no longer receive any ssl errors.  I've successfully tested on RHEL 6.10 and the latest Amazon Linux 2 image.  My guess is that something in the Netdata v1.24 agent resolved the issue.  Thanks for getting back to me.

**Comment by Pingger** [comment]
This one solved it for me on Raspberry Pi Zero 2W: https://github.com/netdata/netdata/issues/8966#issuecomment-636676683
(specifically the `cd /etc; ln -s /etc/pki/tls ssl`-Part)
(stating this for reference, since it wasn't that easy to find, what I needed to do to workaround the issue, because this is quite a long thread)
