### ISSUE TITLE
Kickstart Installation fails due to failed checksum validation

### ISSUE THREAD

**Issue by PatTheMav** [netdata/netdata#8967]
##### Bug report summary
When trying to update an existing netdata installation using the kickstart script via `bash <(curl -Ss https://my-netdata.io/kickstart.sh)` the script fails with the following message:

```
ABORTED  Tarball checksum validation failed. Stopping netdata installation and leaving tarball in /tmp/netdata-kickstart-HzwbQt 
```

##### OS / Environment

```
Linux HOSTNAME 5.4.6-xen #546 SMP Wed Dec 25 17:46:43 CET 2019 x86_64 GNU/Linux
/etc/os-release:PRETTY_NAME="Debian GNU/Linux 10 (buster)"
/etc/os-release:NAME="Debian GNU/Linux"
/etc/os-release:VERSION_ID="10"
/etc/os-release:VERSION="10 (buster)"
/etc/os-release:VERSION_CODENAME=buster
/etc/os-release:ID=debian
/etc/os-release:HOME_URL="https://www.debian.org/"
/etc/os-release:SUPPORT_URL="https://www.debian.org/support"
/etc/os-release:BUG_REPORT_URL="https://bugs.debian.org/"
```
 
##### Component Name
* Kickstart Installer

##### Steps To Reproduce
1. Run `bash <(curl -Ss https://my-netdata.io/kickstart.sh)`

##### Expected behavior
The installer downloads and installs netdata as expected.

**Comment by kgns** [comment]
Additionally, when I manually download the latest tarball like this:
`root@kgns:~# curl -sSL --connect-timeout 10 --retry 3 https://storage.googleapis.com/netdata-nightlies/netdata-latest.tar.gz --output netdata-latest.tar.gz

root@kgns:~# sha256sum netdata-latest.tar.gz
05e5cb922782e2ad4359e68110f2431af7ccc40fa1467c9d7db7561bde3134ee  netdata-latest.tar.gz

root@kgns:~# ls -l netdata-latest.tar.gz
-rw-r--r-- 1 root root 4259555 May 12 12:24 netdata-latest.tar.gz`
checksum is correct, and filesize is 4,259,555 bytes

The file kickstart script downloads is different though:
`root@kgns:/tmp/netdata-kickstart-UZy6bC# sha256sum netdata-latest.tar.gz
62054c99690390181f0eb86b5aab04e579838629a9746ea2439302573cd8f660  netdata-latest.tar.gz

root@kgns:/tmp/netdata-kickstart-UZy6bC# ls -l netdata-latest.tar.gz
-rw-r--r-- 1 root root 4259556 May 12 11:55 netdata-latest.tar.gz`

It's size is increased by 1 byte for some reason, thus the checksum differs.

**Comment by PatTheMav** [comment]
Seems fixed with today's nightly release.

**Comment by kgns** [comment]
I still experience the problem, these findings in my previous post are fresh (11:55 am 12:24 pm Europe/Istanbul timezone)

**Comment by kgns** [comment]
`curl -sSL --connect-timeout 10 --retry 3 https://storage.googleapis.com/netdata-nightlies/netdata-latest.tar.gz --output netdata-latest.tar.gz`
works correctly, but 
`curl -sSL --connect-timeout 10 --retry 3 https://storage.googleapis.com/netdata-nightlies/netdata-latest.tar.gz > netdata-latest.tar.gz`
-the kickstart script way of doing it- does not work, it somehow adds an extra byte making it a corrupted archive file

Strange thing is that, this behavior is only present on 2 of my VDSs, while this is not happening on any of my bare metal servers with the same OS (Ubuntu 16.04). cURL version is the same on all servers
```
curl 7.47.0 (x86_64-pc-linux-gnu) libcurl/7.47.0 GnuTLS/3.4.10 zlib/1.2.8 libidn/1.32 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP UnixSockets
```

**Comment by prologic** [comment]
Any of you guys able to do a binary diff and show me what the "one byte" is that differs? I have a hunch but I'm not certain. This has come up before and I blamed "transient network errors" then and moved on. But let's look at this a bit more closely, trouble is I've never been able to reproduce this on anything I have :/

**Comment by kgns** [comment]
```
root@kgns:/tmp/netdata-kickstart-JExI5G# diff -y <(xxd netdata-latest.tar.gz) <(xxd netdata-latest.tar.gz.correct) --suppress-common-lines
0040fda0: 67f9 f9ea 9fff 1ff6 652b 1000 b832 010a  g.......e+ | 0040fda0: 67f9 f9ea 9fff 1ff6 652b 1000 b832 01    g.......e+
```
the only difference appears to be an extra 0x0a byte at the end

**Comment by prologic** [comment]
> the only difference appears to be an extra 0x0a byte at the end

Bingo! That's what I thought ;) I"ll see if I can fix this.

**Comment by Kamik** [comment]
attempt to install from scratch does not work
`root@mail /usr/src # bash <(curl -Ss https://my-netdata.io/kickstart.sh)`
`ABORTED  Tarball checksum validation failed. Stopping netdata installation and leaving tarball in /tmp/netdata-kickstart-8zfUfG`
check of bash script
`root@mail /usr/src # [ "f1e7aa92ca64b797fdc14df59faad205" = "$(curl -Ss https://my-netdata.io/kickstart.sh | md5sum | cut -d ' ' -f 1)" ] && echo "OK, VALID" || echo "FAILED, INVALID"`
`FAILED, INVALID`

**Comment by Kamik** [comment]
`root@mail /tmp/netdata-kickstart-wWR0Lw # diff -y <(xxd netdata-latest.tar.gz) <(xxd netdata-latest.tar.gz.correct) --suppress-common-lines`
`00415d80: e78b 7efe 3fa7 dfe2 b800 c034 0164 6e73  ..~.?..... | 00415d80: e78b 7efe 3fa7 dfe2 b800 c034 01         ..~.?.....`
`00415d90: 6c6f 6f6b 7570 3a20 302e 3030 3420 7c20  lookup: 0. <`
`00415da0: 636f 6e6e 6563 743a 2030 2e30 3039 207c  connect: 0 <`
`00415db0: 2061 7070 636f 6e6e 6563 743a 2030 2e30   appconnec <`
`00415dc0: 3933 207c 2070 7265 7472 616e 7366 6572  93 | pretr <`
`00415dd0: 3a20 302e 3039 3320 7c20 7374 6172 7474  : 0.093 |  <`
`00415de0: 7261 6e73 6665 723a 2030 2e31 3032 207c  ransfer: 0 <`
`00415df0: 2074 6f74 616c 3a20 302e 3136 3820 7c20   total: 0. <`
`00415e00: 7369 7a65 3a20 3432 3833 3738 390a       size: 4283 <`

**Comment by prologic** [comment]
The really frustrating thing here is I am unable to reproduce this; I haven't found a system I can repro this on (yet):

```#!sh
prologic@ubuntu2004:~$ for i in $(seq 0 9); do [ "f1e7aa92ca64b797fdc14df59faad205" = "$(curl -Ss https://my-netdata.io/kickstart.sh | md5sum | cut -d ' ' -f 1)" ] && echo "OK, VALID" || echo "FAILED, INVALID"; done
OK, VALID
OK, VALID
OK, VALID
OK, VALID
OK, VALID
OK, VALID
OK, VALID
OK, VALID
OK, VALID
OK, VALID
prologic@ubuntu2004:~$
```

**Comment by Kamik** [comment]
you are right, the problem is with the server itself. I tried on another - everything passes.

**Comment by PatTheMav** [comment]
Just a hunch, but `0A` is the ascii code for "line-feed" and used in curl for line-breaks. I haven't had time to test this, but _maybe_ the redirection used in the kickstart script causes an additional line-break to be added on bash.

(IIRC `0A` is also what curl uses as line-breaks).

**Comment by kgns** [comment]
I found the culprit (in my case at least). For some reason a while ago I applied this (https://stackoverflow.com/a/14614203/13567850) to be able to see some cURL logs in a nice fashion. This however added \n to the ending of every cURL stdout. Thus cURL worked correctly when it was supplied with an --output argument, but did not when the stdout was used to pipe into a file.

**Comment by kgns** [comment]
Thanks for @PatTheMav for inspiring me about what to search by mentioning line-feed char :)

**Comment by kgns** [comment]
In the end, it might be better of modifying the kickstart script to use the --output argument of cURL, as the real intent of using that command is to download the archive and save it to a file rather then to output it. I don't know if it wasn't like that due to compatibility issues with different versions of cURL and/or distributions though.

**Comment by PatTheMav** [comment]
Great news - might also explain why the issue was fixed with a new nightly for me but persisted for you.

**Comment by Kamik** [comment]
my   .curlrc
`root@mail ~ # cat .curlrc`
`-w "dnslookup: %{time_namelookup} | connect: %{time_connect} | appconnect: %{time_appconnect} | pretransfer: %{time_pretransfer} | starttransfer: %{time_starttransfer} | total: %{time_total} | size: %{size_download}\n"`
I don’t even know when it appeared there)

**Comment by prologic** [comment]
Good news! Thanks to all of you that responded and especially to @Kamik for his `$HOME/.curlrc` config I'm able to reproduce this reliably (_truth be told I've never bothered having a custom `$HOME/.curlrc` so never thought to look there for clues_):

```#!sh
prologic@ubuntu2004:~$ cat .curlrc
w "dnslookup: %{time_namelookup} | connect: %{time_connect} | appconnect: %{time_appconnect} | pretransfer: %{time_pretransfer} | starttransfer: %{time_starttransfer} | total: %{time_total} | size: %{size_download}\n"
prologic@ubuntu2004:~$ bash <(curl -Ss https://my-netdata.io/kickstart.sh)
System            : Linux
Operating System  : GNU/Linux
Machine           : x86_64
BASH major version:
 --- Fetching script to detect required packages... ---
[/tmp/netdata-kickstart-gG2a0T]$ curl -sSL --connect-timeout 10 --retry 3 https://raw.githubusercontent.com/netdata/netdata/master/packaging/installer/install-required-packages.sh  OK

 --- Running downloaded script to detect required packages... ---
[/tmp/netdata-kickstart-gG2a0T]$ sudo /usr/bin/bash /tmp/netdata-kickstart-gG2a0T/install-required-packages.sh netdata Loading /etc/os-release ...

/etc/os-release information:
NAME            : Ubuntu
VERSION         : 20.04 LTS (Focal Fossa)
ID              : ubuntu
ID_LIKE         : debian
VERSION_ID      : 20.04

We detected these:
Distribution    : ubuntu
Version         : 20.04
Codename        : 20.04 LTS (Focal Fossa)
Package Manager : install_apt_get
Packages Tree   : debian
Detection Method: /etc/os-release
Default Python v: 3

Searching for distro_sdk ...
Searching for autoconf_archive ...
 > Checking if package 'autoconf-archive' is installed...
Searching for libz_dev ...
 > Checking if package 'zlib1g-dev' is installed...
Searching for libuuid_dev ...
 > Checking if package 'uuid-dev' is installed...
Searching for libmnl_dev ...
 > Checking if package 'libmnl-dev' is installed...
Searching for json_c_dev ...
 > Checking if package 'libjson-c-dev' is installed...
Searching for libuv ...
 > Checking if package 'libuv1-dev' is installed...
Searching for lz4 ...
 > Checking if package 'liblz4-dev' is installed...
Searching for openssl ...
 > Checking if package 'libssl-dev' is installed...
Searching for judy ...
 > Checking if package 'libjudy-dev' is installed...
Searching for python3_pymongo ...
 > Checking if package 'python3-pymongo' is installed...

All required packages are already installed. Now proceed to the next step.

 OK

[/tmp/netdata-kickstart-gG2a0T]$ curl -sSL --connect-timeout 10 --retry 3 https://storage.googleapis.com/netdata-nightlies/sha256sums.txt  OK

[/tmp/netdata-kickstart-gG2a0T]$ curl -sSL --connect-timeout 10 --retry 3 https://storage.googleapis.com/netdata-nightlies/netdata-latest.tar.gz  OK

 ABORTED  Tarball checksum validation failed. Stopping netdata installation and leaving tarball in /tmp/netdata-kickstart-gG2a0T

prologic@ubuntu2004:~$
```

**Comment by prologic** [comment]
And the reproducer is pretty clear to me:

```#!sh
prologic@ubuntu2004:~$ for i in $(seq 0 9); do [ "f1e7aa92ca64b797fdc14df59faad205" = "$(curl -Ss https://my-netdata.io/kickstart.sh | md5sum | cut -d ' ' -f 1)" ] && echo "OK, VALID" || echo "FAILED, INVALID"; done
FAILED, INVALID
FAILED, INVALID
FAILED, INVALID
FAILED, INVALID
FAILED, INVALID
FAILED, INVALID
FAILED, INVALID
FAILED, INVALID
FAILED, INVALID
FAILED, INVALID
```

**Comment by prologic** [comment]
I have a fix for this in the works. It involves changing every invocation of `curl` in our tooling to have `-q` as the first option. According ot the man page:

>        -q, --disable
>              If used as the first parameter on the command line, the curlrc config file will not be read and used. See  the  -K,  --config  for
>              details on the default config file search path.

But _of course_ it is special and __absolutely__ must be the very first option all on its own!

I _think_ this will ensure any weird shenanigans from random curl configs out in the wild so we can be sure of what we're running.

**Comment by kgns** [comment]
is there any particular reason for not using `-o` option of curl?

**Comment by prologic** [comment]
> is there any particular reason for not using `-o` option of curl?

Because a) it doesn't actually fix the problem if you have the aforementioned above `.curlrc` and b) We want to preserve the "single-line" installer method we have in place on https://netdata.cloud/ 

As it is right it's unclear to me how else `curl` would produce erroneous `\n`(s) in the output besides disabling any default or user configs with the aforementioned `-q` above.

I'm open to suggestions; but we need to preserve the `bash <(curl -q -SSL ...)` installation method we actively promote to make Netdata installation as functionaless as possible. -- There are of course other isntallation methods [well documented](https://learn.netdata.cloud/docs/agent)

**Comment by kgns** [comment]
I'm not a bash expert myself, but `.curlrc` can be used for setting a permanent proxy for curl to work with (if the server is behind a NAT or firewall etc.). `-o` option fixes the problem because it saves the response body to the specified file, not the whole stdout. you can add extra output to stdout by using .curlrc but cannot modify the response body as far as I know, but as I said I'm not an expert in any way, I'm just a user :)

**Comment by prologic** [comment]
Sure. I can replace invoications of `curl` that write the payload to stdout within `kickstart.sh` and `netdata.installer.sh` -- That's no problems. What I cannot do hwoever is change this:

```#!sh
$ bash <(curl -Ss https://my-netdata.io/kickstart.sh)
```

AFAIK however `curl` will still repsect `http_proxy` / `https_proxy` environment variables even if told to ignore a `.curlrc` with `-q` right?

So perhaps the solution here is to do both. As I keep saying; I've not been able to reproduce this anywhere besides the `.curlrc` config provided above.

**Comment by kgns** [comment]
ah you were talking about the kickstart.sh! yea that you can probably not change that if you want a one-liner. but the script does not control the checksum of itself anyway, that's why we don't have any problems starting to run the script, even with custom .curlrc files. the problem only exists while downloading the latest tarball of netdata source code, because the script checks the file's hash against the supplied ones and fail if they don't match

**Comment by prologic** [comment]
Hi all! Sorry for the long delay, hopefully #9165 solves this once and for all. Anyone is welcome to help test it as I put up some temporary artifacts that you can use to test the PR. I had to add support for swapping out where we get artifacts from so I could properly test the flow e2e.

**Comment by prologic** [comment]
With #9165 merged, please let me know if you see/observe/experience any occurrences of checksum failures that are related to transient issues with `curl` or weird `\n` as per the above thread. Hopefully we'll never see this again as I ensured we use both `-q` and `-o-` eveyrwhere.

**Comment by gaia** [comment]
I'm having the issue now, @prologic

**Comment by prologic** [comment]
> I'm having the issue now, @prologic

Sorry I was on vacation (_just got back_). Are you able to share some details? I'm really not expecting the same failure cases here at all.

**Comment by OliverGee** [comment]
I am also now having this issue with the kickstart script. Attempting to install on a fresh (but up to date) RPI 4 running Raspbian.

**Comment by aldem** [comment]
Initially I thought that I have similar issue (\n related), but after inspecting the files I see in downloaded static package:

```
Version:        v1.23.1-93-g8677f158
```
But sha256sum.txt is referring to different build:

```
da8d528e923f2d14060d5efb8f6970a87da068eabda32032e0d380936d2429c9 *./latest-version.txt
ef79f858f5d5426363fab1a3e0e087c948ee10b69d27256f0ac25a55aa9b4ca1 *./netdata-latest.gz.run
677949f2528ad9c27d6d3b53420187f2feec5d1bf6e2190508bac0121f403024 *./netdata-latest.tar.gz
ef79f858f5d5426363fab1a3e0e087c948ee10b69d27256f0ac25a55aa9b4ca1 *./netdata-v1.23.1-82-g023f9dd9.gz.run
677949f2528ad9c27d6d3b53420187f2feec5d1bf6e2190508bac0121f403024 *./netdata-v1.23.1-82-g023f9dd9.tar.gz
```

Either this is a Google's cache issue (I don't use any proxies nor .curlrc) or a bug somewhere... I tried several times within 20 minutes and problem is still there.

**Comment by prologic** [comment]
I _believe_ it is a Google caching issue which I'm not entirely sure what we can do about it to be honest. I'll have a poke around the Google Storage Bucket(s) again that serve this up and see if there are any knobs I can tweak.

**Comment by prologic** [comment]
This [thread](https://stackoverflow.com/questions/37107171/google-cloud-storage-how-can-i-reset-edge-cache) seems relevant; specifically this bit:

> By default, if an object is publicly accessible to all anonymous users and you do not otherwise specify a cacheControl setting, GCS will serve a Cache-Control header of 3600 seconds, or 1 hour. If you're getting stale object data and haven't been messing with cache control settings, I assume you're serving publicly accessible objects. I'm not sure if Google itself is caching your object data or if there's some other cache between you and Google, though.
>
> In the future, you can fix this by explicitly setting a shorter Cache-Control header, which can be controlled on a per-object basis with the cacheControl setting.

**Comment by prologic** [comment]
Based on my research from today I _think_ we may be able to improve this situation. I have some ideas I can try. I've created #9543 to investigate this tomorrow during the next nightly build and publish run.

**Comment by diegomontoya** [comment]
Just got this on Ubuntu 20.04. 

Removing the /temp/* files and trying again did not help.

```
[/tmp/netdata-kickstart-PfyFGgU46M]# curl -q -sSL --connect-timeout 10 --retry 3 --output /tmp/netdata-kickstart-PfyFGgU46M/sha256sum.txt https://storage.googleapis.com/netdata-nightlies/sha256sums.txt  OK  

[/tmp/netdata-kickstart-PfyFGgU46M]# curl -q -sSL --connect-timeout 10 --retry 3 --output /tmp/netdata-kickstart-PfyFGgU46M/netdata-latest.tar.gz https://storage.googleapis.com/netdata-nightlies/netdata-latest.tar.gz  OK  

 ABORTED  Tarball checksum validation failed. Stopping netdata installation and leaving tarball in /tmp/netdata-kickstart-PfyFGgU46M 
```

**Comment by Reeceline** [comment]
I'm still having this problem, haven't been able to add one specific server for MONTHS

`[root@host tmp]# bash <(curl -Ss https://my-netdata.io/kickstart.sh)
/dev/fd/63: line 171: /tmp/netdata-test.J2NQ6JnJpC: Permission denied
/dev/fd/63: line 171: /tmp/netdata-test.pAoBuzbKYY: Permission denied

Unable to find a usable temporary directory. Please set $TMPDIR to a path that is both writable and allows execution of files and try again.
System            : Linux
Operating System  : GNU/Linux
Machine           : x86_64
BASH major version: 
 --- Fetching script to detect required packages... --- 
[/tmp]# curl -q -sSL --connect-timeout 10 --retry 3 --output /install-required-packages.sh https://raw.githubusercontent.com/netdata/netdata/master/packaging/installer/install-required-packages.sh  OK  

 --- Running downloaded script to detect required packages... --- 
[/tmp]# /usr/bin/bash /install-required-packages.sh netdata Loading /etc/os-release ...
You should have EPEL enabled to install all the prerequisites.
Check: http://www.tecmint.com/how-to-enable-epel-repository-for-rhel-centos-6-5/
 > CentOS Version: 7 ...
 > Checking for epel ...

/etc/os-release information:
NAME            : CentOS Linux
VERSION         : 7 (Core)
ID              : centos
ID_LIKE         : rhel fedora
VERSION_ID      : 7

We detected these:
Distribution    : centos
Version         : 7
Codename        : 7 (Core)
Package Manager : install_yum
Packages Tree   : centos
Detection Method: /etc/os-release
Default Python v: 2 (will install python3 too)

Searching for distro_sdk ...
Searching for autoconf_archive ...
 > Checking if package 'autoconf-archive' is installed...
Searching for libz_dev ...
 > Checking if package 'zlib-devel' is installed...
Searching for libuuid_dev ...
 > Checking if package 'libuuid-devel' is installed...
Searching for libmnl_dev ...
 > Checking if package 'libmnl-devel' is installed...
Searching for json_c_dev ...
 > Checking if package 'json-c-devel' is installed...
Searching for libuv ...
 > Checking if package 'libuv-devel' is installed...
Searching for lz4 ...
 > Checking if package 'lz4-devel' is installed...
Searching for openssl ...
 > Checking if package 'openssl-devel' is installed...
Searching for judy ...
Searching for libelf ...
 > Checking if package 'elfutils-libelf-devel' is installed...

All required packages are already installed. Now proceed to the next step.

 OK  

[/tmp]# curl -q -sSL --connect-timeout 10 --retry 3 --output /sha256sum.txt https://storage.googleapis.com/netdata-nightlies/sha256sums.txt  OK  

[/tmp]# curl -q -sSL --connect-timeout 10 --retry 3 --output /netdata-latest.tar.gz https://storage.googleapis.com/netdata-nightlies/netdata-latest.tar.gz  OK  

 ABORTED  Tarball checksum validation failed. Stopping Netdata Agent installation and leaving tarball in .
Usually this is a result of an older copy of the file being cached somewhere upstream and can be resolved by retrying in an hour. 

[root@host tmp]#  `

**Comment by erfan-ilyas** [comment]
I am still having this issue:

```
[/tmp/netdata-kickstart-gsrI1R9IVu]# curl -q -sSL --connect-timeout 10 --retry 3 --output /tmp/netdata-kickstart-gsrI1R9IVu/sha256sum.txt https://storage.googleapis.com/netdata-nightlies/sha256sums.txt  OK

[/tmp/netdata-kickstart-gsrI1R9IVu]# curl -q -sSL --connect-timeout 10 --retry 3 --output /tmp/netdata-kickstart-gsrI1R9IVu/netdata-latest.tar.gz https://storage.googleapis.com/netdata-nightlies/netdata-latest.tar.gz  OK

 ABORTED  Tarball checksum validation failed. Stopping Netdata Agent installation and leaving tarball in /tmp/netdata-kickstart-gsrI1R9IVu.
Usually this is a result of an older copy of the file being cached somewhere upstream and can be resolved by retrying in an hour.

**Comment by jidylle** [comment]
same issue
`[/tmp/netdata-kickstart-vnuRoMD2w1]# curl -q -sSL --connect-timeout 10 --retry 3 --output /tmp/netdata-kickstart-vnuRoMD2w1/sha256sum.txt https://storage.googleapis.com/netdata-nightlies/sha256sums.txt  OK  

[/tmp/netdata-kickstart-vnuRoMD2w1]# curl -q -sSL --connect-timeout 10 --retry 3 --output /tmp/netdata-kickstart-vnuRoMD2w1/netdata-latest.tar.gz https://storage.googleapis.com/netdata-nightlies/netdata-latest.tar.gz  OK  

 ABORTED  Tarball checksum validation failed. Stopping Netdata Agent installation and leaving tarball in /tmp/netdata-kickstart-vnuRoMD2w1.
Usually this is a result of an older copy of the file being cached somewhere upstream and can be resolved by retrying in an hour.`

**Comment by Ferroin** [comment]
We seem to be intermittently still seeing issues like this, with some correlation with the geographic location of the systems actually seeing the issues. We’re not entirely sure what, exactly, is going on here, but it appears to be an issue with Google Cloud Storage blocking access to resources for as-of-yet unknown reasons.

In the short term, using a stable release instead of a nightly build should sidestep the issue. If you already have things installed on your system, you can switch to a stable release in-place by running the same installer command you ran originally, but adding `--stable-channel --reinstall` to the options you pass to it (and, if you want to switch back, you can do the same thing but with `--nightly-channel` instead of `--stable-channel`).

**Comment by jidylle** [comment]
It works perfectly now. Thank you @Ferroin .
