### ISSUE TITLE
netdata ERROR : MAIN : EOF found in spawn pipe.

### ISSUE THREAD

**Issue by kaplandani** [netdata/netdata#9363]
#### Summary
netdata fails to start in a loop: 

all I see in the log is this: 

020-06-17 18:56:27: netdata INFO  : MAIN : Loading metadata log "/var/cache/netdata/dbengine/metadatalog-00000-00026.mlf".
2020-06-17 18:56:27: netdata INFO  : MAIN : Collector updated metadata for chart disk_qops.dm-22
2020-06-17 18:56:27: netdata ERROR : MAIN : EOF found in spawn pipe.
Shutting down spawn server event loop.
Shutting down spawn server loop complete.

and some times this:
2020-06-17 18:55:28: netdata ERROR : MAIN : Request to remove RRDVAR '' from index failed. Not Found.
2020-06-17 18:55:28: netdata ERROR : MAIN : RRDVAR: Attempted to delete variable '' from host 's5', but it is not found.
EOF found in spawn pipe.
Shutting down spawn server event loop.
Shutting down spawn server loop complete.

the only way to resolve this was clearing the cache folder.

**Comment by mfundul** [comment]
Related to https://github.com/netdata/netdata/pull/9354

**Comment by mfundul** [comment]
Thank you for reporting this. What netdata version are you running? What was your installation method? Can you share more parts of the actual error log? You can take out any sensitive information before sharing.

**Comment by ekexcello** [comment]
Hello.
Got same error with Netdata 1.23.1 running on Gentoo (installed with portage).
Attempt to run Netdata logs:
```
2020-07-02 17:53:18: netdata ERROR : MAIN : Mismatch of metadata log DIMENSION GUID with dbengine metric GUID.
2020-07-02 17:53:18: netdata ERROR : MAIN : Mismatch of metadata log DIMENSION GUID with dbengine metric GUID.
2020-07-02 17:53:18: netdata ERROR : MAIN : Mismatch of metadata log DIMENSION GUID with dbengine metric GUID.
2020-07-02 17:53:18: netdata ERROR : MAIN : Mismatch of metadata log DIMENSION GUID with dbengine metric GUID.
2020-07-02 17:53:18: netdata ERROR : MAIN : Mismatch of metadata log DIMENSION GUID with dbengine metric GUID.
2020-07-02 17:53:18: netdata ERROR : MAIN : EOF found in spawn pipe.
```
Netdata crashes with segfault:
```
2020-07-02 17:58:00: netdata INFO  : MAIN : SIGNAL: Not enabling reaper
Segmentation fault
```
in kernel log corresponding messages (for two starts):
[Thu Jul  2 17:53:18 2020] traps: netdata[80981] general protection ip:7e02e1b985f7 sp:7fff7cd198f8 error:0 in libc-2.30.so[7e02e1a57000+152000]
[Thu Jul  2 17:58:04 2020] traps: netdata[86192] general protection ip:7e76a55465f7 sp:7ffebf554d18 error:0 in libc-2.30.so[7e76a5405000+152000]

Note. Netdata 1.23 has _no_ such issue, so have had to downgrade

**Comment by zack-shoylev** [comment]
@ekexcello Can you uninstall your portage version and try installing through the script to see if it works that way? This will help eliminate possible dependency/portage-caused issues.

**Comment by ekexcello** [comment]
Hello @zack-shoylev,
As for installation from source, decision on this is in progress - the system I faced this issue on is production, so manipulating software is not straightforward task. However, I tried to install version 1.23.1 on two other servers that were under maintenance today and have very same configuration. Unpleasant surprise is that on those servers no error appeared with either 1.23.0 or 1.23.1, so this issue can be reproduced under some specific conditions only and it's not yet clear what these conditions are.

**Comment by ekexcello** [comment]
Small update.

Netdata that used to crash with 
```
[global]
    history = 129600
    memory mode = dbengine
    page cache size = 2048
    dbengine disk space = 8192
```
works stable with
```
[global]
    history = 129600
    memory mode = dbengine
    page cache size = 1536
    dbengine disk space = 4096
```

**Comment by gustavohw** [comment]
Had this issue as well, firstly downgraded from `netdata v1.23.1-34-nightly` to `netdata v1.23.1` no luck:

```
2020-07-05 12:15:43: netdata INFO  : MAIN : Unable to load '/var/lib/netdata/cloud.d/claimed_id', setting state to AGENT_UNCLAIMED
2020-07-05 12:15:43: netdata ERROR : MAIN : Request to remove RRDVAR '`[-AV' from index failed. Not Found.
2020-07-05 12:15:43: netdata ERROR : MAIN : RRDVAR: Attempted to delete variable '`[-AV' from host 'pve', but it is not found.
2020-07-05 12:15:43: netdata ERROR : MAIN : Request to remove RRDVAR 'sysadmin' from index failed. Not Found.
2020-07-05 12:15:43: netdata ERROR : MAIN : RRDVAR: Attempted to delete variable 'sysadmin' from host 'pve', but it is not found.
free(): double free detected in tcache 2
EOF found in spawn pipe.
Shutting down spawn server event loop.
Shutting down spawn server loop complete.
```

Settings for storage:
```
# history = 3996
memory mode = dbengine
page cache size = 256
 dbengine disk space = 8196
```

Resolved by deleting /var/cache/netdata/dbengine as @kaplandani suggested. Lost some metrics but nothing critical.

**Comment by gaia** [comment]
same issue here.

v1.23.1-34-nightly on Debian Buster.

installed from script. uninstalled and re-installed already. at first run after un/install cycle it works for a while. then it stops and the service loops.

PS: added this to the systemd file to keep it from re-trying forever: https://stackoverflow.com/a/39284869

**Comment by kaplandani** [comment]
happened again tonight. 
netdata v1.23.1-44-nightly

**Comment by mfundul** [comment]
Possibly fixed by https://github.com/netdata/netdata/pull/9503

**Comment by gaia** [comment]
Pls update this issue if indeed 9503 fixes it!

**Comment by thiagoftsm** [comment]
Hello @everyone,

The PR #9503 was already merged and the next nightly will have the fixes, please, if you can update and confirm tomorrow that the problem was fixed will be great for everybody.

Best regards!

**Comment by stelfrag** [comment]
A new PR #9509 has been merged to master which addresses a corruption issue during startup. Please update to the latest code from master and try it.

**Comment by gaia** [comment]
@stelfrag problem fixed for me on Debian 10. thank you.

**Comment by gaia** [comment]
Problem is still present on Debian 10. Just takes a bit longer to stop

**Comment by mfundul** [comment]
> 
> 
> Problem is still present on Debian 10. Just takes a bit longer to stop

Maybe it's a different issue. Can you tell us the netdata version, installation method and the contents of `var/log/netdata/error.log`?

**Comment by gaia** [comment]
thanks Markos

`bash <(curl -Ss https://my-netdata.io/kickstart.sh)`

v1.23.2-137-nightly

log https://we.tl/t-hiFTJv2FsV (i got to send you the pword via another channel, could you contact me at https://t.me/onegaia or another channel? I also sent a connection request on LinkedIn)

**Comment by mfundul** [comment]
> 
> 
> thanks Markos
> 
> `bash <(curl -Ss https://my-netdata.io/kickstart.sh)`
> 
> v1.23.2-137-nightly
> 
> log https://we.tl/t-hiFTJv2FsV (i got to send you the pword via another channel, could you contact me at https://t.me/onegaia or another channel? I also sent a connection request on LinkedIn)

@gaia In these logs you sent me I can see only information only for the date "2020-08-07". During this period there is only one netdata agent shutdown, which was triggered by a SIGTERM signal, probably the auto-updater process that updates the netdata agent. However, there was a crash during shutdown, (cc @stelfrag):
```
2020-08-07 06:43:47: netdata INFO  : MAIN : EXIT: freeing database memory...
2020-08-07 06:43:47: netdata INFO  : MAIN : Freeing all memory for host 'node2'...
2020-08-07 06:43:47: netdata ERROR : MAIN : Request to remove RRDVAR '' from index failed. Not Found.
2020-08-07 06:43:47: netdata ERROR : MAIN : RRDVAR: Attempted to delete variable '' from host 'node2', but it is not found.
double free or corruption (out)
```

This may be seemingly different from the original issue in the way it manifests, since it triggers during shutdown and not during start-up. I'm reopening this issue for further investigation. Do you only see this problem whenever the agent shuts down (look for `MAIN : SIGNAL: Received SIGTERM. Cleaning up to exit...` in `var/log/netdata/error.log`)? The nightly builds trigger a restart almost every day.

**Comment by gaia** [comment]
@mfundul I will be on lookout for it. didn't see it in the current log.

lots of "Failed to flush dirty buffers quickly enough in dbengine instance "/var/cache/netdata/dbengine". Metric data are being deleted, please reduce disk load or use a faster disk". can i slow down data collection?

**Comment by mfundul** [comment]
Please send me logs spanning more than a day, ideally I'd like to see a full log from agent start to agent finish, and I will take a look into those warnings.

**Comment by gaia** [comment]
here it is, markos. same pword https://we.tl/t-IN9hBcctAK

**Comment by mfundul** [comment]
This issue may have been fixed by https://github.com/netdata/netdata/pull/9712. Do you use any custom alarms you've written? Please make sure your netdata version is at least `v1.24.0-19` and let's see if this happens again.

**Comment by thiagoftsm** [comment]
@mfundul it looks like the problem was not fixed.

I am running Netdata ` v1.24.0-26-gd897c6512` and I am receiving the same error. In my case this is happening when I send `killall -USR2 netdata`.

I am using the following alarm to debug another bug:

```
 alarm: dev_dim_template
    on: system.cpu
    os: linux
lookup: sum -3s at 0 every 3 percentage foreach *
 units: %
 every: 10s
  warn: $this > 1
  crit: $this > 4
```

**Comment by gaia** [comment]
> This issue may have been fixed by #9712. Do you use any custom alarms you've written? Please make sure your netdata version is at least `v1.24.0-19` and let's see if this happens again.

I have no custom alarms, but i do have different time periods and thresholds for existing alarms (to let them be more forgiving).

regardless, I take it that the issue is confirmed present. I will keep monitoring this issue.

**Comment by thiagoftsm** [comment]
@mfundul I will give more two additional information that can help to debug this:

- When I send `killall -USR2 netdata` the first time the problem did not happen. It normally happens on the third or fourth time I sent the signal. I was sending the signal every minute while I was debugging the issue #9342.
- Finally something that I observed this morning, this never happens when I am using memory mode `ram`.

Best regards!

**Comment by stelfrag** [comment]
@thiagoftsm 

- is this just a parent node ?
- Any children connected at any point in time ? (trying to see if multihost was activated)

**Comment by thiagoftsm** [comment]
> is this just a parent node ?
@stelfrag I am not sure if this is happening on `child`, because the `parent` is always dying.

> Any children connected at any point in time ? (trying to see if multihost was activated)

Yes I always have children connected during my tests.

**Comment by thiagoftsm** [comment]
An update, I ran a 10 minutes test now using `ram` as memory mode, and I can confirm that the problem is also happening with `memory mode = ram`, but it happens with a smaller frequency.

**Comment by mfundul** [comment]
> 
> 
> An update, I ran a 10 minutes test now using `ram` as memory mode, and I can confirm that the problem is also happening with `memory mode = ram`, but it happens with a smaller frequency.

@thiagoftsm if you can reproduce this with a clean netdata cache, with `ram` memory mode then we should probably classify this bug as part of the health AoR.

**Comment by thiagoftsm** [comment]
> @thiagoftsm if you can reproduce this with a clean netdata cache, with `ram` memory mode then we should probably classify this bug as part of the health AoR.

Now that I could recreate the problem with different memory mode, I agree with you, and I think we need to create a new issue for this, the final message is the same, but the source looks like different.

**Comment by mfundul** [comment]
> 
> 
> > @thiagoftsm if you can reproduce this with a clean netdata cache, with `ram` memory mode then we should probably classify this bug as part of the health AoR.
> 
> Now that I could recreate the problem with different memory mode, I agree with you, and I think we need to create a new issue for this, the final message is the same, but the source looks like different.

We could close the original issue and have @gaia follow the new issue.

**Comment by thiagoftsm** [comment]
I created the issue https://github.com/netdata/netdata/issues/9743 for we work with the problem we I described here.
I am not closing this issue, because it is another source of error.

**Comment by mfundul** [comment]
> 
> 
> I created the issue #9743 for we work with the problem we I described here.
> I am not closing this issue, because it is another source of error.

Does this mean that you never saw the `RRDVAR: Attempted to delete variable` print in your test scenario @thiagoftsm ?

**Comment by thiagoftsm** [comment]
> Does this mean that you never saw the RRDVAR: Attempted to delete variable print in your test scenario @thiagoftsm ?

@mfundul I did not verify if there were messages like this in the previous tests, but when I recompiled the tests and I recreated the poblem again, I can say that the message was never there:

```
bash-5.0$ grep "RRDVAR: Attempted to delete variable" /var/log/netdata/error.log 
bash-5.0$ 
```

I also verified that I do not have any messages for `RRDVAR`:

``` 
bash-5.0$ grep "RRDVAR: Attempted to delete variable" /var/log/netdata/error.log 
bash-5.0$ 
```

I am attaching the error.log for you have a better understand of the problem.

[error.log](https://github.com/netdata/netdata/files/5074602/error.log)

**Comment by mfundul** [comment]
> 
> 
> This issue may have been fixed by #9712. Do you use any custom alarms you've written? Please make sure your netdata version is at least `v1.24.0-19` and let's see if this happens again.

@gaia do we have any updates on this? Should I close this issue?

**Comment by Danpiel** [comment]
Facing same issue with unexpected shutdown with EOF found in spawn pipe in log of parent **netdata** pod.
Installed through Helm chart in Kubernetes cluster with 24+ nodes.

**Comment by OdysLam** [comment]
@Danpiel, we are sorry that you are having the same issue. One of our agent team members will answer promptly (e.g @mfundul ), so bear with us as we try to get to the bottom of this!

Btw, welcome to our community. If you have any questions, don't hesitate to create an issue or join our community at https://community.netdata.cloud.

**Comment by mfundul** [comment]
> 
> 
> Facing same issue with unexpected shutdown with EOF found in spawn pipe in log of parent **netdata** pod.
> Installed through Helm chart in Kubernetes cluster with 24+ nodes.

@Danpiel if you're not seeing something similar to `Request to remove RRDVAR '' from index failed. Not Found` in `var/log/netdata/error.log` I advise you to create a new issue with detailed information. Can you take a look?
