### ISSUE TITLE
Alarm notification not sent with kickstart-static64.sh installation

### ISSUE THREAD

**Issue by ThoSap** [netdata/netdata#9494]
##### Bug report summary

Hi, it's me again😉
I've set up Netdata Telegram notifications as described here
https://learn.netdata.cloud/docs/agent/health/notifications
and here
https://learn.netdata.cloud/docs/agent/health/notifications/telegram
and found that somehow the test notification works, **but real alarms are not sent** because of the following error message (taken from /opt/netdata/var/log/netdata/error.log):
```
curl: (77) error setting certificate verify locations:
  CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
2020-07-06 22:15:30: alarm-notify.sh: ERROR: failed to send telegram notification for: superawesomeserver.example.com cgroup_foldingathome.cpu_limit.cgroup_10min_cpu_usage is WARNING to '-123456789' with HTTP error code 000.
```

**As I found a "solution" for this issue** (but with the limitation that the Netdata ACLK stops working again in v1.23.1 Stable - [#8966](https://github.com/netdata/netdata/issues/8966#issuecomment-636676683)) **as stated in section _Steps To Reproduce_**, I'm posting this for documentation purposes.

##### OS / Environment

```
/etc/centos-release:CentOS Linux release 8.2.2004 (Core) 
/etc/os-release:NAME="CentOS Linux"
/etc/os-release:VERSION="8 (Core)"
/etc/os-release:ID="centos"
/etc/os-release:ID_LIKE="rhel fedora"
/etc/os-release:VERSION_ID="8"
/etc/os-release:PLATFORM_ID="platform:el8"
/etc/os-release:PRETTY_NAME="CentOS Linux 8 (Core)"
/etc/os-release:ANSI_COLOR="0;31"
/etc/os-release:CPE_NAME="cpe:/o:centos:centos:8"
/etc/os-release:HOME_URL="https://www.centos.org/"
/etc/os-release:BUG_REPORT_URL="https://bugs.centos.org/"
/etc/os-release:
/etc/os-release:CENTOS_MANTISBT_PROJECT="CentOS-8"
/etc/os-release:CENTOS_MANTISBT_PROJECT_VERSION="8"
/etc/os-release:REDHAT_SUPPORT_PRODUCT="centos"
/etc/os-release:REDHAT_SUPPORT_PRODUCT_VERSION="8"
/etc/os-release:
/etc/redhat-release:CentOS Linux release 8.2.2004 (Core) 
/etc/system-release:CentOS Linux release 8.2.2004 (Core)
```

##### Netdata version

 netdata v1.23.1 Stable

##### Component Name

health -> alarm-notify.sh

##### Steps To Reproduce

1. Setup CentOS 8.2 VM
2. Follow Netdata alarm notification steps for Telegram (created new bot and invited him to a new telegram group)
    https://learn.netdata.cloud/docs/agent/health/notifications
    https://learn.netdata.cloud/docs/agent/health/notifications/telegram
3. Apply dirty symlink quick fix from issue [#8966](https://github.com/netdata/netdata/issues/8966#issuecomment-636676683) so that **Netdata ACLK** works with distros (like RHEL 8.X, CentOS 8.X, Oracle Linux 8.X, SLES, others etc.) that [only officially support kickstart-static64.sh](https://learn.netdata.cloud/docs/agent/packaging/distributions)
4. Test notifications (working fine and received all Telegram test notifications)
```
$ sudo su
# su -s /bin/bash netdata
$ export NETDATA_ALARM_NOTIFY_DEBUG=1
$ /opt/netdata/usr/libexec/netdata/plugins.d/alarm-notify.sh test
```
Results to:
```

# SENDING TEST WARNING ALARM TO ROLE: sysadmin
2020-07-06 22:37:41: alarm-notify.sh: DEBUG: Loading config file '/opt/netdata/usr/lib/netdata/conf.d/health_alarm_notify.conf'...
2020-07-06 22:37:41: alarm-notify.sh: DEBUG: Loading config file '/opt/netdata/etc/netdata/health_alarm_notify.conf'...
--- BEGIN curl command ---
/bin/curl --data-urlencode parse_mode=HTML --data-urlencode disable_web_page_preview=true --data-urlencode $'text=\342\232\240\357\270\217 superawesomeserver.example.com needs attention - <b>test alarm</b>\ntest.chart (test.family)\n<a href="https://app.netdata.cloud/alarms/redirect?agentID=17cdcd41-e46b-420a-8699-88acfba57fc1&host=superawesomeserver.example.com&chart=test.chart&family=test.family&alarm=test_alarm&alarm_unique_id=1&alarm_id=1&alarm_event_id=1&alarm_when=1594067861">test alarm = new value</a>\n<i>this is a test alarm to verify notifications work</i>' https://api.telegram.org/bot111122223:7OpFlFFRzRBbrUUmIjj5HF9Ox2pYJZy5/sendMessage\?chat_id=-123456789 
--- END curl command ---
--- BEGIN received response ---
{"ok":true,"result":{"message_id":21,"from":{"id":1234567890,"is_bot":true,"first_name":"superawesome","username":"superawesome_bot"},"chat":{"id":-123456789,"title":"superawesome monitoring","type":"group","all_members_are_administrators":false},"date":1594067861,"text":"\u26a0\ufe0f superawesomeserver.example.com needs attention - test alarm\ntest.chart (test.family)\ntest alarm = new value\nthis is a test alarm to verify notifications work","entities":[{"offset":3,"length":16,"type":"url"},{"offset":38,"length":10,"type":"bold"},{"offset":61,"length":11,"type":"url"},{"offset":74,"length":22,"type":"text_link","url":"https://app.netdata.cloud/alarms/redirect?agentID=17cdcd41-e46b-420a-8699-88acfba57fc1&host=superawesomeserver.example.com&chart=test.chart&family=test.family&alarm=test_alarm&alarm_unique_id=1&alarm_id=1&alarm_event_id=1&alarm_when=1594067861"},{"offset":97,"length":49,"type":"italic"}]}}
--- END received response ---
RECEIVED HTTP RESPONSE CODE: 200
2020-07-06 22:37:41: alarm-notify.sh: INFO: sent telegram notification for: superawesomeserver.example.com test.chart.test_alarm is WARNING to '-123456789'
# OK

# SENDING TEST CRITICAL ALARM TO ROLE: sysadmin
2020-07-06 22:37:41: alarm-notify.sh: DEBUG: Loading config file '/opt/netdata/usr/lib/netdata/conf.d/health_alarm_notify.conf'...
2020-07-06 22:37:41: alarm-notify.sh: DEBUG: Loading config file '/opt/netdata/etc/netdata/health_alarm_notify.conf'...
--- BEGIN curl command ---
/bin/curl --data-urlencode parse_mode=HTML --data-urlencode disable_web_page_preview=true --data-urlencode $'text=\360\237\224\264 superawesomeserver.example.com is critical - <b>test alarm</b>\ntest.chart (test.family)\n<a href="https://app.netdata.cloud/alarms/redirect?agentID=17cdcd41-e46b-420a-8699-88acfba57fc1&host=superawesomeserver.example.com&chart=test.chart&family=test.family&alarm=test_alarm&alarm_unique_id=1&alarm_id=1&alarm_event_id=2&alarm_when=1594067861">test alarm = new value</a>\n<i>this is a test alarm to verify notifications work</i>' https://api.telegram.org/bot111122223:7OpFlFFRzRBbrUUmIjj5HF9Ox2pYJZy5/sendMessage\?chat_id=-123456789 
--- END curl command ---
--- BEGIN received response ---
{"ok":true,"result":{"message_id":22,"from":{"id":1234567890,"is_bot":true,"first_name":"superawesome","username":"superawesome_bot"},"chat":{"id":-123456789,"title":"superawesome monitoring","type":"group","all_members_are_administrators":false},"date":1594067861,"text":"\ud83d\udd34 superawesomeserver.example.com is critical - test alarm\ntest.chart (test.family)\ntest alarm = new value\nthis is a test alarm to verify notifications work","entities":[{"offset":3,"length":16,"type":"url"},{"offset":34,"length":10,"type":"bold"},{"offset":57,"length":11,"type":"url"},{"offset":70,"length":22,"type":"text_link","url":"https://app.netdata.cloud/alarms/redirect?agentID=17cdcd41-e46b-420a-8699-88acfba57fc1&host=superawesomeserver.example.com&chart=test.chart&family=test.family&alarm=test_alarm&alarm_unique_id=1&alarm_id=1&alarm_event_id=2&alarm_when=1594067861"},{"offset":93,"length":49,"type":"italic"}]}}
--- END received response ---
RECEIVED HTTP RESPONSE CODE: 200
2020-07-06 22:37:41: alarm-notify.sh: INFO: sent telegram notification for: superawesomeserver.example.com test.chart.test_alarm is CRITICAL to '-123456789'
# OK

# SENDING TEST CLEAR ALARM TO ROLE: sysadmin
2020-07-06 22:37:41: alarm-notify.sh: DEBUG: Loading config file '/opt/netdata/usr/lib/netdata/conf.d/health_alarm_notify.conf'...
2020-07-06 22:37:41: alarm-notify.sh: DEBUG: Loading config file '/opt/netdata/etc/netdata/health_alarm_notify.conf'...
--- BEGIN curl command ---
/bin/curl --data-urlencode disable_notification=true --data-urlencode parse_mode=HTML --data-urlencode disable_web_page_preview=true --data-urlencode $'text=\342\234\205 superawesomeserver.example.com recovered - <b>test alarm</b>\ntest.chart (test.family)\n<a href="https://app.netdata.cloud/alarms/redirect?agentID=17cdcd41-e46b-420a-8699-88acfba57fc1&host=superawesomeserver.example.com&chart=test.chart&family=test.family&alarm=test_alarm&alarm_unique_id=1&alarm_id=1&alarm_event_id=3&alarm_when=1594067861">test alarm (alarm was raised for 3 seconds)</a>\n<i>this is a test alarm to verify notifications work</i>' https://api.telegram.org/bot111122223:7OpFlFFRzRBbrUUmIjj5HF9Ox2pYJZy5/sendMessage\?chat_id=-123456789 
--- END curl command ---
--- BEGIN received response ---
{"ok":true,"result":{"message_id":23,"from":{"id":1234567890,"is_bot":true,"first_name":"superawesome","username":"superawesome_bot"},"chat":{"id":-123456789,"title":"superawesome monitoring","type":"group","all_members_are_administrators":false},"date":1594067861,"text":"\u2705 superawesomeserver.example.com recovered - test alarm\ntest.chart (test.family)\ntest alarm (alarm was raised for 3 seconds)\nthis is a test alarm to verify notifications work","entities":[{"offset":2,"length":16,"type":"url"},{"offset":31,"length":10,"type":"bold"},{"offset":54,"length":11,"type":"url"},{"offset":67,"length":43,"type":"text_link","url":"https://app.netdata.cloud/alarms/redirect?agentID=17cdcd41-e46b-420a-8699-88acfba57fc1&host=superawesomeserver.example.com&chart=test.chart&family=test.family&alarm=test_alarm&alarm_unique_id=1&alarm_id=1&alarm_event_id=3&alarm_when=1594067861"},{"offset":111,"length":49,"type":"italic"}]}}
--- END received response ---
RECEIVED HTTP RESPONSE CODE: 200
2020-07-06 22:37:41: alarm-notify.sh: INFO: sent telegram notification for: superawesomeserver.example.com test.chart.test_alarm is CLEAR to '-123456789'
# OK
```
<img src="https://user-images.githubusercontent.com/6555967/86650132-b9445a00-bfe2-11ea-86e6-285fe19c044b.png" width="300" />

5. **Real alarm notifications result into the following**
```
Example 1:
curl: (77) error setting certificate verify locations:
  CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
2020-07-06 19:21:24: alarm-notify.sh: ERROR: failed to send telegram notification for: superawesomeserver.example.com net_packets.enp68s0.inbound_packets_dropped_ratio is WARNING to '-123456789' with HTTP error code 000.

Example 2:
curl: (77) error setting certificate verify locations:
  CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
2020-07-06 22:15:30: alarm-notify.sh: ERROR: failed to send telegram notification for: superawesomeserver.example.com cgroup_foldingathome.cpu_limit.cgroup_10min_cpu_usage is WARNING to '-123456789' with HTTP error code 000.
```

6. Output of `ls -al /etc/ssl/`
**Note:** This menu structure is like this because of the dirty symlink fix from issue [#8966](https://github.com/netdata/netdata/issues/8966#issuecomment-636676683)
```
total 16
drwxr-xr-x.  5 root root   126 Jul  2 23:57 .
drwxr-xr-x. 16 root root   232 Jun 15 20:11 ..
lrwxrwxrwx.  1 root root    49 Dec 11  2019 cert.pem -> /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
drwxr-xr-x.  2 root root    81 Jul  6 22:17 certs
-rw-r--r--.  1 root root   412 Apr 24 05:00 ct_log_list.cnf
drwxr-xr-x.  2 root root     6 Apr 24 05:34 misc
-rw-r--r--.  1 root root 11225 Apr 24 05:00 openssl.cnf
drwxr-xr-x.  2 root root     6 Apr 24 05:34 private
lrwxrwxrwx.  1 root root     8 Jun 30 20:07 ssl -> /etc/ssl
lrwxrwxrwx.  1 root root    12 Jul  2 23:57 tls -> /etc/pki/tls
```

7. Output of `ls -al /etc/ssl/certs`
```
total 0
drwxr-xr-x. 2 root root  81 Jul  6 22:17 .
drwxr-xr-x. 5 root root 126 Jul  2 23:57 ..
lrwxrwxrwx. 1 root root  49 Dec 11  2019 ca-bundle.crt -> /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
lrwxrwxrwx. 1 root root  55 Dec 11  2019 ca-bundle.trust.crt -> /etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt
```

8. If I undo the dirty symlink fix from issue [#8966](https://github.com/netdata/netdata/issues/8966#issuecomment-636676683) with the following commands the Telegram notifications work, but the Netdata ACLK stops working again with kickstart-static64.sh on Netdata version v1.23.1 Stable
```
$ sudo rpm --nodeps -e ca-certificates
$ sudo dnf install ca-certificates

$ ls -al /etc/ssl
total 16
drwxr-xr-x.   2 root root    19 Jul  6 23:14 .
drwxr-xr-x. 158 root root 12288 Jul  6 23:14 ..
lrwxrwxrwx.   1 root root    16 Dec 11  2019 certs -> ../pki/tls/certs
```

##### Expected behavior

Real alarm notifications should be sent to the Telegram chat **AND** Netdata ACLK should work on distros that only officially support kickstart-static64.sh installations.

**Comment by ThoSap** [comment]
Maybe PR [#9263](https://github.com/netdata/netdata/pull/9263) did indeed fix the issue with ACLK but I still experience this issue in my kickstart-static64.sh installation because I previously created the symlink as stated here [#8966](https://github.com/netdata/netdata/issues/8966#issuecomment-636676683) and the installer then somehow detected `/etc/ssl/` instead of `/etc/pki/tls/`.
With this dirty symlink fix of issue [#8966](https://github.com/netdata/netdata/issues/8966#issuecomment-636676683) of course `alarm-notify.sh`  cannot find the file `/etc/ssl/certs/ca-certificates.crt`.

Maybe `alarm-notify.sh` is still using the original symlink `/etc/ssl/certs/ -> /etc/pki/tls/certs/` of package `ca-certificates` instead of the new symlink `/opt/netdata/etc/ssl/ -> /etc/pki/tls/` created upon on Netdata install or update from PR [#9263](https://github.com/netdata/netdata/pull/9263).

**Comment by thiagoftsm** [comment]
Hi @ThoSap,

@Ferroin, please, can you take a look on this?  I have the `health_alarm_notify.conf` configured with Telegram and I receive normally the messages on my bot, but I normally compile Netdata from scratch. 

I was reading `curl` documentation, and I observed that it allow us to change the directory to check the peer (`--capath`), it is possible that if we use it during the installation the problem can be fixed.

Best regads!

**Comment by Ferroin** [comment]
I _think_ this is fallout from the recent changes to how we handle certificate validation in our static builds. I'll need to look a bit deeper to determine for certain what's going on here.

**Comment by Ferroin** [comment]
OK, I _think_ I've figured it out. It looks like cURL is brain-dead and does not default to letting the SSL library sort out certificates if cURL itself cannot find them. I should have a PR up to fix this later today.

**Comment by prologic** [comment]
Nice work @Ferroin !

**Comment by Ferroin** [comment]
Fix merged, it should be in the next nightly (which will be out around 02:00 UTC tomorrow). Sorry about how long this sat here with almost no response.

**Comment by Simonmicro** [comment]
Hi, when exactly was this fixed? As I'm still experiencing this issue on multiple machines:
```
curl: (77) error setting certificate verify locations:  CAfile: /opt/netdata/etc/ssl/certs/ca-bundle.crt CApath: none
2020-12-04 13:57:46: alarm-notify.sh: ERROR: failed to send telegram notification for: [hostname] [alertname] is CRITICAL to '[chatid]' with HTTP response status code 000.
```

To make sure it is not my fault I also tried reinstalling the current kickstart static 64 version - no change... What is going on here?

Just in case - my os metadata:
```
$ cat /etc/debian_version
10.6
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by campio97** [comment]
Hello, i have the same problem on version 1.37.0-40-g05e903688.
```
curl: (77) error setting certificate verify locations:  CAfile: /etc/ssl/certs/ca-certificates.crt CApath: none

2022-12-13 15:26:24: alarm-notify.sh: ERROR: failed to send telegram notification for: xxx-website mem.available.ram_available is CRITICAL to '-xxxxxxxxx' with HTTP response status code 000.
```

Netdata is installed in /opt/netdata

**Comment by campio97** [comment]
I forgot to mention that the operating system is amazon linux 2, I think this is where the problem comes from
