### ISSUE TITLE
Netdata stops collecting metrics after a while

### ISSUE THREAD

**Issue by Elbje** [netdata/netdata#9530]
##### Bug report summary

We have netdata running on almost 1000 servers, after a while netdata stops collecting metrics. The dashboard still works, the api endpoint also keeps working, it looks like everything is still functional except that no new metrics are being stored. 
I have looked at error.log every time this happened (on all our servers) and it looks like netdata stops collecting/saving metrics after these messages in error.log:
```
2020-07-12 20:35:06: netdata INFO  : MAIN : Deleting data file "/var/cache/netdata/dbengine/datafile-1-0000000056.ndf".
2020-07-12 20:35:06: netdata INFO  : MAIN : Creating new data and journal files in path /var/cache/netdata/dbengine
2020-07-12 20:35:06: netdata INFO  : MAIN : Deleting chart 'net.vethbb31177' ('net.vethbb31177') from disk...
2020-07-12 20:35:06: netdata ERROR : MAIN : Cannot read left-over chart directory to be deleted '/var/cache/netdata/net.vethbb31177' (errno 2, No such file or directory)
2020-07-12 20:35:06: netdata INFO  : MAIN : Deleting chart 'net_packets.vethbb31177' ('net_packets.vethbb31177') from disk...
2020-07-12 20:35:06: netdata ERROR : MAIN : Cannot read left-over chart directory to be deleted '/var/cache/netdata/net_packets.vethbb31177' (errno 2, No such file or directory)
2020-07-12 20:35:06: netdata INFO  : MAIN : Deleting chart 'net.veth85a04f7' ('net.veth85a04f7') from disk...
2020-07-12 20:35:06: netdata ERROR : MAIN : Cannot read left-over chart directory to be deleted '/var/cache/netdata/net.veth85a04f7' (errno 2, No such file or directory)
2020-07-12 20:35:06: netdata INFO  : MAIN : Deleting chart 'net_packets.veth85a04f7' ('net_packets.veth85a04f7') from disk...
2020-07-12 20:35:06: netdata ERROR : MAIN : Cannot read left-over chart directory to be deleted '/var/cache/netdata/net_packets.veth85a04f7' (errno 2, No such file or directory)
2020-07-12 20:35:06: netdata INFO  : MAIN : Created data file "/var/cache/netdata/dbengine/datafile-1-0000000075.ndf".
2020-07-12 20:35:06: netdata INFO  : MAIN : Created journal file "/var/cache/netdata/dbengine/journalfile-1-0000000075.njf".
2020-07-12 20:35:06: netdata INFO  : MAIN : Deleting chart 'mdstat.mdstat_health' ('mdstat.mdstat_health') from disk...
2020-07-12 20:35:06: netdata ERROR : MAIN : Cannot read left-over chart directory to be deleted '/var/cache/netdata/mdstat.mdstat_health' (errno 2, No such file or directory)
2020-07-12 20:35:06: netdata INFO  : MAIN : Deleting chart 'mdstat.md0_disks' ('mdstat.md0_disks') from disk...
2020-07-12 20:35:06: netdata ERROR : MAIN : Cannot read left-over chart directory to be deleted '/var/cache/netdata/mdstat.md0_disks' (errno 2, No such file or directory)
2020-07-12 20:35:06: netdata INFO  : MAIN : Deleting chart 'mdstat.md0_mismatch' ('mdstat.md0_mismatch') from disk...
2020-07-12 20:35:06: netdata ERROR : MAIN : Cannot read left-over chart directory to be deleted '/var/cache/netdata/mdstat.md0_mismatch' (errno 2, No such file or directory)
2020-07-12 20:35:06: netdata INFO  : MAIN : Deleting chart 'mdstat.md0_operation' ('mdstat.md0_operation') from disk...
2020-07-12 20:35:06: netdata ERROR : MAIN : Cannot read left-over chart directory to be deleted '/var/cache/netdata/mdstat.md0_operation' (errno 2, No such file or directory)
2020-07-12 20:35:06: netdata INFO  : MAIN : Deleting chart 'mdstat.md0_finish' ('mdstat.md0_finish') from disk...
2020-07-12 20:35:06: netdata ERROR : MAIN : Cannot read left-over chart directory to be deleted '/var/cache/netdata/mdstat.md0_finish' (errno 2, No such file or directory)
2020-07-12 20:35:06: netdata INFO  : MAIN : Deleting chart 'mdstat.md0_speed' ('mdstat.md0_speed') from disk...
2020-07-12 20:35:06: netdata ERROR : MAIN : Cannot read left-over chart directory to be deleted '/var/cache/netdata/mdstat.md0_speed' (errno 2, No such file or directory)
2020-07-12 20:35:06: netdata INFO  : MAIN : Deleting chart 'mdstat.md1_availability' ('mdstat.md1_availability') from disk...
2020-07-12 20:35:06: netdata ERROR : MAIN : Cannot read left-over chart directory to be deleted '/var/cache/netdata/mdstat.md1_availability' (errno 2, No such file or directory)
2020-07-12 20:35:06: netdata INFO  : MAIN : Deleting data and journal file pair.
2020-07-12 20:35:06: netdata INFO  : MAIN : Deleted journal file "/var/cache/netdata/dbengine/journalfile-1-0000000056.njf".
2020-07-12 20:35:06: netdata INFO  : MAIN : Deleted data file "/var/cache/netdata/dbengine/datafile-1-0000000056.ndf".
2020-07-12 20:35:06: netdata INFO  : MAIN : Reclaimed 14413824 bytes of disk space.
```

##### OS / Environment

I installed netdata via apt. Here is my OS info: 
```
Linux *myServerName* 4.15.0-45-generic #48~16.04.1-Ubuntu SMP Tue Jan 29 18:03:48 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=16.04
/etc/lsb-release:DISTRIB_CODENAME=xenial
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 16.04.5 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="16.04.5 LTS (Xenial Xerus)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 16.04.5 LTS"
/etc/os-release:VERSION_ID="16.04"
/etc/os-release:HOME_URL="http://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="http://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
/etc/os-release:VERSION_CODENAME=xenial
/etc/os-release:UBUNTU_CODENAME=xenial
```

##### Netdata version

 
netdata v1.23.0

##### Component Name

I don't really know but im guessing its database ? 

##### Steps To Reproduce

1. install netdata via apt
2. use this simple config file: 
```
[global]
    run as user = netdata

    # the default database size - 1 hour
    history = 3600

    # some defaults to run netdata with least priority
    process scheduling policy = idle
    OOM score = 1000

[web]
    web files owner = root
    web files group = netdata

    default port = 19999
    # by default do not expose the netdata port
    bind to = 0.0.0.0
[plugins]
    cgroups = no
    apps = no
    go.d = no
``` 
3. wait until netdata stops collecting/saving new metrics

##### Expected behavior
I expect netdata to keep collecting/saving new metrics....
I am not really sure if this is a bug or I am doing something wrong.  If I'm doing something wrong I would very much appreciate your help!

**Comment by Elbje** [comment]
also I have tested this with version 1.23.1 and had the same issue

**Comment by mfundul** [comment]
We have detected and fixed some bugs that affect both versions 1.23.0 and 1.23.1
Can you test the latest version and see if your problem is fixed? The [official installation method](https://learn.netdata.cloud/docs/agent/packaging/installer#automatic-one-line-installation-script) also pulls the latest code from master:
```
bash <(curl -Ss https://my-netdata.io/kickstart.sh)
```

**Comment by Elbje** [comment]
Thanks for your reply. Since we did not feel comfortable using the install script, we downgraded to version 1.22.1 and the bug seems to be not present in this version. Using this version is okay for us, thanks for your help!

Do you know when the next release (including these fixes) will be ?

**Comment by mfundul** [comment]
I expect the next release to be out by next week if all goes well.

**Comment by ilyam8** [comment]
> Since we did not feel comfortable using the install script

This is understandable, but still it would be very nice if you could test latest master on one of your servers to ensure it is fixed, if it is not we need to do it before release.

**Comment by Elbje** [comment]
I added the nightly build repo (netdata/netdata-edge) and installed the latest version (1.32.177) to one of our servers, I suppose this is the same version as the latest master ?
I'll keep you updated on the performance of this version on our server.

**Comment by mfundul** [comment]
Btw the next release is out.

**Comment by Elbje** [comment]
Version 1.23.1-77-nightly still has the same bug. Netdata stopped saving/collecting new metrics at Friday 2020-07-17 15:11:31 after the same logs I saw in version 1.23.1 where present in error.log:

```
2020-07-17 15:11:31: netdata INFO  : MAIN : Deleting data file "/var/cache/netdata/dbengine/datafile-1-0000000089.ndf".
2020-07-17 15:11:31: netdata INFO  : MAIN : Rotated unknown archived metric.
2020-07-17 15:11:31: netdata INFO  : MAIN : Rotated unknown archived metric.
2020-07-17 15:11:31: netdata INFO  : MAIN : Rotated unknown archived metric.
2020-07-17 15:11:31: netdata INFO  : MAIN : Rotated unknown archived metric.
2020-07-17 15:11:31: netdata INFO  : MAIN : Rotated unknown archived metric.
2020-07-17 15:11:31: netdata INFO  : MAIN : Rotated unknown archived metric.
2020-07-17 15:11:31: netdata INFO  : MAIN : Rotated unknown archived metric.
2020-07-17 15:11:31: netdata INFO  : MAIN : Rotated unknown archived metric.
2020-07-17 15:11:31: netdata INFO  : MAIN : Rotated unknown archived metric.
2020-07-17 15:11:31: netdata INFO  : MAIN : Rotated unknown archived metric.
2020-07-17 15:11:31: netdata INFO  : MAIN : Rotated unknown archived metric.
2020-07-17 15:11:31: netdata INFO  : MAIN : Rotated unknown archived metric.
2020-07-17 15:11:31: netdata INFO  : MAIN : Deleting chart 'mdstat.mdstat_health' ('mdstat.mdstat_health') from disk...
2020-07-17 15:11:31: netdata ERROR : MAIN : Cannot read left-over chart directory to be deleted '/var/cache/netdata/mdstat.mdstat_health' (errno 2, No such file or directory)
2020-07-17 15:11:31: netdata INFO  : MAIN : Deleting chart 'mdstat.md0_disks' ('mdstat.md0_disks') from disk...
2020-07-17 15:11:31: netdata ERROR : MAIN : Cannot read left-over chart directory to be deleted '/var/cache/netdata/mdstat.md0_disks' (errno 2, No such file or directory)
2020-07-17 15:11:31: netdata INFO  : MAIN : Deleting chart 'mdstat.md0_mismatch' ('mdstat.md0_mismatch') from disk...
2020-07-17 15:11:31: netdata ERROR : MAIN : Cannot read left-over chart directory to be deleted '/var/cache/netdata/mdstat.md0_mismatch' (errno 2, No such file or directory)
2020-07-17 15:11:31: netdata INFO  : MAIN : Deleting chart 'mdstat.md0_operation' ('mdstat.md0_operation') from disk...
2020-07-17 15:11:31: netdata ERROR : MAIN : Cannot read left-over chart directory to be deleted '/var/cache/netdata/mdstat.md0_operation' (errno 2, No such file or directory)
2020-07-17 15:11:31: netdata INFO  : MAIN : Deleting chart 'mdstat.md0_finish' ('mdstat.md0_finish') from disk...
2020-07-17 15:11:31: netdata ERROR : MAIN : Cannot read left-over chart directory to be deleted '/var/cache/netdata/mdstat.md0_finish' (errno 2, No such file or directory)
2020-07-17 15:11:31: netdata INFO  : MAIN : Deleting chart 'mdstat.md0_speed' ('mdstat.md0_speed') from disk...
2020-07-17 15:11:31: netdata ERROR : MAIN : Cannot read left-over chart directory to be deleted '/var/cache/netdata/mdstat.md0_speed' (errno 2, No such file or directory)
```

**Comment by Elbje** [comment]
Thank you for notifying me @mfundul . I will try the new release on the same server, hopefully the bug is fixed

**Comment by HansGeering** [comment]
It seems the bug is still present on the latest release. Trying to update to the latest release shows that I am on the latest:
```Tue 21 Jul 10:26:26 BST 2020 : INFO:  Current Version: 001023002032
Tue 21 Jul 10:26:26 BST 2020 : INFO:  Latest Version: 001023002032```

Where last night netdata tried to drop some metrics:
```
./error.log.1:2096:2020-07-21 01:48:06: netdata INFO  : MAIN : Deleting chart 'disk_space._home' ('disk_space._home') from disk...
./error.log.1:2097:2020-07-21 01:48:06: netdata ERROR : MAIN : Cannot read left-over chart directory to be deleted '/var/cache/netdata/disk_space._home' (errno 2, No such file or directory)
./error.log.1:2098:2020-07-21 01:48:06: netdata INFO  : MAIN : Deleting chart 'disk_inodes._home' ('disk_inodes._home') from disk...
./error.log.1:2099:2020-07-21 01:48:06: netdata ERROR : MAIN : Cannot read left-over chart directory to be deleted '/var/cache/netdata/disk_inodes._home' (errno 2, No such file or directory)
```
Weirdly enough it's just the _home sub-metric, all the others in disk_space and disk_inodes are still being collected. The volume has not been unmounted at any time, and restarting netdata does not help the problem.

**Comment by mfundul** [comment]
I just noticed that your config file is using `history = 3600` which is not applicable to the default `memory mode` which is `dbengine` so what actually is taking place is you're using `dbengine` with the default values.

I will look into that some more, try and reproduce it. In the meantime can you share your `error.log` over a longer period of time, say since agent start and until after the time the metrics stop being collected? If you don't wish to share your logs in public but would not object sending them to netdata you can send them to me directly via e-mail at markos@netdata.cloud

**Comment by mfundul** [comment]
@Elbje some questions:
1. do all metrics stop being collected, or is it only a few of them?
2. Is it a subset of charts that freeze?
3. Is it only the metrics that are described in the `error.log` file the frozen ones, or different ones?
4. Do the `md` or the `veth` devices exist on the hosts when they stopped data collection, or did they disappear from the host system as well?

**Comment by Elbje** [comment]
@mfundul 
 1. yes, all metrics stop being collected
 2. All charts freeze, but the dashboard stays operational. I can scrol back in time and see the saved values. If i scroll forward (past 
     the last collection timestamp) the charts stay empty.
 3. No not only those, all metrics are frozen.
 4. I'm 100% certain that the md device does still exist on the host when the data collection stops. I can't tell for sure with the 
     veth, I would have to look that up.

**Comment by Elbje** [comment]
Oh I didn't know, thanks for pointing out the config mistake, I will correct these.

**Comment by mfundul** [comment]
@Elbje @HansGeering can you test the Pull Request to see if the problem is resolved? You can follow these instructions:
https://github.com/netdata/netdata/pull/9583#issuecomment-662364771

**Comment by HansGeering** [comment]
Thanks @mfundul - but unfortunately for me the missing metric has not returned. Netdata did not crash (as in the other issue) but kept on running, but completely ignores one specific drive (and the complete /proc/mdstat). Do you want me to create that into a separate issue?

**Comment by mfundul** [comment]
> 
> 
> Thanks @mfundul - but unfortunately for me the missing metric has not returned. Netdata did not crash (as in the other issue) but kept on running, but completely ignores one specific drive (and the complete /proc/mdstat). Do you want me to create that into a separate issue?

This specific issue describes a condition where all netdata charts suddenly stop collecting, during the cleanup of obsolete charts of mdstat. This is related to the crash in the other issue, but quite different from not collecting a specific device which has reappeared.

You can try refreshing your dashboard URL in your browser (e.g. `127.0.0.1:19999`), this could show new charts that weren't available before. Feel free to create a new issue if you feel there is a different problem that needs to be addressed.

**Comment by Elbje** [comment]
@mfundul I will test the PR right now, I'll keep you updated

**Comment by Elbje** [comment]
@mfundul good news, the PR has fixed the bug. Netdata has been running stable for 4 days now. In the past, the bug was usually triggered in the first 24h after start up.
