### ISSUE TITLE
Netdata install failing on multiple servers with "Static binary checksum validation failed"

### ISSUE THREAD

**Issue by thomasjosif** [netdata/netdata#9919]
##### Bug report summary

Fresh NetData agent installation "Tarball checksum validation failed." - Happening on multiple different machines / OS environments.

Full Error:

ABORTED  Static binary checksum validation failed. Stopping netdata installation and leaving binary in /tmp/netdata-kickstart-KKwvh9yish

##### OS / Environment

**Server 1**
```/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=18.04
/etc/lsb-release:DISTRIB_CODENAME=bionic
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="18.04.5 LTS (Bionic Beaver)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 18.04.5 LTS"
/etc/os-release:VERSION_ID="18.04"
/etc/os-release:HOME_URL="https://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="https://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
/etc/os-release:PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
/etc/os-release:VERSION_CODENAME=bionic
/etc/os-release:UBUNTU_CODENAME=bionic
```

**Server 2** 
```/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=18.04
/etc/lsb-release:DISTRIB_CODENAME=bionic
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="18.04.5 LTS (Bionic Beaver)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 18.04.5 LTS"
/etc/os-release:VERSION_ID="18.04"
/etc/os-release:HOME_URL="https://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="https://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
/etc/os-release:PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
/etc/os-release:VERSION_CODENAME=bionic
/etc/os-release:UBUNTU_CODENAME=bionic
```

**Server 3**
```
/etc/centminmod-release:123.09beta01.b548
/etc/centos-release:CentOS Linux release 7.8.2003 (Core)
/etc/os-release:NAME="CentOS Linux"
/etc/os-release:VERSION="7 (Core)"
/etc/os-release:ID="centos"
/etc/os-release:ID_LIKE="rhel fedora"
/etc/os-release:VERSION_ID="7"
/etc/os-release:PRETTY_NAME="CentOS Linux 7 (Core)"
/etc/os-release:ANSI_COLOR="0;31"
/etc/os-release:CPE_NAME="cpe:/o:centos:centos:7"
/etc/os-release:HOME_URL="https://www.centos.org/"
/etc/os-release:BUG_REPORT_URL="https://bugs.centos.org/"
/etc/os-release:
/etc/os-release:CENTOS_MANTISBT_PROJECT="CentOS-7"
/etc/os-release:CENTOS_MANTISBT_PROJECT_VERSION="7"
/etc/os-release:REDHAT_SUPPORT_PRODUCT="centos"
/etc/os-release:REDHAT_SUPPORT_PRODUCT_VERSION="7"
/etc/os-release:
/etc/redhat-release:CentOS Linux release 7.8.2003 (Core)
/etc/system-release:CentOS Linux release 7.8.2003 (Core)
```

##### Netdata version

 Netdata is not installing (N/A)

##### Component Name

N/A?

##### Steps To Reproduce

1. Run netdata install with: bash <(curl -Ss https://my-netdata.io/kickstart.sh)

##### Expected behavior

Netdata installation

**Comment by thomasjosif** [comment]
Seems like it was fixed, very strange issue.

**Comment by OdysLam** [comment]
@thomasjosif , thanks for reporting it. We had a caching issue with the provider from which the package was downloaded. It is now fixed.

Thanks for contributing with issues  and welcome to our community :)

**Comment by prologic** [comment]
> @thomasjosif , thanks for reporting it. We had a caching issue with the provider from which the package was downloaded. It is now fixed.
> 
> Thanks for contributing with issues and welcome to our community :)

it actually isn't fixed. But thanks for reminding me, I'll be reaching out to Google support to see if there are things we can do here. This is a bit of a tough one, "caching" is hard™

**Comment by yasharne** [comment]
Hi
I also have the same problem when I try to update my netdata:
```
/opt/netdata/usr/libexec/netdata/netdata-updater.sh 
Checking if a newer version of the updater script is available.
Downloading newest version of updater script.
Mon Jan 17 16:52:50 +0330 2022 : INFO:  Entering /tmp/netdata-updater-V7wwbrZzsZ
Mon Jan 17 16:52:51 +0330 2022 : INFO:  Current Version: 00103200000000
Mon Jan 17 16:52:51 +0330 2022 : INFO:  Latest Version: 00103200100000
Mon Jan 17 16:52:51 +0330 2022 : INFO:  Update available
Mon Jan 17 16:53:04 +0330 2022 : ERROR:  FAILED TO UPDATE NETDATA : Static binary checksum validation failed. Stopping netdata installation and leaving binary in /tmp/netdata-updater-V7wwbrZzsZ
Usually this is a result of an older copy of the file being cached somewhere and can be resolved by simply retrying in an hour.
```
its been two days since I'm getting this error

**Comment by ilyam8** [comment]
@yasharne fixed in #11986

**Comment by yasharne** [comment]
Thanks @ilyam8 for your fast action

**Comment by yasharne** [comment]
one more thing @ilyam8 , can we have sort of backward compatibility? in our case, we have more than 500 netdata agents and now we have to uninstall and then install the new version to upgrade to the latest version

**Comment by ilyam8** [comment]
What backward compatibility problem do you have? I think there is no such problem if you regularly update from one stable version to another.

**Comment by yasharne** [comment]
You are right, I thought we also need to update the updater script on our agents

**Comment by ilyam8** [comment]
There is [self_update()](https://github.com/netdata/netdata/blob/e91d1110e5998ede7bc8aecf5309c28176361acf/packaging/installer/netdata-updater.sh#L223-L238) function in the updater script (download the latest `netdata-updater.sh` from GitHub if it is newer than the local copy).

**Comment by yasharne** [comment]
The issue still persists @ilyam8

**Comment by ilyam8** [comment]
@netdata/agent-sre, please check https://github.com/netdata/netdata/issues/9919#issuecomment-1136795266
